### ISSUE TITLE
Add handlebars-helpers

### ISSUE THREAD

**Issue by d6233** [tars/tars#106]
https://github.com/assemble/handlebars-helpers
https://github.com/shannonmoeller/handlebars-layouts
https://github.com/helpers/handlebars-helper-prettify

**Comment by artem-malko** [comment]
Что именно нужно взять?
What do you want to have?

**Comment by d6233** [comment]
all

**Comment by artem-malko** [comment]
+ добавить легкую возможность подключения своих хелперов.

**Comment by artem-malko** [comment]
https://github.com/helpers/handlebars-helper-prettify — не будет использоваться, так как #69

**Comment by artem-malko** [comment]
https://github.com/shannonmoeller/handlebars-layouts — будет реализовано в версии 2.0 На данный момент можно сделать самому, расширив файловую структуру.

**Comment by artem-malko** [comment]
In version-1-4-0
