### ISSUE TITLE
The page with links to all compiled pages

### ISSUE THREAD

**Issue by d6233** [tars/tars#107]
Создавать страницу при build, с ссылками на страницы которые есть в вёрстке

**Comment by artem-malko** [comment]
:+1:

**Comment by d6233** [comment]
Может поможет
https://github.com/klei/gulp-inject
https://github.com/filso/gulp-linker
http://stackoverflow.com/questions/30961751/how-to-add-links-of-other-html-files-to-index-html-automatically-using-gulp
http://rileyjshaw.com/blog/how-to-generate-a-static-site-from-a-folder-of-assets-using-Gulp/

**Comment by artem-malko** [comment]
In version-1.6.0
