### ISSUE TITLE
Group media queries

### ISSUE THREAD

**Issue by d6233** [tars/tars#108]
Объединять media quaries в конце css файла при build
https://www.npmjs.com/package/gulp-combine-media-queries

**Comment by artem-malko** [comment]
@d6233 этот пакет не работает и ломает весь css, если в коде есть keyframes. Так что пкоа что это не реализуемо. Я пристально слежу за их репозиторием, так что как только, так сразу.

**Comment by d6233** [comment]
https://github.com/Se7enSky/group-css-media-queries
https://github.com/hail2u/node-css-mqpacker
https://github.com/frontendfriends/node-combine-mq
Вот такой список альтернатив нашёл, возможно тут баги все поправлены. Может стоит открыть issue, что бы люди, которые пользовались плагинами выше, рассказали о них?

**Comment by artem-malko** [comment]
@d6233 из того списка подходит только https://github.com/hail2u/node-css-mqpacker
Но у него есть проблема, как и у любого подобного пакета: https://github.com/hail2u/node-css-mqpacker#css-applying-order
Как с этим быть?

**Comment by d6233** [comment]
Что то не понял о чём там?

**Comment by artem-malko** [comment]
@d6233 там говорится, что порядок правил может нарушаться.

**Comment by d6233** [comment]
Мне кажется если правильно писать стили, то не должно быть такого, а там хз

**Comment by artem-malko** [comment]
@d6233 можешь потыкать у себя на каком-нить проекте? Или просто отдельно. Только должно быть большое кол-во этих медиа-выражений + в разных местах.

**Comment by d6233** [comment]
Ты хочешь в 1.6.0 его засунуть?

**Comment by artem-malko** [comment]
@d6233 если успеешь вердикт свой дать до релиза, то можно и в 1.6.0

**Comment by d6233** [comment]
https://github.com/hail2u/node-css-mqpacker/issues/16
ты тут читал? Там ничего серьёзного?А то я ж с англ. не очень...

**Comment by artem-malko** [comment]
@d6233 читал, и вот прям не нравится мне эта штука. Смотри, так как это postcss-плагин, его каждый может себе сам поставить, оценивая все риски.
В целом, на размер выходного файла это не сильно влияет.

**Comment by d6233** [comment]
Я вот тоже почитал немного, и понял что это всё неконтролируемо, поэтому да, логичней будет самому таск сделать

**Comment by artem-malko** [comment]
@d6233 тогда, закрываю тикет, к сожалению.

**Comment by NabAlexey** [comment]
@artem-malko все еще нет?
