### ISSUE TITLE
В документации не сказано как создать user-package.js

### ISSUE THREAD

**Issue by rtxrulez** [tars/tars#111]
https://github.com/tars/tars/blob/master/docs/ru/tasks-workflow.md
Конечно я могу просто на подобие package.json создать свой файл. Но хорошо бы если в документации описывалось как создавать такой файл и как туда прописывать зависимости при установке своих пакетов.

**Comment by artem-malko** [comment]
@rtxrulez Если используется CLI, то user-package.json не нужен. Каждый проект имеет свой собственный package.json и в него нужно писать свои зависимости и вообще инфу по проекту. 
user-package.json Необходим только в случае использования TARS без CLI. Допишу об этом в доке.

**Comment by rtxrulez** [comment]
@artem-malko Еще в документации не понятно, где запускаются собственные таски. Сказано как их создать, но как запускать ? И можно ли их запускать как tars my-task ?

**Comment by rtxrulez** [comment]
@artem-malko https://github.com/tars/tars-cli#tars-add-module-
Не очевидно в каком порядке нужно писать команды. Хорошо бы пример.

**Comment by artem-malko** [comment]
@rtxrulez учту, хорошие замечания.

**Comment by artem-malko** [comment]
@rtxrulez смотри, так больше понятно про команды в tars-cli: https://github.com/tars/tars-cli/tree/TARS-2-cli-for-options
