### ISSUE TITLE
Problem with jade

### ISSUE THREAD

**Issue by bagahunda** [tars/tars#117]
Error during jade compiling.
[10:06:37] 'html:compile-templates' errored after 2.55 ms
[10:06:37] TypeError: object is not a function

Mac OS X El Captan

**Comment by artem-malko** [comment]
@bagahunda I need more info. Did you start your project after it was inited? Did you add your own modules?

**Comment by artem-malko** [comment]
@bagahunda if you use tars-cli, just run tars re-init. If you don't use tars-cli, start gulp re-init.

**Comment by artem-malko** [comment]
@bagahunda send a feedback as a comment here, please.
