### ISSUE TITLE
Как запускать свои таски? 

### ISSUE THREAD

**Issue by dumperize** [tars/tars#123]
Сейчас установили tars-cli. Сделали tars init. Хотим перенести несколько своих taskов. Есть специальное отделение для них - user-tasks (кстати в example-task.js в 6 строке опечатка в слове packges - нет буквы а). 
Теперь у нас есть свой набор отдельных тасков и свои последовательности (которые используют и наши таски и такски тарса).
Теперь вопрос: а как нам их вызвать? 
tars <имя такски> 
не работает
gulp <имя такски> 
не работает (начинает просить все зависимости попорядку такого типа Cannot find module 'gulp-util').
Что же делать? Как использовать свои таски и tars-cli?

В документации указано "Пользовательские таски будут подключены в gulpfile также автоматически, но их необходимо включить в основные-таски в gulpfile, чтобы вы могли их использовать." 
Т.е. используя tars-cli мы можем использовать только dev и build последовательности ?

**Comment by artem-malko** [comment]
Пока да, но уже совсем скоро будет выпущена https://github.com/tars/tars-cli/issues/11
Можете оставить комментарий, какой вы видите эту функциональность.

**Comment by dumperize** [comment]
В идеале хотелось бы получить такую функциональность: 

1. хочется пользоваться tars-cli 
    Для того чтобы постоянно не таскать за собой все npm-modules 
2. хочется иметь возможность обновления самого tars 
    Для получения новых возможностей и версий с исправленными ошибками
3. хочется иметь возможность создавать свои таски и последовательности и запускать их. 
    Для настройки под себя/под проект и тд.  

Исходя из этого должно быть следующее: 

1. необходимо расширить функциональность tars-cli (то что Вы указали - использование кастомных команд). Для того чтобы запускать свои таски и последовательности
2. необходимо нам любителям писать свои таски - не ковырять код tars. Писать только в строго в отведенных для нас местах. В связи с этим мне не понятно, почему был убран user-packages. Соблюдение данного пункта позволило бы нам обновлять tars полностью а свои таски, зависимости переносить копированием пары папок и пары файлов. 

У нас получилось таким образом: мы взяли тарс и вписали куча своего во все внутренности. Теперь вышло уже куча новых версий tars, но накатить мы их не можем (в частности issue https://github.com/tars/tars/issues/81 отисследовать не можем) . Решили опять с нуля аккуратненько вписать свои задачи в последнюю версию tars, туда куда нам это дозволенно. Но оно не запускается=). Вобщем очень ждем развития проекта!

А конкретно про запуск своих taskов (https://github.com/tars/tars-cli/issues/11): 
интерактив тут совсем не нужен. И лучше совсем не заморачиваться и сделать примерно так: 

```
tars 'комманда'  'любая_длинная_строка_с_пробелами'
```
вместо слова 'комманда' можно использовать любое слово
tars встретив его просто передает` 'любая_длинная_строка_с_пробелами'` в gulp

**Comment by artem-malko** [comment]
Про первое в эти выходные сделаю)
Про второе, прочитайте тут: tars/blob/master/docs/ru/tasks-workflow.md user-package.json никуда не делся))

**Comment by artem-malko** [comment]
@dumperize сделал почти так, как вы советовали. TARS-CLI уже обновлен, сейчас в тестировании. Через минут 20 будет релиз.
