### ISSUE TITLE
Проблема с data

### ISSUE THREAD

**Issue by pufflik** [tars/tars#124]
Никак не могу заставить data хоть как-нибудь работать. Как ни бился, все время выплевывает ошибку.
Error: An error occurred with data-files!
SyntaxError: Unexpected token ,
Для примера дублирую модуль head, все файлы переименовываю.

Содержимое html:
 {{text}}

Содержимое data.js:
slider: {
    featured: {
        text: 'Hello!'
    }
}

Вызов на странице index.html:
{{> slider/slider slider.featured}}

И не работает. Уже и _template дублировал и подставлял данные - не хочет компилироваться вообще. index.html попросту не собирается.

**Comment by artem-malko** [comment]
@pufflik а есть ли пустые data.js в проекте?

**Comment by pufflik** [comment]
В общем, в очередной раз попробовал - все получилось. В чем была проблема, так я и не понял :)

**Comment by pufflik** [comment]
И все равно с data продолжают появляться проблемы. Может этот как-то связано с Mac OS, даже не знаю. Сделал один слайдер - все гладко. По аналогии делаю второй - опять те же ошибки. Причем неявные. Бывает даже перестает работать, если переименовываю модуль. Назвал все slider - не работает. Переименовал все в featured - порядок. Какая-то неотслеживаемая логика :(

**Comment by artem-malko** [comment]
@pufflik тут есть два правила:
1) Не должно быть пустых дата-файлов. Создавай модули через tars add-module и тогда data.js будет правильно сформирован.
2) Не должно быть в двух одинаковых объектов в data.js на самом высоком уровне вложенности.

То есть:
````javascript
// moudle1/data.js
module1: {}

// module2/data.js
module1: {}
````
Это не правильно.

**Comment by artem-malko** [comment]
@pufflik вопрос закрыт?

**Comment by pufflik** [comment]
Будем считать, что закрыт, хотя проблема не ушла. И она, судя по всему, с именованием модулей. Если допускаю ошибку в модуле и удаляю, потом создавая модуль с таким же названием, получаю ошибку компилирования. Как такое может происходит, ума не приложу. Возможно какое-то кэширование файлов на уровне операционки.

**Comment by artem-malko** [comment]
@pufflik кеширование есть внутри TARS. Пожалуй заведу баг отдельный для этого, если удасться воспроизвести.

**Comment by wizzzart** [comment]
Была такая же проблема. Дело оказалось в том, что текст в data-файл копировали из макета в Figma. При копировании, оттуда цеплялось форматирование, которое никак не проявлялось визуально, но ломало сборку.
У меня это был Разделительный параграф.
В ворде обозначается как "P SEP", в Юникоде: U+2029
Если форматирование очистить, все работает.
