### ISSUE TITLE
реквестирую описание хелпера formatDate. )

### ISSUE THREAD

**Issue by alexd73** [tars/tars#154]
Привет!
Пишу:
```php
                <p>© {{formatDate 'Y'}} text</p>

```
и получаю ошибку

```shell

TypeError in plugin 'gulp-compile-handlebars'
Message:
    format.replace is not a function
```
Форматы в кавычках пробовал разные.
что я делаю не так?

**Comment by d6233** [comment]
http://assemble.io/helpers/helpers-dates.html
Всё гараздно проще, в data.js пишешь, date=new Date();
А потом выводишь
{formatDate date "%m/%d/%Y"}}
{{formatDate date "%I:%M%p"}}
{{formatDate date "%F"}}
{{formatDate date "%Y%m%dT%H%M%S%z"}}
Как тебе угодно...

**Comment by artem-malko** [comment]
@alexd73 @d6233 спасибо за ответ) Ты прям выручаешь меня каждый раз))

**Comment by artem-malko** [comment]
@alexd73 описывать хелпер внутри доки к TARS не вижу смысла, так как документацию к этому хелперу уже написана и так.
https://github.com/tars/tars/blob/master/docs/ru/handlebars-helpers.md#formatdate-now-i18n Собственно в этом разделе и указана ссылка на доку.

**Comment by d6233** [comment]
@artem-malko Ну, а почему бы и нет :thumbsup:

**Comment by artem-malko** [comment]
@alexd73 issue закрываю? Со всем разобрались?

**Comment by alexd73** [comment]
@d6233 @artem-malko Да, спасибо.
