### ISSUE TITLE
Использование расширения .hbr

### ISSUE THREAD

**Issue by alexd73** [tars/tars#156]
Тут такая ситуация:
html файлах подсветка синтаксиса не совсем точная и линтер выдает ошибки.
Пробовал переименовать в *.html.hbr, но сборка проекта не проходит. 
Можно как-то решить этот вопрос?

**Comment by artem-malko** [comment]
@alexd73 есть поддержка расширения hbs. Подойдет?)

**Comment by alexd73** [comment]
То что надо )

**Comment by alexd73** [comment]
Проверил, но pages/index.hbs хавает (html:compile-templates проходит без ошибок), а index.html не формирует.

**Comment by artem-malko** [comment]
#157  завел баг

**Comment by artem-malko** [comment]
Уже даже закрыл)
