### ISSUE TITLE
css watcher

### ISSUE THREAD

**Issue by sosnovskyas** [tars/tars#159]
Использую SASS, для написания CSS, и вотчер перезагружает страницу вместо того чтобы просто заменить CSS. Очень неудобно и на самом делел странно, ведь в тасках стоит stream: true, что подразумевает замену без перезагрузки.

**Comment by artem-malko** [comment]
@sosnovskyas есть возможность заюзать эту фичу, просто она не всегда стабильно работает, поэтому была отключена.
Заюзать можно так, как указано в этом gulpfile (это из версии 1.6.0 ): https://github.com/tars/tars/blob/version-1.6.0/gulpfile.js#L183 На месте параметра injectChanges необходимо выставить true.

**Comment by sosnovskyas** [comment]
Спасибо, помогло.
