### ISSUE TITLE
Добавить поддержку coffee

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#16]

**Comment by artem-malko** [comment]
Полезные ссылки:
https://www.npmjs.com/package/gulp-coffeelint
https://www.npmjs.com/package/coffeelint-stylish

**Comment by artem-malko** [comment]
Возможно это не имеет смысла, и стоит добавить транслятор из es6 to es5?

**Comment by Grawl** [comment]
Для любителей сахара вроде меня было бы приятно иметь возможность использовать CoffeeScript.

**Comment by artem-malko** [comment]
@Grawl а как насчет ES6?) Или скобки все же не хочется писать?)

**Comment by Grawl** [comment]
@artem-malko да, именно что просто сахар. Я не особо прогер – больше верстальщик-дизайнер, и не хочется вываливаться из моего сладкого потока Sass + Jade.

**Comment by artem-malko** [comment]
@Grawl на самом деле, coffescript не был приоритетным, если займешься, буду признателен. Fork -> Pull request)

**Comment by Grawl** [comment]
Я только начал знакомиться с Gulp (немного знаком с Grunt), так что PR сейчас был бы более чем разрушителен.
