### ISSUE TITLE
Add symbols workflow for svg

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#160]

**Comment by romanbyte** [comment]
Может быть еще добавить генерацию иконочного шрифта из svg?

**Comment by artem-malko** [comment]
@romanbyte использование иконочного шрифта - это антипаттерн. В TARS встроенной поддержки не предвидится. Возможно будет реализовано плагином для TARS в будущем.

**Comment by artem-malko** [comment]
In 1.6.0
