### ISSUE TITLE
нужны рекомендации по разработке бэкенда

### ISSUE THREAD

**Issue by sosnovskyas** [tars/tars#162]
Очень хороший дистрибутивчик и хотелось бы его использовать при разработке полного стека. как пример хочу писать бэкенда для своего SPA на Node.JS прям в этом же проекте. Есть ли какие-то наработки/бэстпрактиксы/рекомендации где размещать в проекте этот код и как включать в сборку?

**Comment by artem-malko** [comment]
@sosnovskyas на самом деле нету никаких бэстпрактиксов, так как каждый кастомизирует TARS под себя так, как ему удобно. Нужно относится к TARS как к сборщику, то есть его можно внедрять в любое SPA на Nodejs. Стройте свое приложение и кастомизируйте TARS так, как вам удобно.
Есть мысли создать пару плагинов, которые реализуют шаблон для SPA, но это будет реализовано только после внедрения системы плагинов.
Я ответил на ваш вопрос?

**Comment by sosnovskyas** [comment]
да, польнстью, спасибо. а когда ожидается внедрение системы плагинов?

**Comment by artem-malko** [comment]
@sosnovskyas на самом деле, нету никаких bestpractise, так как каждый может кастомизировать TARS под себя. Вам необходимо относится к TARS именно как к сборщику, а не фреймворку для SPA. Иными словами, вы можете использовать TARS для сборки любого SPA на Nodejs.
Создавайте свое приложение так, как привыкли и кастомизируйте, если потребуется, TARS под свои нужды.
Я ответил на ваш вопрос?

**Comment by artem-malko** [comment]
@sosnovskyas вопрос сложный) Думаю что как минимум в конце января 2016. Еще куча задач до этого есть, а времени нет много на разработку(

**Comment by sosnovskyas** [comment]
Спасибо
