### ISSUE TITLE
PostHTML support

### ISSUE THREAD

**Issue by Grawl** [tars/tars#175]
Like PostCSS, PostHTML is a growing technology and a community filling up with plugins to process HTML through AST tree with JS code.

It's already [have plugins](http://maltsev.github.io/posthtml-plugins/)
- for [including](https://github.com/posthtml/posthtml-include) one template into another, 
- [extend](https://github.com/maltsev/posthtml-extend) them on top of each other part,
- read images and [add their sizes](https://github.com/maltsev/posthtml-img-autosize) into `<img>` elements,
- [improve accessibility of tabs](https://github.com/jonathantneal/posthtml-aria-tabs) and [add missing `alt` attributes](https://github.com/ismamz/posthtml-alt-always),
- [minify html](https://github.com/maltsev/htmlnano) in modular way and [inline any assets](https://github.com/jonathantneal/posthtml-inline-assets) you want,
- maintain [BEM classnames](https://github.com/rajdee/posthtml-bem) or [use CSS modules](https://github.com/admdh/posthtml-modular-css),
- and even [use PostCSS](https://github.com/posthtml/posthtml-postcss) on inline styles.

It's highly important to implement this technology right now.

**Comment by artem-malko** [comment]
@Grawl really interesting, I will comeback to research asap. Thank you.

**Comment by Grawl** [comment]
Glad to help you.

**Comment by artem-malko** [comment]
@Grawl great) I'll write you after 1.6.0 release.

**Comment by artem-malko** [comment]
Wait for #150

**Comment by FrontDevs** [comment]
https://youtu.be/Zq12MQSesWc

**Comment by artem-malko** [comment]
@FrontDevs thanks)

**Comment by Grawl** [comment]
Backlog again?

**Comment by artem-malko** [comment]
@Grawl, I do not have enogh time to implement it right now or in the closest version. It does't mean, that this feature won't be implemented.

**Comment by Grawl** [comment]
@artem-malko no problem, I just checked it out

**Comment by artem-malko** [comment]
Not popular(
