### ISSUE TITLE
Boost build with gulp-remember

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#182]
- [ ] Add gulp-remember
- [ ] Update watchers, add unlink handler

More info in https://www.youtube.com/watch?v=Dhrhoe6fFD0&index=6&list=PLDyvV36pndZFLTE13V4qNWTZbeipNhCgQ

**Comment by ilkome** [comment]
gulp-remember

**Comment by artem-malko** [comment]
@ilkome fixed)

**Comment by artem-malko** [comment]
Не реализуемо в текущем варианте сборки(
