### ISSUE TITLE
Gulp plugins options

### ISSUE THREAD

**Issue by FrontDevs** [tars/tars#194]
Сделать возможность редактирования опций gulp плагинов, без переопределения системных тасков. На примере  /tars/user-tasks/html/helpers/modify-options.js, возможно даже в этом файле всё уместится.

**Comment by artem-malko** [comment]
@FrontDevs прости, очень хочется уже 1.7.0 выпустить)

**Comment by artem-malko** [comment]
In version 1.8.0
