### ISSUE TITLE
error helpers using SVG icon

### ISSUE THREAD

**Issue by FrontDevs** [tars/tars#208]
```
{{#repeat 16}}
    {{Icon iconName='calendar' className='svg-icon'}}
{{/repeat}}
```
This code gives an error "Can not read property '__iconsData' of undefined"

**Comment by FrontDevs** [comment]
Thanks. Good job :thumbsup:

**Comment by LitvinenkoEvgeny** [comment]
Здравствуйте, пытаюсь отрендерить иконку edit.svg находящуюся по пути: 
markup/static/img/svg/edit.svg
`
   != pugHelpers.Icon.call(locals, {iconName: 'edit'})
`
Cannot read property 'edit' of undefined
если в tars/tasks/html/helpers/pug-helpers.js
на 23 строке прописать         `console.log(this.__iconsData, iconName);`
то выдаст `undefined 'edit'
`
если посмотреть на this, то там действительно не будет __iconsData
`
{ _template: { big: { title: 'Hello world', age: 10, button: false } },
  head: { defaults: { title: 'default title', useSocialMetaTags: true } },
  header: { defaults: { listLeft: [Object], listRight: [Object] } },
  __pages: [ { name: 'index', href: 'index.html' } ],
  pugHelpers: 
   { Icon: [Function: Icon],
     exampleHelper: [Function: exampleHelper] } }
`
