### ISSUE TITLE
Добавить возможность работы с bower

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#21]

**Comment by TrySound** [comment]
Я использую [main-bower-files](https://github.com/ck86/main-bower-files). Потрясающая вещь.

**Comment by artem-malko** [comment]
Сложность в том, чтобы потом разложить файлы по нужным местам.

**Comment by TrySound** [comment]
Я обычно просто фильтрую и конкатенирую их.

**Comment by artem-malko** [comment]
@TrySound просто в конкатенации важен порядок. Например с js порядок такой:
* файлы фреймворка
* библиотек
* плагинов
и т.д.

Так вот в bower может быть jquery — библиотека и ember — фреймворк. По умолчанию bower не может сказать, какого типа сущностью является пакет. Были мысли запускать установку пакетов из bower с различными ключами. Например, хочешь, чтобы у тебя пакет попал в папку framework, пишешь bower i ember --framework. Как идея?

**Comment by TrySound** [comment]
А зачем вообще в папку перемещать, сразу из bower и в concat. А для порядка существуют зависимости. main-bower-files ими отлично оперирует. А если зависимости не указаны, это уже проблема пакета.

**Comment by artem-malko** [comment]
@TrySound не, ты меня видимо не так понял. Напрямую в concat бросать все что угодно нельзя. Я привел пример, когда порядок сборки важен. Могу с CSS пример привести. Например, мы скачиваем bootstrap. Нам важно, чтобы стили bootstrap'а были до всех остальных стилей в сборке.
Или ты предлагаешь оставить это на усмотрение пользователя, куда что положить?

**Comment by TrySound** [comment]
Ну да, в этом случае верно. Можно сделать пользовательскую сортировку по названиям пакетов. В main-bower-files это пока не реализовано, но вы можете вставить свой фильтр. В моей практике это ни разу не понадобилось: Бутстрап+библиотеки (в любом порядке)->мои стили со всем справляется и ничего не конфликтует, а для тех же бутстраповских тем есть зависимости.

**Comment by TrySound** [comment]
Если грамотно писать разметку, то можно и в любом порядке. Главное сначала определить вендоры, а потом свои стили.

**Comment by artem-malko** [comment]
@TrySound  а вот про фильтры я не знал, это может значительно облегчить решение задачи. Спасибо)

**Comment by TrySound** [comment]
Модуль очень мощный. Когда попросил автора вставить глобы и сделать фильтр первым аргументом, стало еще и красиво.

**Comment by TrySound** [comment]
При желании пользователь может в bower.json в поле overrides.dependencies прописать все зависимости, тогда и фильтр не нужно будет использовать. Может и костыль, но при необходимости случаев сработает.

**Comment by rtxrulez** [comment]
@TrySound Есть еще плагин для работы с bower https://www.npmjs.com/package/gulp-bower-assets

**Comment by TrySound** [comment]
@rtxrulez У него своя идеалогия. main-bower-files более универсален и в большинстве случаев ничего ненужно дописывать.

**Comment by rtxrulez** [comment]
@TrySound но как же зависимости в js? И к тому же удобно подключить less файл бутстрапа и переопределять переменные. Например если какой то плагин зависящий от jquery подключится до jquery? Ошибка же будет. Мне кажется гораздо надежнее вручную прописывать каждую библиотеку.

**Comment by TrySound** [comment]
@rtxrulez Для этого в bower.json можно писать overrides для непроработанных манифестов.

**Comment by artem-malko** [comment]
@eddyLazar призываю тебя помочь с этим)

**Comment by artem-malko** [comment]
https://github.com/taptapship/wiredep

**Comment by TrySound** [comment]
@artem-malko Bower отстой ))

**Comment by artem-malko** [comment]
@TrySound вот это поворот) npm?)

**Comment by TrySound** [comment]
@artem-malko Да. В нем теперь нет смысла. npm3 дедьюпит зависимости. browserify и прочие работают лучше именно с npm. А конкатенация в сложных проектах плохо масштабируется. Так что смысла в bower больше нет. Хотя опыт занятный был )

**Comment by artem-malko** [comment]
@TrySound Держишь ишью, держишь) А потом просто берешь и закрываешь)

**Comment by TrySound** [comment]
@artem-malko Вообще-то твоя. А я бесправный ))

**Comment by artem-malko** [comment]
@TrySound ну я про себя)

**Comment by TrySound** [comment]
@artem-malko Закрывай. bower плохая практика. Мы не должны ее поощрять.

**Comment by artem-malko** [comment]
Будет использоваться npm!

**Comment by TrySound** [comment]
:+1:

**Comment by artem-malko** [comment]
@TrySound  Ничоси реакция у тебя)

**Comment by TrySound** [comment]
@artem-malko Подписка на issue и уведомления почты на телефоне :)

**Comment by Grawl** [comment]
А чем будем Sass, допустим, из NPM доставать? О JS все заботятся, а на остальное забивают, а зря.

Я сейчас делаю так: у меня есть в папке `tasks/injections` шаблоны для наполнения зависимостями – `_injections.sass`, например. Этот файл копируется в `app/styles/partials/` и наполняется, превращаясь вот во что:

```sass
// bower:scss
@import "../../bower_components/foundation-sites/scss/foundation.scss"
// endinject
//
// inject:scss
@import modules/_control.scss
// endinject
//
// bower:sass
// endinject
//
// inject:sass
@import modules/_flying.sass
@import modules/_globals.sass
@import modules/backgroundStretch.sass
@import modules/backgrounds.sass
…
// endinject
//
```

И уже этот файл я в нужное место `@import`.

Так же делаю и с зависимостями Jade.

Не нашёл пока ничего лучше, чем `gulp-main-bower-files` для этого.

**Comment by artem-malko** [comment]
@Grawl слишком много специфики получилось. Я уже давно думал над этим всем и ничего универсального не получается сделать. Импорт из node_modules возможен

**Comment by Grawl** [comment]
Специфики? Ну да, в каждом проекте что-то своё. То Bootstrap из CSS, то Foundation из Sass, то на React какая-нибудь фигня. Но `main-bower-files` решает задачу сбора зависимостей идеально – можно хоть по прямой ссылке файл из CodePen поставить (у меня есть [один такой](http://codepen.io/Grawl/pen/iqaBF)), назначить ему зависимость в `bower.json/overrides` и он встанет на своё место.

**Comment by artem-malko** [comment]
@Grawl не решает в рамках TARS, так как зависимость может быть библиотекой, фреймворком или плагином. И это нельзя определить автоматом, только человек может принять решение.

**Comment by Grawl** [comment]
Ну вот и учесть как-то эти потребности. Например, автоматически собирать только `bundledDependencies`.

**Comment by artem-malko** [comment]
@Grawl не совсем понял, что имеется в виду.

**Comment by Grawl** [comment]
У NPM есть такой тип зависимости – `bundledDependencies`. Можно их как раз и использовать для автоматического сбора jQuery-библиотек, JS/CSS-framework'ов и так далее. А проще не выдумывать велосипед и воткнуть в это место готовый инструмент, многократно упомянутый выше и идеально справляющийся со своими задачами.

**Comment by artem-malko** [comment]
Фреймворк и библиотеки должны лежать в разных директориях. При этом каждый сам принимает решение о том, что фреймворк, а что библиотека. От сюда следует, что это не автоматизировать.

**Comment by Grawl** [comment]
То есть установка frontend-зависимости в проект исключительно вручную?

**Comment by rtxrulez** [comment]
@artem-malko может есть какая то папка или рекомендации куда лучше ставить bower пакеты и в какой файл потом импортировать css или js ? Что бы структура была у каждого человека использующего tars примерно одинакова.

**Comment by artem-malko** [comment]
@rtxrulez частично в доке описал (для css https://github.com/tars/tars/blob/master/docs/ru/css-processing.md). Про JS тут уже как удобнее.
Вообще, пока желательно руками раскидывать файлы по папкам в в папке static
