### ISSUE TITLE
How to add your own svg template?

### ISSUE THREAD

**Issue by romamilkovic** [tars/tars#217]
I use the SVG symbols workflow and got a questions about how can I change the default SVG template? I found a plugin that generates SVG symbols - gulp-svg-symbols. 

> templates
> 
> Specify your own templates by providing an absolute path:
> 
> templates: [
>   path.join(__dirname, 'path/to/my/template.stylus'),
>   path.join(__dirname, 'path/to/another/template.html'),
>   // You can still access to default templates by providing:
>   'default-svg',
>   'default-css',
>   'default-demo'
> ]

In **make-symbol-sprite.js** I added

`                        templates: [
                            tars.root + '/tasks/images/helpers/symbols-svg-template.svg',
                            'default-svg',
                            tars.root + '/tasks/images/helpers/symbols-data-template.js'
                        ],`

But nothing changes. 

What actually should I do? Thanks.

**Comment by artem-malko** [comment]
First of all, you should to create user-task to override system make-symbol-sprite task. More info you can get from [docs](https://github.com/tars/tars/blob/master/docs/en/tasks-and-watchers.md#tasks-and-watchers).
After that, you have to create your own template fro sprite and store it somewhere in project.
And the last step: you need to specify path to your own template in templates:
```js
templates: [
    'default-svg',
    'path to your template'
]
```

Please, let me know, was it useful for you? Thank you.

**Comment by romamilkovic** [comment]
@artem-malko Yes, the problem is solved! Thanks.

**Comment by artem-malko** [comment]
@romamilkovic great.
