### ISSUE TITLE
Переход в папку с билдом по клику на версии билда в консоли

### ISSUE THREAD

**Issue by Seminioni** [tars/tars#220]
1. В строке, где тарс пишет "Build version is...", возможно ли по комбинации ctrl + пкм сделать переход к этой/в эту папку со сбилженным проектом?
![bnyc7](https://cloud.githubusercontent.com/assets/16149737/14731453/437e5836-0883-11e6-9cb3-2a9ba3495567.png)

2. Например, как при запуске в dev-режиме с туннелированием и live reload 
![np14w](https://cloud.githubusercontent.com/assets/16149737/14731469/62d4f58c-0883-11e6-9907-2fa3b2f4f863.png)

**Comment by artem-malko** [comment]
Не реализуемо. Пока положу в backlog
