### ISSUE TITLE
Невозможно открыть сбилженный архив в OS X

### ISSUE THREAD

**Issue by Seminioni** [tars/tars#221]
Цитирую "чтобы я выставлял права доступа для создаваемого архива. От рута его можно будет разархивировать"
![photo_2016-04-22_17-03-05](https://cloud.githubusercontent.com/assets/16149737/14737526/1f48f382-08af-11e6-9a30-f782f04d47c2.jpg)

**Comment by artem-malko** [comment]
К сожалению, не смогу такое пофиксить( В доке указано, что от рута не стоит запускать TARS.
