### ISSUE TITLE
Вернуть возможность Jade следить за файлами с "_*.jade"

### ISSUE THREAD

**Issue by Laxiston** [tars/tars#222]
До последнего фикса было очень удобно создавать модули и страницы-шаблоны, имена которых начинались с "_". Станицы-шаблоны использовались в других основных страницах через "extends"  (встраиваемый шаблон) и не нужно было копировать кучу кода. Так же и с модулями, по крайней мере я использовал подобное для глобальных каких-то переменных и функций. Сейчас же этого нет. Очень не удобно теперь.

**Comment by artem-malko** [comment]
@Laxiston а чего закрыл-то?)

**Comment by Laxiston** [comment]
@artem-malko разобрался хД

**Comment by artem-malko** [comment]
@Laxiston Ты себе сам поправил?)

**Comment by Laxiston** [comment]
@artem-malko слегка затупил)

**Comment by artem-malko** [comment]
Так ты расскажи, что в итоге? Что понял? Стоит ли что-то менять?
