### ISSUE TITLE
JS:concat-processing gigant time required

### ISSUE THREAD

**Issue by elektrobober** [tars/tars#228]
Hi, guys. First of all I really want to say thank you for great tool. I'm happy to use it, but now I have some unpleasant issue. js:concat-processing required about 4-5 min.
Mb you have some solution or any ideas about the reason of this trouble. 

Please find below my tars-config file
```js
module.exports = {
    "autoprefixerConfig": [
        "> 1%",
        "last 2 versions",
        "Firefox ESR",
        "android 4"
    ],
    "postcss": [],
    "svg": {
        "active": true,
        "workflow": "sprite",
        "symbolsConfig": {
            "loadingType": "inject",
            "usePolyfillForExternalSymbols": true,
            "pathToExternalSymbolsFile": ""
        }
    },
    "js": {
        "workflow": "concat",
        "bundler": "webpack",
        "lint": true,
        "useBabel": false,
        "removeConsoleLog": true,
        "webpack": {
            "useHMR": false
        },
        "jsPathsToConcatBeforeModulesJs": [],
        "lintJsCodeBeforeModules": false,
        "jsPathsToConcatAfterModulesJs": [],
        "lintJsCodeAfterModules": false
    },
    "sourcemaps": {
        "js": {
            "active": true,
            "inline": true
        },
        "css": {
            "active": true,
            "inline": true
        }
    },
    "notifyConfig": {
        "useNotify": true,
        "title": "TARS notification",
        "sounds": {},
        "taskFinishedText": "Task finished at: "
    },
    "browserSyncConfig": {
        "baseDir": "./dev",
        "port": 3004,
        "open": true,
        "browser": "default",
        "startUrl": "/index.html",
        "useNotifyInBrowser": true,
        "injectChanges": false
    },
    "minifyHtml": false,
    "staticPrefix": "static/",
    "buildPath": "./builds/",
    "useBuildVersioning": true,
    "useArchiver": true,
    "ulimit": 4096,
    "templater": "jade",
    "cssPreprocessor": "scss",
    "useImagesForDisplayWithDpi": [
        96,
        192,
        288,
        384
    ],
    "fs": {
        "staticFolderName": "static",
        "imagesFolderName": "img"
    },
    "useBabel": false
};
```

Thank you in advance

**Comment by artem-malko** [comment]
@elektrobober can you add log from your terminal with info about js-compilation?

**Comment by elektrobober** [comment]
Hi, Artem and thank you for real quick answer.

For real it isn't issue with quantity of js-files because same markup folder wich moving at tars folder on my Mac doesn't provide this issue.

Please find the cmd screenshot below
![image](https://cloud.githubusercontent.com/assets/10926784/15173003/100d51da-1762-11e6-98f9-6c38a5197011.png)

**Comment by artem-malko** [comment]
@elektrobober it is not a problem with your JS, 4 minutes it is a time to compile HTML. First compilation will be quite long, but recompilation will be really fast. So, It is not a problem, it is just life)
Please, try to save js-file and then jade-file. You will see, that  recompilation is really fast.

**Comment by elektrobober** [comment]
@artem-malko Ok, thank you for your answer,mb it's realy just life, but my righthand colleague make the same operation realy quick - just few seconds. One thing make me happe - lefthand colleague has to spend 1 min more than I have to. And the last but not least - all team members have same PC/Node/npm/tars configuration - just magic. Never mind =)

**Comment by artem-malko** [comment]
@elektrobober your colleagues just recompile html and js, but the first compilation is long on their PC too. Is it possible to send me archive with your project for testing?

**Comment by artem-malko** [comment]
@elektrobober is where any news?)

**Comment by elektrobober** [comment]
@artem-malko hi, Artem, we have to approve sharing this project with our Rm. Be sure, I will contact you asap.

**Comment by artem-malko** [comment]
@elektrobober ok, I'll be waiting for it.

**Comment by artem-malko** [comment]
@elektrobober up!)
