### ISSUE TITLE
Grammar fixes

### ISSUE THREAD

**Issue by Seminioni** [tars/tars#236]
- [x] Раз

![1](http://i.imgur.com/Uhii2HC.png)

- [x] Два 

![2](http://i.imgur.com/4KoGWYZ.png)

**Comment by Seminioni** [comment]
@artem-malko стыдно признаться, но я не умею в реквесты. Сделал на автомате ишшью, потом перечитал и понял что тупанул. Ну а дальше "ааа я же пулл реквесты никогда не делал!"

**Comment by artem-malko** [comment]
@Seminioni эх(

**Comment by jt3k** [comment]
@Seminioni если ошибка в ридмишечке, то можно прям на гитхабе подправить, затем написать текст коммита, и репозетарий сам форкнится и появится у тебя. А затем ты можешь нажать на зелёную кнопку "Pull request" и написав комментарий отправить этот пуллреквест в апстрим )
и тогда он появится здесь https://github.com/tars/tars/pulls

**Comment by artem-malko** [comment]
@Seminioni насколько я понял, править мне придется самому?)

**Comment by Seminioni** [comment]
@artem-malko не, сам сделаю

**Comment by Seminioni** [comment]
@jt3k спасибо за инструкцию! Теперь буду править и отправлять пулл реквест :+1:

**Comment by artem-malko** [comment]
@Seminioni первое не пофиксил) Оно в tars-cli находится

**Comment by artem-malko** [comment]
In 1.8.1
