### ISSUE TITLE
Grammar in English readme and docs

### ISSUE THREAD

**Issue by icehaunter** [tars/tars#237]
A lot of problems with English translation of documentation. Not only typos, but also grammar mistakes. They exist in most doc files, unfortunately. I am working on a pull request to fix those.

Множество проблем с английской документацией. Не только опечатки, но и грамматические ошибки. Ошибки присутствуют почти во всех файлах документации. Я уже работаю над ними - заодно включу поправки в опечатках в русских файлах, если замечу.

**Comment by artem-malko** [comment]
@icehaunter thank you a lot! I do not have much time to fix it)

**Comment by artem-malko** [comment]
@icehaunter thank you again! I saw how many fixes you have implemented.

**Comment by artem-malko** [comment]
@icehaunter hi)
Can I merge your fixes?

**Comment by artem-malko** [comment]
In 1.9.0
