### ISSUE TITLE
Изменить структуру папок в builds и dev

### ISSUE THREAD

**Issue by VaLeXaR** [tars/tars#240]
Можна ли изменить структуру папок при компиляции на следующюю.
```
├── builds/
    ├── css/
    ├── js/
    ├── img/
    ├──index.html
```
Тоесть просто убрать из структуры папку static.

**Comment by artem-malko** [comment]
@VaLeXaR можно. Вы можете переопределить таски, которые занимаются генерацией файлов в папку static, чтобы они это делали в другое место. Проще пока способа нет. Чем плоха текущая реализация?

**Comment by VaLeXaR** [comment]
Думаю использовать TARS на уже готовом шаблоне для сайта.
Мне нужно компилировать только файлы стилей, картинки и шрифты. Структура следующая.
```
├── template_name/
    ├── css/
    ├── js/
    ├── img/
    ├── fonts/
    ├── index.php
    ├── favicon.ico
    ├── .htaccess
```
Например можно было бы в папке шаблона сайта создать папку tars, там инициализировать сам tars.
```
├── template_name/
    ├── css/
    ├── js/
    ├── img/
    ├── fonts/
    ├── tars/
        ├── все файлы TARS
    ├── index.php
    ├── favicon.ico
    ├── .htaccess
```
В IDE исключаю из автоматической заливки на сервер папку tars.
Тогда я смогу работать только в папке tars, а файлы, компилировались бы в нужной структуре и измененные заливались на сервер.
Сейчас я могу перенести папку builds на нужный уровень и назвать так, как мне нужно. Но вот папка static очень мешает.

**Comment by VaLeXaR** [comment]
По сути даже это не принципиально. Главное чтобы стили, шрифты, картинки собирались в нужной папке и при перекоппиляции очишались би только эти папки, а не полностью родительская.

**Comment by VaLeXaR** [comment]
Решил вопрос.
Указал точки и папка static исчезла из путей.

**Comment by artem-malko** [comment]
@VaLeXaR точки в тасках вместо staticFoldeName?

**Comment by VaLeXaR** [comment]
Нет. В конфиге tars.

**Comment by artem-malko** [comment]
@VaLeXaR ну круто, если делает, то, что нужно)

**Comment by AdreeUA** [comment]
@VaLeXaR У меня почему-то не получаеться сделать как Вы говорите. Где именно точки вы ставили? Если ставить точки в `staticFolderName` тогда сборка не может собрать спрайты и выдает ошибку, а если оставить ее как есть то папка static остается.

**Comment by VaLeXaR** [comment]
@AdreeUA инициализируйте TARS, настройте, перенесите содержимое папок markup/static/ на уровень вверх, отредактируйте переменные tars-config.js:
staticFolderName: '.',
staticPrefix: './'
Возможно прийдется подправить некоторые таски.
