### ISSUE TITLE
TARS не инициализируется через собственный архив без user-package.json внутри

### ISSUE THREAD

**Issue by Seminioni** [tars/tars#243]
Падает вот с такой ошибкой
![](http://i.imgur.com/xczO78G.png)
Содержимое репозитория
![](http://i.imgur.com/UdF3EVp.png)

**Comment by jt3k** [comment]
полагаю проблема здесь: 
https://github.com/tars/tars/blob/master/tars/helpers/install-additional-deps.js#L10
@Seminioni не мог бы ты проверить на винде, заменив слеш на падающий налево "\"  ?

**Comment by Seminioni** [comment]
@jt3k неа, не помогло

**Comment by artem-malko** [comment]
@jt3k проблема в том, что цикл потом запускать не надо, если ошибки были.

**Comment by FrontDevs** [comment]
@artem-malko Этот баг я решил простым добавлением этого файла к себе в архив.

**Comment by artem-malko** [comment]
@FrontDevs понятно дело, но по-хорошему, это не должно влиять

**Comment by artem-malko** [comment]
In 1.8.1
