### ISSUE TITLE
Не правильные пути для стилей IE

### ISSUE THREAD

**Issue by meroPush** [tars/tars#244]
Баг с путями при "ручной" сборке стилей для IE. В static/less/entry/ie/main_ie8.less|main_ie9.less пути нужно поднять на одну директорию

**Comment by meroPush** [comment]
Еще ошибка с путями в файле "static/less/entry/built-in-partials/_service-ie8.less" строка 12
Подключается файл "sprite-ie.less", но он не существует, есть файл "sprite-png-ie.less", скорее всего опечатка.

**Comment by artem-malko** [comment]
In 1.8.1
