### ISSUE TITLE
Autoprefixer для сборки IE9

### ISSUE THREAD

**Issue by meroPush** [tars/tars#246]
Было бы не плохо прогонять стили для IE9 через autoprefixer, с настройками autoprefixer только для ie. На данный момент стили для ie вообще не обрабатываются autoprefixer и получается что все "плюшки" css3 для каждого элемента придется дописывать вручную с приставкой -ms-

**Comment by artem-malko** [comment]
@meroPush дык уже прогоняем) https://github.com/tars/tars/blob/master/tars/tasks/css/helpers/manual-compile-css-task-template.js#L45

**Comment by meroPush** [comment]
@artem-malko прогоняем, но только для ie8
`postProcessors.push(
    autoprefixer({browsers: ['ie 8']})
);`
я же имел ввиду сборку и для ie9

**Comment by meroPush** [comment]
решил проблему через переопределение тасков, но хотелось бы видеть этот функционал из коробки.

**Comment by artem-malko** [comment]
@meroPush забыл про IE9( Сделаю)

**Comment by artem-malko** [comment]
In 1.8.1
