### ISSUE TITLE
Stylelint support

### ISSUE THREAD

**Issue by ai** [tars/tars#248]
If we have ESLint to lint JS, we should lint CSS too. There are three popular way to lint CSS: Stylelint, scss-lint and csslint. I think Stylelint is a best because:
- Modular design like ESLint.
- [Facebook](https://code.facebook.com/posts/879890885467584), [GitHub](https://github.com/stylelint/stylelint/issues/1402#issuecomment-225282315) and [US gov 18F](https://github.com/18F/stylelint-rules) already uses it. In that links you can find their practices.
- Stylelint support SCSS, Less, CSS and SugarSS inputs. If somebody will add Sass support to PostCSS, Stylelint will support it too.
- Stylelint has Stylefmt to fix code according Stylelint config. It is like `eslint --fix`.
- You [can display](https://github.com/postcss/postcss-browser-reporter) Stylelint uses directly in browser in development mode.

Also they have plugins for Atom, Sublime to see issues in editor.

**Comment by artem-malko** [comment]
@ai thanks for suggestion. I think, we should to implement this feature in 1.9.0
