### ISSUE TITLE
Баг scss при билде проекта

### ISSUE THREAD

**Issue by VadimMikh** [tars/tars#250]
Добрый день, очень прошу помочь. Постоянно при билде выбрасывает такую 

http://prntscr.com/bj2jxz       ошибку.

Tars-CLI version: "1.8.4"
Tars-CLI version in project: "1.8.1"
Gulp: "3.9.1"
npm: "3.9.5"
Nodejs: "6.2.2"

**Comment by jt3k** [comment]
не видно начала этой ошибки.

**Comment by VadimMikh** [comment]
Тут весть процесс http://prntscr.com/bj48ho

**Comment by jt3k** [comment]
а те команды что тёмно-красными буквами написаны  выполняли ?

**Comment by VadimMikh** [comment]
Конечно ) 
Tars-CLI version: "1.8.4"
Tars-CLI version in project: "1.8.1" 

на более новые версии не обновляется

**Comment by jt3k** [comment]
а какие способы обновления Вы обновляетесь ? 
Какие команды писали ?

Напишите их сюда, возможно кто-то кто сталкивался смогут помочь

**Comment by VadimMikh** [comment]
tars update - глобально обновлял TASR CLI
tars update-project - локально внутри проекта

**Comment by VadimMikh** [comment]
Обновил TARS из корня командой 

npm i -g tars-cli

помогло

**Comment by jt3k** [comment]
закрывай
