### ISSUE TITLE
Не уникальный id при собирании svg в один файл

### ISSUE THREAD

**Issue by kendrive** [tars/tars#251]
При компиляции svg и его inject, к каждому path устанавливается не уникальный id. Из-за этого не возможно поставить несколько svg с градиентом linearGradient на одну страницу.

`<defs>
      <path id="a" d="M30.953 0L17 13.953 3.047 0H0l17 17L34 0z"/>
      <path id="a" d="M27.512 27.622L17.205 17.47l.484-.493 9.82 9.678 9.82-9.678.48.492z"/>
</defs>` 

`<symbol id="arrow-bottom" viewBox="0 0 34 17">
      <g fill="none" fill-rule="evenodd"><mask id="c" fill="#fff"><use xlink:href="#a"/></mask><path fill="url(#b)" d="M-8.5 8.5L17-17 42.5 8.5 17 34" mask="url(#c)"/><g transform="translate(10)"><mask id="f" fill="#fff"><use xlink:href="#d"/></mask><path fill="url(#e)" d="M-3.207 3.402L7-6.805 17.208 3.402 7 13.61" mask="url(#f)"/></g></g>
    </symbol>
    <symbol id="logo-small" viewBox="0 0 56 56">
      <clipPath id="c"><use xlink:href="#a" overflow="visible"/>`

**Comment by artem-malko** [comment]
@kendrive вообще такого быть не должно. Уникальность должна быть на уровне символа только. В целом, нужно поиграться с настройками SVGO https://github.com/tars/tars/blob/master/tars/tasks/images/minify-svg.js#L32

**Comment by kendrive** [comment]
Да, уникальность на уровне символа сохраняется, но defs один для всего "спрайта". И url ищет id  именно в defs. Находит первый и применяет его.

Вариантом решения, была бы установка префикса к id в виде имени файла/класса.

Настройка SVGO
`cleanupIDs: {
   prefix: namefile,
   remove: false,
   minify: true,
 }`
ни к чему не привела, возможно у меня руки кривые.

**Comment by artem-malko** [comment]
@kendrive попробуйте убрать лишнюю запятую в конце. Откуда берете namefile?

**Comment by artem-malko** [comment]
@kendrive есть новости?)

**Comment by artem-malko** [comment]
@kendrive открою, если будут новости.

**Comment by martos28** [comment]
та же проблема, решить сложно хм, дублей очень много в defs [http://ipic.su/img/img7/fs/kiss_713kb.1508016485.jpg](url)
