### ISSUE TITLE
svg problems

### ISSUE THREAD

**Issue by merss19** [tars/tars#252]
Криво собираются svg
В некоторых местах не до конца отрисовывается, где-то лишняя рамка появляеся
http://joxi.ru/p278JVMI0XNQVA

До сборки svg каждый файл отображается корректно.
В насктройках стоит 'sprite'.
В чем может быть проблема?

**Comment by artem-malko** [comment]
Проблема только в ваших SVG. Должен быть viewBox с целыми значениями и с двумя нулями в начале. SVG должны содержать как можно меньше лишних элементов.

**Comment by artem-malko** [comment]
@merss19 проверьте, что ваши SVG-файлы соответствуют этим параметрам и будем закрывать ишью.

**Comment by merss19** [comment]
да, спасибо, скорее всего проблема в моих svg.
