### ISSUE TITLE
Сделать поддержку IE 8-9 опциональной. 

### ISSUE THREAD

**Issue by LostSenSS** [tars/tars#253]
Привет!
Не всем нужно поддерживать эти браузеры. Было бы неплохо при инициализации TARS спрашивать, нужна ли поддержка старых IE. И если нет, то полностью выпиливать весь функционал, относящийся к ним.

**Comment by artem-malko** [comment]
@LostSenSS спасибо за issue. 
Такой вопрос, а чем мешают таски для работы с IE? Они же очень четко отделены от всего остального?

**Comment by LostSenSS** [comment]
@artem-malko Просто что б в структуре не было лишнего, например main_ie8.scss, sprite-ie.scss и html5shiv. Приятно же :)

**Comment by artem-malko** [comment]
@LostSenSS смотри, какая может быть ситуация: ты инитишь проект, говоришь, что поддержка тебе не нужна и TARS выпиливает все лишнее. А потом твой заказчик говорит, что вот IE9 можно было бы и поддержать. И это может быть в любой момент. Плюс люди не любят необратимости)
Эти файлы все лежат максимально отдельно, чтобы не захламлять общую картину. В конечный бандл не в коем случае не попадают.
Поэтому, данная фича будет выполнена в несколько ином виде: в 2.0 вообще не будет поддержки IE8, IE9)

**Comment by LostSenSS** [comment]
@artem-malko Ок. Здорово, что 2.0 уже в планах )
