### ISSUE TITLE
Некорректный вывод заголовка TARS в консоли WebStorm

### ISSUE THREAD

**Issue by LostSenSS** [tars/tars#254]
Вот так выглядит надпись TARS в консоли Шторма. В стандартном терминале всё ок. 
Может лучше заменить эти символы на обычный текст?

![image](https://cloud.githubusercontent.com/assets/1523204/16580433/1e6a5978-42ad-11e6-8687-99d4763da9bd.png)

**Comment by artem-malko** [comment]
@LostSenSS на Windows это итак обычный текст. К сожалению нет детектора, доступны символы или нет, поэтому нет возможности это исправить автоматически.
Подскажите, какая ОС используется?

**Comment by LostSenSS** [comment]
@artem-malko OSX 10.11.5

**Comment by artem-malko** [comment]
@LostSenSS вот это поворот. А какая версия webstorm?

**Comment by LostSenSS** [comment]
@artem-malko вообще на самом деле не WebStorm, а PyCharm, версия 2016.1.4. 
Решил не уточнять изначально, т.к. это практически одно и то же.

**Comment by artem-malko** [comment]
@LostSenSS щерт, на OS X не хотелось бы от красивых букв избавляться( Может фиг с ним, что в PyCharm так?

**Comment by LostSenSS** [comment]
@artem-malko Ну это не мне решать ) Но мне кажется, что весьма значительный процент разработчиков используют эти IDE и многие из них работают в встроенном терминале, т.к. в нём удобно выполнять действия связанные с текущим проектом.

**Comment by artem-malko** [comment]
@LostSenSS дык я тоже в webstorm тыкаюсь и у меня все норм) В общем, положу ишью в backlog. Если будет много где еще повторяться — будем убирать красивости(

**Comment by TryHardNinja** [comment]
У меня тоже самое. RubyMine , macOS 10.12
