### ISSUE TITLE
Использование NODE_ENV

### ISSUE THREAD

**Issue by LostSenSS** [tars/tars#255]
В доках сказано: 

> По умолчанию у вас есть возможность использовать переменную окружения NODE_ENV в коде

Но на самом деле она всегда undefined. Если не ошибаюсь даже там, где она используется в самом TARS, например в /tars/tasks/main/dev.js. 
Было бы очень удобно, если бы при вызове tars dev / tars build в нее заносилось соответствующее значение. 
И было б совсем супер, если б был доступ к ней прямо из шаблонов, что б можно было делать подобное: 
```jade
if (NODE_ENV == 'dev')
  script(src='my-only-dev-script.js')
```

**Comment by artem-malko** [comment]
@LostSenSS в данном случае не хотелось залезать в то, что передается в эту переменную, чтобы пользователь мог сам настроить ее так, как удобно. Если и будет какая-то переменная использоваться — то скорее всего что-то типа TARS_ENV, а в NODE_ENV уже что пользователь за хочет, то и положит.

**Comment by LostSenSS** [comment]
@artem-malko да, конечно. Главное, что б она была автоматической и к ней был доступ из скриптов/шаблонов.

**Comment by artem-malko** [comment]
@LostSenSS доступ есть всегда, не зависимо от сборщика) Это же переменная, которая расшарена на весь процесс) Ишью закрываем?

**Comment by LostSenSS** [comment]
@artem-malko Не совсем понял. Что сейчас можно сделать, что б в TARS_ENV было значение dev/build в зависимости от того, в каком режиме запускается TARS? И как получить к этому доступ из шаблонов?
Прошу прощения, если вопрос неуместен/глуп.

**Comment by artem-malko** [comment]
@LostSenSS этой переменной пока не существует. Ты можешь ее сам задать, при запуске таска. 
```bash
TARS_ENV='dev' tars dev
```
Чтобы в коде модулей это было доступно — необходимо настроить webpack.

**Comment by LostSenSS** [comment]
@artem-malko Понял. Мне кажется было бы здорово, если б это было встроенной фичей. Каждый раз прописывать переменную вручную не очень удобно. 
Еще не совсем понятно, как передать эту переменную в шаблоны. Webpack же тут ни при чем? Он может передать только в скрипты. 
Нашел способ, но наверняка не оптимальный: в pages-and-data-files-processing.js в конце дописал 
``` javascript
this.push(new File({
    path: '.',
    contents: new Buffer(`TARS_ENV: '${process.env.TARS_ENV}'`)
}))
```
Так работает. Но эту задачу, как я понял, нельзя даже переопределить в user-task. Т.е. при обновлении TARS это всё слетит.

**Comment by artem-malko** [comment]
@LostSenSS да, слетит. Значит в итоге что сделаем, TARS_ENV переменную, которая будет хранить объект с инфой о текущей сборке. Норм идея?

**Comment by LostSenSS** [comment]
@artem-malko Да. С передачей в шаблоны. Было бы здорово.

**Comment by jt3k** [comment]
я может не в тему но редко но метко встречается кейсы типа:

- нужно собрать без сжатия но для окружения production
- нужно собрать со сжатием но для окружения dev

Это когда надо отдебажить в тестерской среде на реальном https

**Comment by artem-malko** [comment]
@jt3k это отдельная задача. Предлагаю ее тебе отдельно описать тут: https://github.com/tars/tars/projects/2

**Comment by artem-malko** [comment]
In 1.9.0
