### ISSUE TITLE
Ошибка при инциализации с Jade шаблонизатором.

### ISSUE THREAD

**Issue by m1skam** [tars/tars#256]
При инициализации проекта с шаблонизатором Jade, в компонентах схема по умолчанию default_component_scheme.json в которой разметка для __componentName__.jade - представлена в обычном html синтаксисе, что приведет к ошибке.

Сейчас:
```
"files": [
        {
            "name": "__componentName__.__templateExtension__",
            "content": "<div class=\"__componentName__\"></div>"
        }, {
            "name": "__componentName__.__cssExtension__",
            "content": ".__componentName__ {}"
        }, {
            "name": "__componentName__.js",
            "content": ""
        }
    ]
```
Желательно:
```
"files": [
    {
      "name": "__componentName__.__templateExtension__",
      "content": "mixin __componentName__(data)\n  .__componentName__"
    }, {
      "name": "__componentName__.__cssExtension__",
      "content": ".__componentName__ {}"
    }, {
      "name": "__componentName__.js",
      "content": ""
    }
  ]
```

**Comment by FrontDevs** [comment]
@m1skam В чём проблема переопределить, как тебе нужно?

**Comment by m1skam** [comment]
@FrontDevs Не совсем понял вопрос.
Лично у меня все ок, я себе уже поправил как мне удобней :)
Я написал, что из коробки пример для шаблонизатора Jade некорректен и вызовет ошибку при сборке.

**Comment by artem-malko** [comment]
@FrontDevs, @m1skam прав. Сделаю в ближайшей версии.

**Comment by artem-malko** [comment]
В мастере в 1.8.2
