### ISSUE TITLE
Слежка за некомпилируемыми (_name.jade) шаблонами

### ISSUE THREAD

**Issue by LostSenSS** [tars/tars#258]
Из доков:

> Если не требуется компиляция определенной страницы, то можно просто добавить '_' в начало названия страницы, и она не будет скомпилирована.

Но при этом получается, что она не отслеживается в watch, так? Т.е. что б увидеть изменения, нужно перезапускать TARS. Неудобно.
Можно сделать так, что б эти страницы не компилировались, но при этом изменения из них подхватывались во время разработки?

**Comment by artem-malko** [comment]
@LostSenSS пожалуй это хорошая мысль. Запилишь?) Даже строчку укажу, где это нужно убрать.
https://github.com/tars/tars/blob/master/tars/watchers/templates/page-modules.js#L19

**Comment by LostSenSS** [comment]
@artem-malko Запилил. #260

**Comment by artem-malko** [comment]
@LostSenSS увидел, отписался уже)

**Comment by LostSenSS** [comment]
@artem-malko В итоге всё же от слежения за такими страницами отказался? 
Вроде оно не работает.
