### ISSUE TITLE
При изменении стилей происходит полная перезагрузка страницы. 

### ISSUE THREAD

**Issue by LostSenSS** [tars/tars#261]
Так же не должно быть? BrowserSync совершенно точно умеет инжектить стили без перезагрузки страницы. 
Перепроверил на совершенно чистом новом TARS проекте. 
Такое чувство, что оно сперва правильно инжектит стили, но сразу после этого что-то всё равно триггерит полную перезагрузку.

**Comment by artem-malko** [comment]
@LostSenSS https://github.com/tars/tars/blob/master/plugins-config.json#L21 нужно установить в true

**Comment by LostSenSS** [comment]
@artem-malko Спасибо! Недоглядел. Работает.

**Comment by LostSenSS** [comment]
@artem-malko А по какой причине оно по дефолту выключено? Возможно у кого-то тоже возникнут вопросы с этим.

**Comment by artem-malko** [comment]
@LostSenSS оно не 100% хорошо работает
