### ISSUE TITLE
После обновления при запуске tars вылезает ошибка о том, что нет такого миксина как bg-svg

### ISSUE THREAD

**Issue by vilka-vk** [tars/tars#263]
У меня подобная [проблема](https://github.com/tars/tars/issues/209), только она не решается так просто и появилась после обновления тарса до последней на данный момент версии. 
У меня в sass используется переменная один в один с именем svg:
@include bg-svg($ic-clothes);
Но при запуске вылезает ошибка о том, что нет такого миксина bg-svg. 
```

An error occurred while compiling css for IE8.
Look in the console for details.

Error details:

markup/modules/catalog/catalog-list.scss
Error: Undefined variable: "$ic-t-shirt".
        on line 32 of markup/modules/catalog/catalog-list.scss
>>                     @include bg-svg($ic-t-shirt);
   ------------------------------------^
```

А если убрать флажки с поддержкой ie8/9, то тарс запускается без этих ошибок.

Не могу понять, что не так? Все по документации. В предыдущей версии все работало.

**Comment by vilka-vk** [comment]
Вообще как-то нехорошо получилось: два проекта у нас на тарсе версии 1.7.1, третий решили на новом тарсе запускать. Естественно, терминал попросил обновить tars-cli. И после его обновления мы теперь не можем запустить первые два проекта, т.к. версия тарса старая уже. Ну и после обновления конечно же вылезает данная ошибка + [еще одна](https://github.com/tars/tars/issues/264).

**Comment by artem-malko** [comment]
@vilka-vk есть возможность скинуть проект на tars.builder@gmail.com ? Проходит ли сборка с флагом:
```bash
tars build --ie9
```

**Comment by vilka-vk** [comment]
Сборка проходит. Проект отправила.

**Comment by artem-malko** [comment]
@vilka-vk как только получу, сразу потыкаю и отпишусь.

**Comment by vilka-vk** [comment]
Спасибо большое! Там же можно и по 264 issue потыкать )

**Comment by artem-malko** [comment]
@vilka-vk проблема оказалась комплексной. Прошу обновить и TARS-CLI и TARS в проекте. Отпишитесь, пожалуйста, помогло ли это.

**Comment by vilka-vk** [comment]
Все обновила, проблема осталась.
Удивительно, что я создала тестовый проект со скаченным ранее tars-master (v.1.8.2), перекинула туда markup из нашего проекта, и смогла запустить тест-проект без этой ошибки. Наш гит-репозиторий не подключала. А вот в рабочем проекте даже с обновлениями не прошел запуск.

**Comment by artem-malko** [comment]
@vilka-vk скорее всего проблема в том, что tars-cli не обновился. Какая версия у него сейчас?

**Comment by vilka-vk** [comment]
Посмотрела версии, оказалось, что до последних версий не проходит обновление. Т.е. tars-cli сейчас 1.8.5, а tars 1.8.2. Запускаю команду tars update - обновление не проходит

**Comment by vilka-vk** [comment]
> я создала тестовый проект со скаченным ранее tars-master (v.1.8.2), перекинула туда markup из нашего проекта, и смогла запустить тест-проект без этой ошибки

к сожалению, тут я ошиблась: в tars-config по умолчанию в 1.8.2 прописано `componentsFolderName: 'components'` , но у меня-то по старинке используется modules. Когда поменяла в конфиге на модули, то ошибка с svg проявилась. Прошу прощение, что накрутила тут проблем. Теперь основная остается в том, что не могу обновиться. А дальше надо смотреть.

**Comment by artem-malko** [comment]
@vilka-vk предлагаю просто снести tars-cli и поставить снова.

**Comment by vilka-vk** [comment]
Ок. Попробую в конце рабочего дня, а-то хочется успеть потрудиться над работающим проектом))

**Comment by vilka-vk** [comment]
Ну что ж, все прошло на "Ура!". Проект запустился с одной единственной синтаксической ошибкой:
`An error occurred with data-files!
SyntaxError: Unexpected token ILLEGAL
`
А с ней я думаю мы уже справимся сами) Спасибо Вам большое за оперативный и полезный фидбэк!

**Comment by artem-malko** [comment]
@vilka-vk круто, рад был помочь)
