### ISSUE TITLE
Ошибка после обновления tars: "Cannot read property 'defaults' of undefined"

### ISSUE THREAD

**Issue by vilka-vk** [tars/tars#264]
При запуске проекта после обновления тарса с версии 1.7.1 до последней вылезает ошибка 

```
[12:16:39] gulp-notify: [TARS notification] 
An error occurred while compiling to html.
Look in the console for details.

Error details:

/home/vilka/Project/gifts/tars-master/markup/modules/header/header.jade:43
    41| 
    42| 
  > 43|     +modal-catalog(modalCatalog.defaults)
    44|     +modal-feedback()
    45| 

Cannot read property 'defaults' of undefined

```

Раньше, конечно же все работало. В чем проблема - не понимаю, к сожалению ))

**Comment by artem-malko** [comment]
@vilka-vk как выглядит объект с данными к этому модулю? Как этот модуль подключается?

**Comment by artem-malko** [comment]
@vilka-vk это ожидаемое поведение. С версии 1.8 TARS умеет работать с вложенными компонентами. Раньше не умел, а вы уже это использовали) 
Про то, как работать с данными у вложенных компонентов можно прочесть в доке: https://github.com/tars/tars/blob/master/docs/ru/html-processing.md

**Comment by vilka-vk** [comment]
Спасибо! Будем адаптировать под новую версию )

**Comment by artem-malko** [comment]
@vilka-vk ждем)

**Comment by vilka-vk** [comment]
Убрала в файле header.jade все, что содержалось в скобках тут +modal-catalog()
Проект запускается теперь, но компилить мешает ошибка
`An error occurred with data-files! SyntaxError: Unexpected token ILLEGAL `
При этом неизвестно к какому файлу она относится.
