### ISSUE TITLE
При конкатенации файлов js файлы с префиксом "_" все равно попадают в итоговый файл

### ISSUE THREAD

**Issue by dmober** [tars/tars#265]
В частности из папок markup/js/framework | libraries ... даже при добавленном префиксе _ в названии файлов они все равно конкатенируются.
P.S. посмотрел в таске concat-processing исключения не указаны, это баг или фича?

**Comment by artem-malko** [comment]
@dmober кажется баг. Проверю. Спасибо за ишью)

**Comment by artem-malko** [comment]
In 1.9.0
