### ISSUE TITLE
Folder "undefined" and "Cannot read property 'defaults' of undefined_"

### ISSUE THREAD

**Issue by alexador** [tars/tars#267]
После tars init в папке markup вместо components создается папка undefined. После ее переименования в components при tars dev все равно выдается ошибка
\markup\pages\index.jade:9
> 9|         +head(head.defaults)
Cannot read property 'defaults' of undefined

**Comment by artem-malko** [comment]
@alexador 
1) Какая версия TARS и TARS-CLI?
2) Какая ОС и версия Node?
3) tars init запускался в свежем проекте или обновленном?
4) Какой был файл настроек при первом запуске tars-init?

**Comment by alexador** [comment]
@artem-malko 
1) tars 1.8.3, tars-cli 1.8.6
2) Win10 и Node 4.5.0
3) В свежем
4) Стандартный, при установке выбран jade. Но если выбирать handlebars то папка undefined все равно создается вместо components, но тестовая страница запускается без ошибок.

**Comment by alexador** [comment]
Способом без tars-cli вроде все ок, никаких ошибок при выборе jade нет, страница успешно открывается после gulp dev --lr

**Comment by artem-malko** [comment]
@alexador не могу повторить это( Можешь ли попробовать все шаги у себя повторить еще раз. В точной последовательности?

**Comment by artem-malko** [comment]
@alexador хорошо, что все заробило) Но до сути проблемы хотелось бы добраться)

**Comment by alexador** [comment]
@artem-malko ну в общем я удалил тарс-кли и нод, потом установил заново, потом переустановил виндовс и все стало быстро и хорошо )

**Comment by artem-malko** [comment]
@alexador жаль ,что не удалось повторить. Все равно спасибо)
