### ISSUE TITLE
 TARS + AngularJS

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#27]
Подумать о том, как организовать работу сборщика при использовании  AngularJS

**Comment by artem-malko** [comment]
В основном проблема заключается в том, что при использовании handlebars мы не можем использовать {{}} в AngularJS.
Также, необходимо пересмотреть включение партиалов в страницы. При использовании фреймворка этого встраивания не должно происходить.

**Comment by artem-malko** [comment]
+ минификация должна производится отдельным модулем.

**Comment by extiser** [comment]
ожидается ли поддержка Tars + AngularJS? хотелось бы понять как встроить в систему Ангуляр

**Comment by artem-malko** [comment]
@extiser на самом деле, уже сейчас можно. Есть опции https://github.com/2gis/tars/blob/master/docs/en/options.md#jspathstoconcatbeforemodulesjs-%D0%B8-jspathstoconcataftermodulesjs с помощью которых можно какие угодно еще js-сущности добавить в TARS. Каждый модуль у тебя может быть чем угодно, например дерективой.

Только шаблонизатор тебе придется использовать jade. С handlebars есть проблема {{}}.

**Comment by extiser** [comment]
то есть по сути, даже имея структуру папок в виде отдельных модулей - я могу просто указать общую папку в стиле "modules/**/*.js"?

**Comment by artem-malko** [comment]
@extiser не понял вопроса.

**Comment by extiser** [comment]
@artem-malko jsPathsToConcatBeforeModulesJs: [] - для данной опции в конфиге

**Comment by artem-malko** [comment]
@extiser понял, я думал, что вы хотите js, которые в модулях лежат добавить. Да, именно в таком стиле, только нужно так:

```javascript
modules/*/*.js
```

При этом \* означает 1 уровень вложенности, а \*\* — сколько угодно.

**Comment by extiser** [comment]
а нельзя ли складывать controller, view в одну папку? то есть раскладывая по модулям.

**Comment by artem-malko** [comment]
Если я все правильно понял, то до, можно. Но тогда стоит сделать следующим образом:

```javascript
markup
    modules
        exampleModule
            controller
                controller.js
            view
                view.js
            exampleModule.js
```

Дело в том, что для склейки js в бандл берется весь js, который лежит в modules на первом уровне вложенности.
Вы можете подправить таск js/processing если необходимо другое поведение.

**Comment by extiser** [comment]
хорошо. спасибо, пробую)

**Comment by artem-malko** [comment]
@extiser отпишитесь, пожалуйста, как все получилось?
Кстати, минификацю можете спокойно использовать, имена переменных не обфурсцируются.

**Comment by extiser** [comment]
@artem-malko конечно отпишу) конечно я не профи в angular, но будет пилотный проект у меня)

**Comment by artem-malko** [comment]
@extiser привет, есть успехи?
