### ISSUE TITLE
Call bower components through webpack

### ISSUE THREAD

**Issue by jm-kumaresh** [tars/tars#273]
I have installed a jquery plugin through bower and I called it through webpack. Now the webpack searches for the js file only on `node_modules` folder and not in `bower_components` folder. Also I have already added `bower_components` in webpack config. Attached screenshots for the reference.

**Added bower_component to webpack config**.
![image](https://cloud.githubusercontent.com/assets/2070512/18408927/d6cd8d5a-775a-11e6-9d6c-6bed431e5225.png)

**Added js file in main.js**
![image](https://cloud.githubusercontent.com/assets/2070512/18408918/b01f270e-775a-11e6-9daa-39042bb5ae49.png)

**Error on compile**
![image](https://cloud.githubusercontent.com/assets/2070512/18408912/8e2c54fa-775a-11e6-9faf-ace1b6e3c315.png)

**Comment by artem-malko** [comment]
First of all, could you install in through npm?
As you can see from [official docs for webpack](https://webpack.github.io/docs/usage-with-bower.html) bower — is not good idea. For example glide. It does not export anything from main file, so, webpack cannot import anything from there.

**Comment by jm-kumaresh** [comment]
@artem-malko It's not an issue to use npm instead of bower. But some components listed in bower is not listed in npm packages. In this case I have to use bower.

**Comment by jt3k** [comment]
@jm-kumaresh you can use an absolute path to the desired file

**Comment by jm-kumaresh** [comment]
@jt3k Thanks. It works.
