### ISSUE TITLE
Imported SASS files not detecting changes

### ISSUE THREAD

**Issue by jm-kumaresh** [tars/tars#274]
I have imported a sass file from `bower components`. It gets imported and works fine. But when I make changes to that imported sass file the changes doesn't get detected by `tars cli`. The modified sass file is not injected and browser is not reloading. But when i restart tars using `tars dev` command the modified sass files are injected and works fine.

**Comment by artem-malko** [comment]
@jm-kumaresh files from node_modules and bower_components are not watched. It is very strange, than you change something in files, which are out of your project.
