### ISSUE TITLE
Uncaught type error on js concat

### ISSUE THREAD

**Issue by jm-kumaresh** [tars/tars#276]
I'm using http://unslider.com/ for slideshow. Installed in plugin js folder and initiated through main js

![image](https://cloud.githubusercontent.com/assets/2070512/18864337/7802f09c-84b3-11e6-8594-2c4137341997.png)

In chrome console I'm getting the below error.

![image](https://cloud.githubusercontent.com/assets/2070512/18864410/d8e8ef4c-84b3-11e6-8ca3-5f6d77aea15a.png)

slider.js has this code

![image](https://cloud.githubusercontent.com/assets/2070512/18864556/84e7cc50-84b4-11e6-9624-2abb3991e926.png)

main,js compiles this order

![image](https://cloud.githubusercontent.com/assets/2070512/18864504/5794700a-84b4-11e6-8ba0-bb77d7081bf9.png)

**Comment by artem-malko** [comment]
Hello @jm-kumaresh 
First of all, you do not use concat. You use webpack)
If you use webpack, you have to require all your components into one entry point (or several entry points). So, it means, what you can not use just $(function ...), you should export something from your component/module and import/require it into entry point.
By the way, you need to work with webpack only, without TARS, cause you have some problems with understanding, who it works.

**Comment by jm-kumaresh** [comment]
@artem-malko Sorry that if I'm at basic level. Actually I'm designer with some HTML and CSS knowledge.

I'm not using concat. I'm using modular workflow and webpack bundler. 

1. `const jquery = require('jquery');`
This entry has jquery plugin

2. `const unslider = require('static/js/plugins/unslider/unslider');`
This entry has slider plugin

3. `const slider = require('components/slider/slider');`
This entry is the js file initialising the slider plugin in the banner id.

Could you help me where I'm going wrong..?

**Comment by artem-malko** [comment]
I said about concat and webpack because of the topic name) (Uncaught type error on js concat).
I think, it should help you https://webpack.github.io/docs/library-and-externals.html#examples
