### ISSUE TITLE
Move all tars-* reps to tars

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#279]
It is quite hard to maintain so many repositories: tars-jade, tars-scss and so on. So, I've decided to merge it into main tars rep.

**Comment by ilyoff** [comment]
@artem-malko as I see, there is no progress too long, may be I can take it?

**Comment by artem-malko** [comment]
Ok, it will be great!)

**Comment by ilyoff** [comment]
Я правильно понимаю, что нужно сохранить возможность применять нужную версию шаблона?
