### ISSUE TITLE
Does not work html-prettify

### ISSUE THREAD

**Issue by dimondevs** [tars/tars#284]
Менял опции в разных местах, всё равно не работает.
Может глянуть в эту сторону и сделать это для css, js, html сразу https://github.com/beautify-web/js-beautify. Была бы киллер фича, а так приходится в редакторе её узать на каждом файле.

**Comment by artem-malko** [comment]
Какой шаблонизатор юзается?
Какие опции не работают?
Где опции устанавливаешь?

**Comment by dimondevs** [comment]
handlebars
Не работают никакие, что я только не ставил
Меняю в plugins-config.json и tars/user-tasks/html/helpers/modify-options.js. Результата нет не там не там.

**Comment by artem-malko** [comment]
Обновил пакет html-pretiify, должно помочь

**Comment by artem-malko** [comment]
Будет в ближайшем релизе
