### ISSUE TITLE
add sugarss 🍬 🍭  🍰

### ISSUE THREAD

**Issue by TryHardNinja** [tars/tars#287]
Ребят, что насчет sugarss? https://github.com/postcss/sugarss

**Comment by artem-malko** [comment]
@TryHardNinja это специфический плагин. Tars - это инструмент, который удобно кастомизировать. Он уже сейчас имеет много всего, и я стараюсь, чтобы ничего лишнего туда не попадало. Данный плагин имеет аналоги и А каждый захочет выбрать то, что нравится именно ему. Кому-то этот плагин не подойдет, этим ему будет доставлено неудобство.

**Comment by artem-malko** [comment]
В любом случае, спасибо за предложение)
