### ISSUE TITLE
Некорректный вывод заголовка TARS в консоли RubyMine

### ISSUE THREAD

**Issue by TryHardNinja** [tars/tars#290]
![screen shot 2016-10-31 at 6 28 59 am](https://cloud.githubusercontent.com/assets/22329784/19840895/5d30a7f6-9f33-11e6-803e-2873cf7a1d56.png)
macOS 10.12

**Comment by artem-malko** [comment]
@TryHardNinja да, такое может быть( Но я не могу проверять, поддерживает ли консоль символы. Я проверяю по ОС.
