### ISSUE TITLE
Глобальная конфигурация tars

### ISSUE THREAD

**Issue by extiser** [tars/tars#294]
День добрый! Возможно ли как-то настроить глобальную конфигурацию tars, чтобы при инициализации проекта не вносить каждый раз правки в состав сборки?

Например: каждый раз вычищать не нужные мне классы из index.jade - не удобно. возможно можно было бы сделать какие-то предустановленные компоненты node_module (jquery, к примеру, который необходим мне в каждом проекте). Можно ли добавить свои миксины, которые я использую повсеместно? Свои наработки какие-то. 

Был бы признателен, если бы направили в нужную сторону или подсказали как я могу это реализовать. Использую tars-cli.

Спасибо.

**Comment by artem-malko** [comment]
Я рекомендую создать свой форк TARS. Например вот: https://github.com/senja006/tars TARS-CLI позволяет инициализировать TARS с любой версией: https://github.com/tars/tars-cli/blob/master/docs/en/commands.md#available-flags ключ -s или --source

**Comment by extiser** [comment]
Круто! Огромное спасибо!!

**Comment by artem-malko** [comment]
Рад был помочь)
