### ISSUE TITLE
Проблема с data файлами у вложенных компонентов

### ISSUE THREAD

**Issue by Lehakos** [tars/tars#295]
К примеру имеем такую структуру: parent-component/child-component. Имя data свойства для вложенного компонента получится такого вида: parent-component_child-component. Но это недопустимое имя для переменной в js, поэтому в jade невозможно использовать его, даже если заключить в кавычки. Предлагаю добавить опцию в настройки тарса, чтобы когда она включена, имена data файлов автоматически преобразовывались в camelCase стиль.

**Comment by artem-malko** [comment]
Кажется ее придется сделать не опциональной, а обязательной. Иначе дата не работает в Jade/Pug (

**Comment by jt3k** [comment]
Подготовил один из способов конвертации в кемел-кейс )

```js
'parent-component_child-component'
  .replace(/-+([^-])/g, (pre, inj) => inj.slice(0,1).toUpperCase() + inj.slice(1));
```

**Comment by movasyl** [comment]
@Lehakos, @artem-malko, в pug работает. 
`
fullData['component-name_second-component-name']
`

**Comment by Lehakos** [comment]
Не о том речь. Когда ты передаешь data при вызове миксина `+child-component('parent_child-component'.default)` - это не работает ни в jade, ни в pug.

**Comment by artem-malko** [comment]
@Lehakos а вот так подойдет:
+child-component(['parent_child-component'].default) ?

**Comment by artem-malko** [comment]
@Lehakos уже не пробуешь tars?)

**Comment by Lehakos** [comment]
@artem-malko Да, уже не пользуюсь :)

**Comment by artem-malko** [comment]
@Lehakos случаем не осталось проекта на tars с такой проблемой?

**Comment by Lehakos** [comment]
К сожалению нет. Использовал тарс на предыдущей работе. Сейчас доступа к репам нет.

**Comment by pashkes** [comment]
все ок, нужно обращатся через parentComponent_childComponent

**Comment by artem-malko** [comment]
Круто, тогда закрываю
