### ISSUE TITLE
Обновление Data.js

### ISSUE THREAD

**Issue by movasyl** [tars/tars#299]
При внесении изменений в data.js результат не рендериться пока не пересохранить pug шаблон. Причем просо перезаписать мало. Нужно что-то изменить (прим: поставить пробел), тогда сохранить и после этого изменения в data.js компонента будут скомпилированы.

Возможно проблема тут, но у меня не получается исправить (((

tars\watchers\templates\data-files.js
**templaterName** у меня **pug**, а проверка только на **jade**
```
if (templaterName === 'jade' && tars.packages.cache.caches && tars.packages.cache.caches.templates) {
            const templateToRecompile = watchedPath.split('/data/data.js').shift();

            for (let cacheKey in tars.packages.cache.caches.templates) {
                if (cacheKey.indexOf(templateToRecompile) > -1) {
                    delete tars.packages.cache.caches.templates[cacheKey];
                }
            }
        }
```

**Comment by pashkes** [comment]
у меня так же

**Comment by pashkes** [comment]
А как подтянуть эти изменения в свой проект?

**Comment by artem-malko** [comment]
@pashkes выполнить tars update-project в директории с проектом.
