### ISSUE TITLE
Подставление данных json в атрибуты (pug)

### ISSUE THREAD

**Issue by Ivanopalas** [tars/tars#301]
Не могу подставить данные в атрибуты. На данный момент мне требуется подставить данные в атрибут src. Пробовал так подставить img(src="#{data.img}"), не работает. Подскажите как подставить данные в атрибут?

**Comment by jt3k** [comment]
### 1 создаём данные
В файле `app/data/foo.json` пишем:
```json
{
	"bar": "hohoho"
}
```

### 2 получаем данные из жсон в шаблоне
Теперь в жсон файле можно получить доступ вот так:
```pug
//- определяем переменную в которой будет объект
- var foo = getData('foo');
//- используем эту переменную
.block(data-attribute="#{foo.bar}")
```

### 3 результат будет таким
```html
<div data-attribute="hohoho" class="block"></div>

**Comment by movasyl** [comment]
а зачем интерполяция? 
`
img(src = data.img)
`

**Comment by artem-malko** [comment]
@Ivanopalas В первую очередь рекомендую прочесть: 
1. https://github.com/tars/tars/blob/master/docs/ru/html-processing.md#Работа-с-компонентами-и-данными-в-jadepug 
2. https://pugjs.org/language/attributes.html

Затем, проверьте, что вы передаете данные в компонент. Проверьте, что в data.im действительно находятся нужные вам данные.

**Comment by Ivanopalas** [comment]
@artem-malko Я читал по ссылкам и все равно не получается сделать. Данные в data.js я передаю такого вида:
slider: {
  slide1: {
    img: '%=static=%img/assets/slider/slider_1.png'
  }
}
Не могу врубиться как мне передать.

**Comment by movasyl** [comment]
`
img(src = slider.slider1.img)
`

**Comment by artem-malko** [comment]
@Ivanopalas @movasyl прав, попробуйте так же.

**Comment by Ivanopalas** [comment]
@movasyl Спасибо, заработало)

**Comment by lionvsalex** [comment]
И тем ни менее, парень также как и я пробовал подставить: img(src="#{data.img}")
А все потому, что прямо из коробки видим такую конструкцию в head.pug:
...
16    if data.useSocialMetaTags
17    meta(property="og:title", content="#{data.title}")

А нужно вот как:
meta(property="og:title", content = data.title)
