### ISSUE TITLE
Папка components создана как undefined

### ISSUE THREAD

**Issue by impcyber** [tars/tars#303]
Развернул tars через tars-cli, однако в папке markup было создано 3 папки:
pages, static, undefined.
tars-cli 1.9.5
tars 1.9.6

UPD: 
Win: 10
Node: v6.9.1
Заметил похожую issue https://github.com/tars/tars/issues/267. При переименовании папки в components приводит к аналогичной ошибке. Плюс к этому я заметил что при инициализации проекта папка static и components создаются, но примерно после сообщения "[ TARS ]: It's almost ready!" создается папка pages и папка components переименовывается в undefined. Однако, я мельком заметил при установке tars-cli, что "пролетела" ошибка связанная с node-gyp и posix, могло ли это является причиной столь странного поведения?

![image](https://cloud.githubusercontent.com/assets/1425691/21473279/60713738-cb15-11e6-8bb1-d9310b8f9e44.png)

**Comment by impcyber** [comment]
Путем небольшого дебага выяснилось, что в tars-config.js просто отсутствовал параметр 
``"componentsFolderName": "components"``
После его добавления билд прошел успешно.
¯ \ _ (ツ) _ / ¯

**Comment by artem-malko** [comment]
@impcyber А можешь прям все шаги описать. Не совсем понятно, как в конфиг undefined затесалось)

**Comment by impcyber** [comment]
Да, конечно.

- Поставил tars-cli
``npm install -g tars-cli``
- Создал папку для проекта, зашел в нее через терминал, далее
``tars init`` - scss, jade, 92dpi, [static], [img], es2015, os notify
- Выждал процесс установки, увидев пролетевшую ошибку по сборке posix
- Несмотря в папку сразу запустил ``tars dev`` с liverload, на что получил Cannot get /index.html
- В терминале висит ошибка о том что невозможно подключить миксины из ../components
- Посмотрел в папку, а там три папки pages, static, undefined
- Переименовал папку undefined в components, на что вышла иная ошибка 
``9| +head(head.defaults)
Cannot read property 'defaults' of undefined``
- Далее был вычищен tars, tars-cli, поставлено все заново. Ситуация повторилась.
- После было решено, что-нибудь сотворить с node-gyp, после чего он был незамедлительно выпилен из $HOME\.node-gyp
- Но после тщетных попыток все это дело переставить еще раз, результат приводил к одному и тому же.
- Однако, после длительных и пристальных наблюдений за процессом развертывания проекта, было замечено, что изначально создается две папки pages и components, но после сообщения ``[ TARS ]: It's almost ready!`` создается папка static и папка component переименовывается в undefined.
- Было решено волевое решение залезть в коды tars (после ошибки о +head(head.defaults)),
тут https://github.com/tars/tars/blob/master/tars/tasks/html/concat-mocks-data.js#L14 ``${tars.config.fs.componentsFolderName}`` - undefined
тут https://github.com/tars/tars/blob/master/tars/tars.js#L49 global.tars.config.fs.componentsFolderName - undefined
открыл tars-config.js, а там только staticFolderName: 'static', и imagesFolderName: 'img', и ни слова о папке компонентов (модулей).
- Собственно, добавив "componentsFolderName": "components", все завелось и заверсталось

**Comment by artem-malko** [comment]
@impcyber то есть сразу после init в tars-config.js нет свойства componentsFolderName?

**Comment by impcyber** [comment]
Для верности, только что сделал init. Результат подтвердился:
```
    "useImagesForDisplayWithDpi": [
        96
    ],
    "fs": {
        "staticFolderName": "static",
        "imagesFolderName": "img"
    },
    "useBabel": true,
    "staticPrefix": "static/"
```
```

>npm -v
4.0.3
>node -v
v6.9.1
>tars -v
[ TARS ]: Tars-cli version: "1.9.5"
>ver
Microsoft Windows [Version 10.0.14393]
>dir markup
26.12.2016  21:47    <DIR>          .
26.12.2016  21:47    <DIR>          ..
26.12.2016  21:47    <DIR>          pages
26.12.2016  21:47    <DIR>          static
26.12.2016  21:47    <DIR>          undefined
               0 файлов              0 байт
               5 папок  30 348 484 608 байт свободно
```

**Comment by artem-malko** [comment]
@impcyber спасибо, Сейчас проверю

**Comment by artem-malko** [comment]
@impcyber все с нуля сделал - все работает ( Даже не знаю, как повторить. Попробуй выполнить вот что: 
npm un -g tars-cli 
npm cache clean 
npm i -g tars-cli

**Comment by artem-malko** [comment]
@impcyber ну и повторить tars init. Ты же все опции дефолтные используешь (просто enter нажимаешь)?

**Comment by impcyber** [comment]
К сожалению, смогу это сделать только после 5-го числа.

**Comment by artem-malko** [comment]
@impcyber а вот это уже странно. Такое ощущение, что TARS-CLI все же очень старый. А есть еще комп с той же ОС, чтобы проверить? И еще момент, какая версия у пакета tars-cli в глобальной папке с node_modules?

**Comment by impcyber** [comment]
В общем, проблема решилась полным сносом node (+ полная очистка папки) и установки заново. В папке nodejs/node_modules был tars-cli версии 1.6.8, вероятно, что из него и проходила инициализация от чего такой конфликт и возник.

**Comment by artem-malko** [comment]
Хорошо, что все разрешилось) Спасибо за участие)
