### ISSUE TITLE
Перейти на Browserslist

### ISSUE THREAD

**Issue by ai** [tars/tars#309]
Как я вижу, браузеры рекомендуется задавать явно [в конфиге](https://github.com/tars/tars/blob/master/plugins-config.json#L5) Автопрефиксера.

Но последнее время куча инструментов начинает поддерживать тот же формат указания браузеров — Babel, ESLint, Stylelint, cssnext.

Было бы круто, чтобы все инструменты использовали один конфиг. Поэтому мы стараемся перевести пользователей на `browserslist`. Есть два способа:

1. Конфиг `browserslist` в корне проекта.
2. Раздел `browserslist` в `package.json`.

Давай-те переведём TARS на общий конфиг тоже во имя добра.

**Comment by TryHardNinja** [comment]
В корне конечно

**Comment by artem-malko** [comment]
👍
