### ISSUE TITLE
JS файл для pages

### ISSUE THREAD

**Issue by Ivanopalas** [tars/tars#310]
Не пойму где создать js файл который будет работать с страницей (папка pages). С компонентами все отлично подхватывает js и все работает. А для страницы не пойму куда положить js файл что б все работало. Уже пробовал создать общий файл static/js/main.js но он так же не работает.

**Comment by artem-malko** [comment]
@Ivanopalas Привет. Такого места нет. На каждой странице вы сами управляете, какой JS-файл там подключится.

**Comment by impcyber** [comment]
Логичнее сделать просто компонент и подключать его на нужной странице

**Comment by Ivanopalas** [comment]
@artem-malko Я так понимаю что по сути если сам его подключаю то так же могу кинуть js файл куда хочу. А как его подключать? Как обычный js <script src="static/js/main.js">?

@impcyber Предлагаешь создать отдельно компонент без разметки и стилей чисто для js?

**Comment by impcyber** [comment]
@Ivanopalas Он все равно завернется в общий main.js, но дабы этого избежать можно поступить как описано в документации "Весь JavaScript-код собирается в один отдельный файл, кроме JavaScript-файлов, которые находятся в директории separate-js", следовательно подключать индивидуально для каждой страницы.

**Comment by artem-malko** [comment]
@impcyber либо использовать webpack, для создания нескольких бандлов. Тикет можно закрывать?

**Comment by Ivanopalas** [comment]
@artem-malko Решил вопрос созданием компонента с js файлом) Спасибо за помощь
