### ISSUE TITLE
Проблемы при выборе нужного варианта при tars init

### ISSUE THREAD

**Issue by SRG94** [tars/tars#311]
Доброго дня! делаю tars init через git bash. и при вопросе "Выберите препроцессор",нажав на стрелки, ничего не происходит. т.е. тупо не получается выбрать ни какой из вариантов. стрелки на клаве рабочие. скрин ниже.
ОС: Windows 7
http://SSMaker.ru/a3e0665d/
Очень жду помощи. Заранее благодарен!

**Comment by artem-malko** [comment]
@SRG94 да, есть такая проблема на винде. Выбор можно осуществить с помощью цифр: 1, 2, 3 и т.д.

**Comment by artem-malko** [comment]
@SRG94 помогло?)

**Comment by SRG94** [comment]
да, помогло. спасибо.
