### ISSUE TITLE
Убрать принудительный выбор css и html препроцессора. 

### ISSUE THREAD

**Issue by aleksandr-guryanov** [tars/tars#314]
Сейчас postCSS очень становиться актуальным, да и после [видео ](https://www.youtube.com/watch?v=CaDnbOjXjRg) . Хочется на небольших проeктах работать в привычном окружении и делать что то без scss / less и т.д. Думаю должно быть право не выбирать какие либо препроцессоры.

**Comment by jt3k** [comment]
с первым ишьюсом тебя 👍

**Comment by artem-malko** [comment]
@aleksandr-guryanov ох, окай) Пришло это время)) Надо только флоу для графики на postCSS перенести, а это самая большая боль.

**Comment by artem-malko** [comment]
Дубликат #128
