### ISSUE TITLE
На генерируется файл .min.css в сборке Build после изменения конфига

### ISSUE THREAD

**Issue by kendrive** [tars/tars#319]
Изменены только эти параметры:

"buildPath": "../../web/build",
"useBuildVersioning": false,
"useArchiver": false

TARS-CLI version: "1.9.5"
TARS version in current project: "1.9.7"

**Comment by artem-malko** [comment]
А с какими флагами запускается сборка?

**Comment by kendrive** [comment]
Release mode,  Minify files only

**Comment by artem-malko** [comment]
А что в билде вообще есть?

**Comment by kendrive** [comment]
В билде полная сборка как нужно, кроме минифицированного css.

**Comment by artem-malko** [comment]
А можете сделать пустой проект и сделать сборку в проде?

**Comment by kendrive** [comment]
Сделал сборку в новом пустом проекте, результат тот же. Нет min.css

**Comment by kendrive** [comment]
issue можно закрывать, у buildPath должен быть обязательно закрывающий слэш.

**Comment by artem-malko** [comment]
👍
