### ISSUE TITLE
Реализация двуцветных svg, workflow: symbols (currentColor)

### ISSUE THREAD

**Issue by mailamir** [tars/tars#320]
Вопрос по svg, workflow: symbols. Все работает, но мне надо добавить к элементу атрибут currentColor, чтобы можно было управлять двуцветными svg, делать это нужно в месте выводы %=symbols=% и добавлять к конкретным symbol > path.
Возможно это реализовать штатными средствами?

**Comment by artem-malko** [comment]
Конечно. Просто каждому path можно указать атрибут fill="currentColor" Тогда цвет у path будет такой, какой задан в color у svg через css
Просто нужно картинки предварительно подготовить.

**Comment by mailamir** [comment]
Спасибо! Добавлением fill="currentColor" в исходниках svg вопрос решается, но получается что нужно всякий раз править код svg иконки, которую присылает дизайнер.
Нет ли возможности возложить и эту рутину на tars?
ЗЫ. Спасибо за отличный продукт)

**Comment by artem-malko** [comment]
@mailamir к сожалению нет. Не на столько он умен)
