### ISSUE TITLE
Сборка SVG спрайта из папки компонента

### ISSUE THREAD

**Issue by Feofilov** [tars/tars#322]
Здравствуйте! Мне уж очень нравится система спрайтов которая позволяет включать иконку таким образом @include bg-svg($svg-image-name); Было бы очень круто если бы была возможность складывать svg иконки не только в static/img/svg/ но и отдельно в компонент. Это бы позволило просто копировать папку компонента из проекта в проект без каких либо дополнительных действий. Извиняюсь, если хочу слишком много)

**Comment by artem-malko** [comment]
@Feofilov были такие мысли. Но есть проблема, что если случится так, что в разных папках окажутся иконки с одним именем. Как порешать эту ситуацию очевидным образом — непонятно(

**Comment by Feofilov** [comment]
А в таком случае можно сделать ошибку в консоль?

**Comment by artem-malko** [comment]
@Feofilov можно ли ожидать pull-request'а?

**Comment by artem-malko** [comment]
Кажется нет) Пока увожу в backlog
