### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by v20stepanenko** [tars/tars#323]
как отключить или переместить всплывающеие окно, которые вылазит после перекомпиляции

**Comment by evilsprut** [comment]
С такими вопросами тебе на [toster](https://toster.ru/)

**Comment by impcyber** [comment]
Если вопрос касается системы нотификации, и мне не изменяет память, то достаточно выбрать "n" в процессе tars init при вопросе о "Use OS notifications"

**Comment by artem-malko** [comment]
Кажется разобрались)
