### ISSUE TITLE
 Package gulp-sass is not available.

### ISSUE THREAD

**Issue by TryHardNinja** [tars/tars#324]
![screen shot 2017-06-20 at 10 08 53 pm](https://user-images.githubusercontent.com/22329784/27351592-8e4d84b4-5606-11e7-9267-80a6063891d5.png)
v node 8.1.2
v tars-cli 1.9.5
v tars project 1.9.7
tars-cli обновлял 1.9.5 последняя, почему тогда проект получается 1.9.7?

**Comment by artem-malko** [comment]
В проекте указана версия сборщика, tars-cli - это не сборщик, это лишь cli-утилитка для сборщика. Полное удаление и установка tars не помогла?

**Comment by TryHardNinja** [comment]
![screen shot 2017-06-22 at 5 20 45 pm](https://user-images.githubusercontent.com/22329784/27438881-361d71fe-576f-11e7-949e-52a66e54b750.png)
при установки с помощью yarn

**Comment by TryHardNinja** [comment]
полное удаление не помогает

**Comment by veremey** [comment]
@artem-malko @fobos @chayn1k @ilkome  
И у меня не работает.  
windows 10 
node -v   == v8.3.0
tars -v  == Error: Cannot find module 'C:\Users\verem\AppData\Roaming\npm\node_modules\tars-cli\bin\tars.js'

1.  http://joxi.ru/bmoLjDwCMjNeJ2
2.  http://joxi.ru/brRJv3RHQ4ypnr

**Comment by artem-malko** [comment]
@TryHardNinja @veremey попробую на дня до последней версии node-sass обновить) Ожидайте

**Comment by Seminioni** [comment]
@artem-malko было бы в целом неплохо, если и не пилить что-то новое ТАРСу, так хотя бы обновлять зависимости время от времени. Как считаешь, Артём?

**Comment by artem-malko** [comment]
@Seminioni чертовски прав, но где взять время?)

**Comment by veremey** [comment]
Я все удалил и для начала установил Node-sass https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md 
А потом установил ТАРС заново и заработало. )

**Comment by veremey** [comment]
обновил node.js , git проблема вернулась.
В начатом проекте делаю `tars dev`  ->  *Package gulp-sass is not available.*
 http://joxi.ru/5md4elEUvOOoKm

Проект горячий (((  
Нужно работать. )

**Comment by Seminioni** [comment]
@veremey зачем обновили ноду?

**Comment by artem-malko** [comment]
@veremey откати ноду пока что. Я очень постараюсь на этой неделе выпустить обновление.

**Comment by artem-malko** [comment]
@veremey @Seminioni https://github.com/tars/tars-cli/issues/76 может вам поможет.

**Comment by veremey** [comment]
откат к node -> 8.3.0  // npm -> 5.5.1  не помог. 
https://www.youtube.com/watch?v=FCiS45AfbIc

**Comment by artem-malko** [comment]
@veremey нужно полностью все снести и поставить заново. Можно еще до 4 откатиться

**Comment by veremey** [comment]
Да, действительно помогло. 
Я откатил `NPM` и смог переустановить TARS, сейчас все заработало. 
Сделал: 
`npm install --global --production windows-build-tools`
`npm install --global --production npm-windows-upgrade`
`npm-windows-upgrade --npm-version 4.2.0`
`npm i -g tars-cli`

Сейчас: 
Windows 10
`$ node -v v8.9.1`  `$ npm -v 4.2.0`

**Comment by artem-malko** [comment]
@veremey То есть и на 8 ноде завелось?

**Comment by veremey** [comment]
да. 
Значит проблема в NPM ((

**Comment by Alorian** [comment]
Обновил ноду, так и не смог запустить. Откат не предыдущую версию npm не помог. Откат на старую 6 версию ноды помог, но решение честно говоря так себе :)

@artem-malko Надеюсь что все же получится обновить пакет :)

**Comment by veremey** [comment]
@artem-malko меня на проекте просят обновить Галп до gulp v4.0.0 .
Не будет ли у меня конфликтов? 
Ибо навозился с последними настройками. ))

**Comment by antonprog007** [comment]
@artem-malko Добавлю в копилку свое решение.
Необходимо обновить пакет gullp-sass в tars-cli до версии 3.1.0 в моем случае это помогло для node 8.9.4
Так же протестил на node 9.8.0 - тоже работает, только не забыть пересобрать node-sass надо `npm rebuild node-sass --force`

**Comment by artem-malko** [comment]
Fixed in 1.9.8

**Comment by veremey** [comment]
![screen shot](http://joxi.ru/KAgPMyWsEgXlYr)
v node 8.0.0
v npm 5.0.0
TARS-CLI version: "1.9.8"
TARS version in current project: "1.9.11"

OSX 10.13.6

**Comment by veremey** [comment]
Откатил ноду и  NPM удалил TARS 
 и все заработалою 
node -v -> 8.9.1 
npm -v -> 4.2.0
