### ISSUE TITLE
Wrong comment

### ISSUE THREAD

**Issue by zoxon** [tars/tars#325]
https://github.com/tars/tars/blob/master/tars/tasks/images/make-symbols-sprite.js#L18

"Minify png and jpg images" in make-symbols-sprite.js

**Comment by artem-malko** [comment]
@zoxon можно ожидать pull-request с исправлением?)

**Comment by zoxon** [comment]
Извините но нет, не пользуюсь тарсом. Смотрел как вы реализовали сборку иконок.

**Comment by artem-malko** [comment]
Fixed in 1.9.8
