### ISSUE TITLE
Icon helper error

### ISSUE THREAD

**Issue by LitvinenkoEvgeny** [tars/tars#326]
Здравствуйте, думаю эта проблема связана с #208
пытаюсь отрендерить иконку edit.svg находящуюся по пути: 
markup/static/img/svg/edit.svg
`
   != pugHelpers.Icon.call(locals, {iconName: 'edit'})
`
Cannot read property 'edit' of undefined
если в [tars/tasks/html/helpers/pug-helpers.js](https://github.com/tars/tars/blob/master/tars/tasks/html/helpers/pug-helpers.js)
на [22 строке ](https://github.com/tars/tars/blob/master/tars/tasks/html/helpers/pug-helpers.js#L22) прописать         `console.log(this.__iconsData, iconName);`
то выдаст `undefined 'edit'
`
если посмотреть на this, то там действительно не будет __iconsData
`
{ _template: { big: { title: 'Hello world', age: 10, button: false } },
  head: { defaults: { title: 'default title', useSocialMetaTags: true } },
  header: { defaults: { listLeft: [Object], listRight: [Object] } },
  __pages: [ { name: 'index', href: 'index.html' } ],
  pugHelpers: 
   { Icon: [Function: Icon],
     exampleHelper: [Function: exampleHelper] } }
`

**Comment by LitvinenkoEvgeny** [comment]
в конфиге по дефолту стоит sprite, сменил на symbols все заработало

**Comment by artem-malko** [comment]
@LitvinenkoEvgeny хорошая мысль. Можно ждать pull-request?)

**Comment by LitvinenkoEvgeny** [comment]
@artem-malko да. К понедельнику, закончу проект, над которым работаю и сделаю.

**Comment by veremey** [comment]
@LitvinenkoEvgeny  @artem-malko  пока не ту решения этой проблемы? 

Сейчас пытаюсь вставить svg в pug через:  
`!= pugHelpers.Icon.call(locals, {iconName: 'hands', className: 'hands', iconWidth: '25', iconHeight: '25'})`
и в css : 
`
.some {
	display: inline-block;
	@include bg-svg($hands)
}`

Первый вариант не работает вообще. 
А второй не дает возможности задавать размеры, цвет для картинки. 

Что я делаю не так? 
Дайте, пожалуйста, пример, как комментарий. 
Спасибо!

**Comment by artem-malko** [comment]
@LitvinenkoEvgeny 👍

**Comment by artem-malko** [comment]
@LitvinenkoEvgeny pull-request все еще приветствуется)

**Comment by donbot-inc** [comment]
@artem-malko Issue resolved?

**Comment by artem-malko** [comment]
@donbot-inc Yeah! You are right!
