### ISSUE TITLE
Замена дублирующихся свойств при компиляции. 

### ISSUE THREAD

**Issue by TIIGRUS** [tars/tars#327]
Не знаю есть ли подобная вещь и можно ли ее вообще реализовать, я новичок в работа с gulp. А данный инструмент очень пригляделся. Так вот в чем состоит идея. 

При компиляции, чтобы свойство, которое в каскаде является более приоритетным к одном и тому же селектору просто заменялось. На примере бутстрапа мы понимаем, что нам нужно переопределять необходимые свойства, но таким образом происходит лишнее нагромождение кода. Почему бы не сделать так, чтобы то что мы переопределяем в кастомном файле стилей при компиляции фрэймворка(bootstrap), заменялось уже нашим свойство и избегать тем самым лишнее нагромождение. 

Вот пример скрина, к одному и тому же селектору без родителей и потомков и т.д применяется одинаковое свойство, оно глобальное. http://joxi.ru/DmBXvEZhwo1XPA

**Comment by artem-malko** [comment]
@TIIGRUS не совсем тебя понял. Напиши, пожалуйста, что хочется в итоге увидеть?

**Comment by TIIGRUS** [comment]
На скрине видно, что у селектора ".btn" есть 2 одинаковых свойства "font-size". Одно подтягивается из файлов bootstrap, а другое переопределено мною. Так вот,чтобы при компиляции файлов, оставалось мое значение "font-size", а то свойство, что находится в файлах бутсрапа просто не компилировалось. 

Если к одному и тому же селектору применяться 2 одинковых свойства, остается то что определённо мною в моих фалах.

**Comment by TIIGRUS** [comment]
Вот в итоге, что должно быть. http://joxi.ru/xAeGVeBUpyxG3m Остается только мое свойство к классу ".btn".

**Comment by Seminioni** [comment]
@TIIGRUS https://github.com/ben-eb/postcss-discard-duplicates

**Comment by TIIGRUS** [comment]
@Seminioni Хорошая попытка, но мне нужно, что-то для scss.

**Comment by TIIGRUS** [comment]
Хорошо было бы если бы это дело работало с коробки) Многие , кто пользуется фрэймворками думаю оценили был)

**Comment by Seminioni** [comment]
@TIIGRUS твой сасс компилирует все твоё барахло (*.scss) в css и уже дальше postcss добивает плагинами, которые ты определишь в тарсе.

**Comment by TIIGRUS** [comment]
@Seminioni да так уже интересненько. Однако если выбран только один препроцессор, то как быть?

**Comment by Seminioni** [comment]
@TIIGRUS так включи postcss в конфиге или как он включается в тарсе.

**Comment by TIIGRUS** [comment]
@Seminioni  вот скрин конфига http://joxi.ru/Q2Knvx1F48oglm

**Comment by Seminioni** [comment]
@TIIGRUS доку иди покури лучше.

**Comment by TIIGRUS** [comment]
@Seminioni ок, спасибо. Попробую завести.

**Comment by TIIGRUS** [comment]
Для тех, кто только начинает работать с gulp, а тем более с TARS самому прикрутить плагину немного сложновато.

**Comment by TIIGRUS** [comment]
Если это будет уместно, реализуйте данную фичу на уровне пользователя, чтобы не лезть в лишние файлы.

**Comment by Lehakos** [comment]
@TIIGRUS А как вы себе представляете это? Сборщик должен удалить font-size из класса бутстрапа? А откуда он может знать что в другом месте не потребуется этот font-size из бутстраповского класса? Это не осуществимая идея.

**Comment by TIIGRUS** [comment]
@Lehakos В static/GUI.scss я переопределяю общие стили касательно .btn. а те что дублируется удаляются.

**Comment by TIIGRUS** [comment]
По иерархии gui находится ниже и приоритет выше чем у  бутстрапа, значит его свойства и будут по умолчанию оставлены. Все остальные в топку.

**Comment by TIIGRUS** [comment]
@Seminioni Попробовал я этот плагин  https://github.com/ben-eb/postcss-discard-duplicates, не плохой. Но не то ,что я имел ввиду. 
Если будет такой расклад: 
.btn{
   color: red.
}
и чуть ниже в другом файле будет описан, точно такой же стиль, то да он его заменит. 
Но если там будет другой цвет кнопки, прописанный глобально, то он не заменит его. 
.btn{
   color: black;
}
Тут ничего не произойдет и будет все то же самое нагромождение.

**Comment by artem-malko** [comment]
Кажется тикет уже можно закрыть)
