### ISSUE TITLE
Почему jsPathsToConcatBeforeModulesJs не подключается в самом начале?

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars#328]
По логике jsPathsToConcatBeforeModulesJs должен же подключаться самым первым?
Так как я подключаю через node_modules Jquery плагин. Но при сборке проекта  jquery оказывается не в начале документа js.

**Comment by artem-malko** [comment]
Исходя из названия jsPathsToCincatBeforeModulesJs должен подключаться до скриптов модулей. Здесь не сказано, что подключение идет до все оставшихся компонентов.
https://github.com/tars/tars/blob/master/docs/ru/js-concat-processing.md#Работа-с-js-с-помощью-простой-склейки по этой доке можно узнать, как именно собираются файлы, если используется конкатинация.

**Comment by DjSunrise** [comment]
Получается такие библиотеки типа jQuery и тд нужно ложить в папку libraries ?
Так же хотел спросить еще один вопрос не создавая новый. Как быть с плагинами у которых есть свои шрифты и иконки? Судя по вашей документации нужно ложить шрифты все в папку fonts, иконки  в папку general и тд.  Но это ведь не удобно если например я хочу вырезать плагин из проекта нужно искать по всем папкам его части? =)

**Comment by artem-malko** [comment]
Придется раскладывать, если испольузется конкатинация(
