### ISSUE TITLE
Tutorial по созданию собственных тасков(task). 

### ISSUE THREAD

**Issue by TIIGRUS** [tars/tars#329]
Было бы не плохо иметь какой-нибудь туториал по созданию собственных тасков. А то вроде tars должен снижать уровень рутины до 0%, а выходит, что настраивание тасков повышает этот уровень. Как работать тем, у кого сравнительно небольшой опыт работы с gulp и другими полезными инструментами. В gitter не всегда достучишься, а тут вроде отвечают , а вроде и нет) На презентации tarsa призывалось создавать issues и т.д если не понятно что-то.

**Comment by artem-malko** [comment]
https://github.com/tars/tars/blob/master/docs/ru/tasks.md
https://github.com/tars/tars/blob/master/docs/ru/tasks-and-watchers.md
Ну и есть пример таска с комментами: https://github.com/tars/tars/blob/master/tars/user-tasks/example-task.js
Боюсь, если я начну писать туториал — я просто повторю доку галпа. Спрашивается — зачем?)

**Comment by TIIGRUS** [comment]
@artem-malko Согласен, что копипастить доки не зачем)  Спасибо, за ссылки). Одако, было бы не плохо иметь, что-то более наглядное) типа скринкаста. )) 

Вопрос может не по теме, но вот столкнулся со сложностью. По поводу вот этой ссылки https://github.com/tars/tars/blob/master/docs/ru/tasks-and-watchers.md по замете встроенных task/watch своими. Не работает эта структура. Мне нужно заменить встроенный helper для css(concat-compile-css-task-template.js). Я создал всю структуру для этого и продублировал файл убрал не нужные директории для компилирования, но он все равно подгружает дефолтный.

**Comment by TIIGRUS** [comment]
@artem-malko Вот пример, того что хотелось бы видеть , но не подхватывает. http://joxi.ru/Vm6yVb4IDPoz3r

**Comment by artem-malko** [comment]
@TIIGRUS нужно, чтобы имя таска было таким же, как и оригинальный. В этом все дело)
Закрываю issue

**Comment by TIIGRUS** [comment]
@artem-malko Чуть выше я приложил скрин, такое же название и вложенность папок, но все равно не подхватывает пришлось делать костыль и лезть и исходники, что не очень удобно и не практично если тарс нужно будет обновить.

**Comment by artem-malko** [comment]
@TIIGRUS там файл  назван по-своему)

**Comment by TIIGRUS** [comment]
@artem-malko Как другое? Вот прилагаю еще раз скрин http://joxi.ru/Vm6yVb4IDPoz3r Такое же название, я выделил его стрелкой и подчеркнул.

**Comment by artem-malko** [comment]
Так это не таск) Это же просто функция-хелпер)

**Comment by TIIGRUS** [comment]
@artem-malko Спасибо, думал что их тоже можно перезаписать своей.)
