### ISSUE TITLE
Yaml support?

### ISSUE THREAD

**Issue by 7iomka** [tars/tars#330]
Всем привет.
Есть ли какая-либо возможность добавить в качестве альтернативного варианта представления поддержку файлов yaml?
Я использую fractal для сборки текущих проектов (как одностраничников так и многостраничников), где реализован механизм выбора вариантов представления: json (любителям хардкора), yaml (сначала не мог привыкнуть, а потом забыл про боль с скобками, js - тогда, когда надо использовать для возврата данных какой-нибудь node.js модуль или сделать запрос по ajax и получить ответ.
Изучаю ваш сборщик, и если привыкнуть после nunjucks к handlebars я ещё смогу, то вот писать рутинные объекты (а-ля перечень наименований и свойств ссылок глубокоуровневого меню) никак не решусь.
Посему, надеюсь что Вы меня обрадуете что можно как-нибудь припаять yaml поддержку - хотябы для модулей со статическими параметрами.
Спасибо!

**Comment by artem-malko** [comment]
Боюсь, сейчас не будет времени такое реализовывать( Можно в папйплайн работы с данным из json вставить преобразователь yaml кода в json?

**Comment by 7iomka** [comment]
Не срочно, но на досуге, если будет время, я б не отказался от минималистического примера. Спасибо

**Comment by artem-malko** [comment]
Кажется у меня совсем не будет времени( Предлагаю обратиться с этой просьбой в гиттер
https://gitter.im/tars/tars?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
