### ISSUE TITLE
не работает  require

### ISSUE THREAD

**Issue by veremey** [tars/tars#331]
Не работает запись const Chart = require('chart.js');   в JS  компонента. 
Как решить?

**Comment by artem-malko** [comment]
Использовать сборку с webpack.
https://github.com/tars/tars/blob/master/docs/ru/js-webpack-processing.md

**Comment by veremey** [comment]
"useBabel": true
![Image error](http://joxi.ru/krDJwPEH0ypWY2)
------------------------------------------------------


"useBabel": false

![Image error](http://joxi.ru/nAykRawIXd74km)


Подскажи, плз, что я делаю не так?
