### ISSUE TITLE
зачем нужны дубликаты файлов main.css и main.js _ie8, _ie9?

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars#337]
Можно подробно описать зачем нужны эти доп файлы для IE? 
В чем их различие от основного файла?
Если они точная копия оригинального и созданы чтобы  в них дописывать хаки и костыли то смело можно удалять? Потому что не совсем удобно при передаче на бэк энд вносить изменения новые во всех файлах. Я просто пытаюсь понять для каких целей они как с ними работать ))

**Comment by artem-malko** [comment]
Они только для хаков в этих браузерах. Если мы говорим про исходники — то в них добавляем хаки. Если говорим про билд — в билде создаются файлы именно для этих браузеров, чтобы другие не содержали в себе хаки и не тащили лишний код.
