### ISSUE TITLE
Экстра перенос строки в sass?

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars#338]
Как сделать так чтобы на выходе из scss в css, css код сохранял переносы?

`/* ==========================================================================
   GUI styles of the project
   For example, styles of the links, buttons and so on.
   ========================================================================== */

/* Buttons
   ========================================================================== */

.button {
    font-weight: 500;
}

А на выходе выходит :

/* ==========================================================================
   GUI styles of the project
   For example, styles of the links, buttons and so on.
 ========================================================================== */
/* Buttons
 ========================================================================== */
.button {
  font-weight: 500;
}

**Comment by artem-malko** [comment]
Я думаю, надо посмотреть, какие опции можно передать в препроцессор.
