### ISSUE TITLE
На выходе один build версию?

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars#340]
Как на выходе иметь одну билд версию? Так как удобно работать с гитом и пушить изменения программистам. Чтобы при создании нового билда заменялись лишь те файлы которые новые

**Comment by aleksandr-guryanov** [comment]
Откройте файл tars-config.js там измените
'"useBuildVersioning": false,
"useArchiver": false,' 
 и в этом случае не факт что гит будет видеть толко измененные файлы. Так как каждый билд - есть новые сгенерированные файлы ( папка builds удаляется при создании билда ). Плюс если Вы используете свг спрайты в теле *.html то каждый файл будет обновляться ( когда будут добавляться новые свг иконки или свг файлы в проект в папку images/svg )
