### ISSUE TITLE
проблема с множественными линейными градиентами в svg symbols

### ISSUE THREAD

**Issue by 6y6a** [tars/tars#341]
Когда собираешь svg symbols в один файл, где в иконках используются разные линейные градиенты, то в итоговом файле у всех градиентов один и тот же id, поэтому на всех иконках один и тот же градиент 

`<linearGradient id="a/></linearGradient>
<linearGradient id="a/></linearGradient>
<linearGradient id="a/></linearGradient>
`

я решил проблему с помощью пользовательского таска и использования [gulp-svgmin](https://github.com/ben-eb/gulp-svgmin#per-file-options)
Возможно, какую-нить функциональность для разрешения одинакового id нужно и в основную ветку добавить

**Comment by aleksandr-guryanov** [comment]
Обычно при использовании свг символов не используют градиенты внутри иконок, используют в основном только шейпы. Это сделано с целью возможности управлять цветом. Это не баг - это фича! ) А как я понял ваше решение заключается в том, что svg min вырезает градиенты и другие  атрибуты ? И у Вас остается просто черная иконка.

**Comment by artem-malko** [comment]
@6y6a придется переопределить таск, так как конфиг для svgo в нем зашит. https://github.com/tars/tars/blob/master/tars/tasks/images/minify-svg.js#L33 вот эта строчка

**Comment by artem-malko** [comment]
@6y6a тут можно ознакомится, как сделать переопределение тасков: https://github.com/tars/tars/blob/master/docs/ru/tasks-and-watchers.md#%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%82%D0%B0%D1%81%D0%BA%D0%B0%D0%BC%D0%B8-%D0%B8-%D0%B2%D0%BE%D1%82%D1%87%D0%B5%D1%80%D0%B0%D0%BC%D0%B8
