### ISSUE TITLE
SVG sprite symbols

### ISSUE THREAD

**Issue by aleksandr-guryanov** [tars/tars#343]
![image](https://user-images.githubusercontent.com/5307826/38803115-aa71ee6a-4187-11e8-8aae-4d064cdc693f.png) Какая то не обычная проблема. Иконки перестают растягиваться в 100%.  Причем если заменить, 100 на 24 то все встает в норму ... 
![image](https://user-images.githubusercontent.com/5307826/38803193-e25818fe-4187-11e8-91bf-296d1cb0907c.png)

Работает если в свг будет только такой формат 
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
``` 
и понять н могу почему ранее он жаловался на viewBox так как с 

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24">``` 

уже не работает. Это теперь все иконки перекраивать ?

**Comment by aleksandr-guryanov** [comment]
![image](https://user-images.githubusercontent.com/5307826/38812411-a5c9a7ea-41a5-11e8-9fe9-1dd01d2ec7ec.png)
Оказывается viewBox вырезается на стадии минификации.

**Comment by aleksandr-guryanov** [comment]
Странный баг, если у svg иконки заданы размеры width height то все ломается ... не видит viewBox и все.

**Comment by aleksandr-guryanov** [comment]
```
**Не работает**
<!-- 
    Иконка скачанная интернета 
    оригинальный файл
 -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24">
    <path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
</svg>
<!-- 
    Иконка скачанная интернета 
    минифицированный из ./dev/.../minified-svg
 -->
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5h18v2H3v-2z"/></svg>

**Работает**
<!-- 
    Иконка скачанная интернета 
    пересохранил в илюстраторе
    оригинальный файл
 -->
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<path d="M3,6h18v2H3V6 M3,11h18v2H3V11 M3,16h18v2H3V16z"/>
</svg>

<!-- 
    Иконка скачанная интернета 
    пересохранил в илюстраторе
    минифицированный из ./dev/.../minified-svg
 -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5h18v2H3v-2z"/></svg> ``` 

И все же я не могу понять в чем причина, попробовал поставить ```removeDimensions: true``` не помогло
removeDimensions - remove width/height attributes if viewBox is present (opposite to removeViewBox, disable it first) (disabled by default)

**Comment by aleksandr-guryanov** [comment]
**Не работает удаляет viewBox**
```
<!-- 
    Иконка скачанная интернета 
    оригинальный файл
 -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24">
    <path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
</svg>
<!-- 
    Иконка скачанная интернета 
    минифицированный из ./dev/.../minified-svg
 -->
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5h18v2H3v-2z"/></svg>
```


**Работает оставляет viewBox**
```
<!-- 
    Иконка скачанная интернета 
    пересохранил в илюстраторе
    оригинальный файл
 -->
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
<path d="M3,6h18v2H3V6 M3,11h18v2H3V11 M3,16h18v2H3V16z"/>
</svg>

<!-- 
    Иконка скачанная интернета 
    пересохранил в илюстраторе
    минифицированный из ./dev/.../minified-svg
 -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 6h18v2H3V6m0 5h18v2H3v-2m0 5h18v2H3v-2z"/></svg> 
``` 

И все же я не могу понять в чем причина, попробовал поставить 

```removeDimensions: true```

не помогло, 
removeDimensions - remove width/height attributes if viewBox is present (opposite to removeViewBox, disable it first) (disabled by default)

**Comment by artem-malko** [comment]
Странно, потыкаю как-нибудь этот момент.

**Comment by TIIGRUS** [comment]
@aleksandr-guryanov Было что-то похожее, но с иконками генерируемые фотошопом, почему-то ни в какую не принимал или иконки отображлись выборочно. Решение: скачивать качественную графику с нормальных фотобанков. Либо проверить фотошоп, как он их генерирует.

**Comment by artem-malko** [comment]
Проблема приобрела стихийный характер. Будем решать обновлением пакета на определенную версию.

**Comment by Folo4ka** [comment]
@artem-malko Как решение продвигается? сборщик просто нерабочий уже как 1,5 месяца из-за того

**Comment by aleksandr-guryanov** [comment]
@Folo4ka не думаю что вопрос решиться быстро. Перед тем как закидывать иконку в проект, удалить вначале параметры height и width и все прекрасно будет работать.

**Comment by Folo4ka** [comment]
@aleksandr-guryanov это точно не вариант, скетч, зеплин, фигма экспортит с высотой и шринойи руками это убирать - тупизм. 

я зашел в AppData\Roaming\npm\node_modules\tars-cli открыл package.json, поменял версию gulp-imagemin на 3.4.0, прописал из этой папки npm i, и все стало работать

**Comment by artem-malko** [comment]
@Folo4ka @aleksandr-guryanov постараюсь на этой неделе выпустить фикс)

**Comment by artem-malko** [comment]
Готово) 
Вот изменения, которые нужно применить в текущем проекте, чтобы не обновлять его череp tars-cli — https://github.com/tars/tars/commit/8eea0d5e9ec28e70547bde365fc7d647c15053c3

**Comment by aleksandr-guryanov** [comment]
Спасибо большое. На сколько я понял imagemin добавили ? И через svgo решили вопрос ?

**Comment by artem-malko** [comment]
@aleksandr-guryanov нет, он был уже) Просто API плагина другое. По доке он старый формат тоже поддерживал, а на деле оказалось, что нет)
