### ISSUE TITLE
Не могу импортировать JS файлы из node_modules

### ISSUE THREAD

**Issue by CcRaZyY** [tars/tars#344]
Привет, вопрос прост, почему не получается импортировать jQuery из node_modules.
У меня:

> npm 5.8.0
> node 8.11.1

Установил jQuery через `npm i jquery -D`, пробовал запускать как с добавлением строк к `providePlugins`  в `tars-config.js`, так и без этого.
Странность в том что при `workflow` = `modular` и добавлении строк в `providePlugins`, импорт проходит и всё работает, но тогда не работает модульность и пропадает проверка **js** файлов в **dev режиме**.
Но как только ставлю `workflow` = `concat` никаким образом не получаю доступ к **jquery** или каким-либо другим плагинам...
Надеюсь понятно описал проблему.

**Comment by artem-malko** [comment]
Привет.
Что значит опция providePlugins?
Если workflow modular, значит с JS идет работа через webpack, значит его нужно явно import'ить/require'ить куда-нить.

**Comment by CcRaZyY** [comment]
Я имел ввиду это:
> "providePlugin": {
                $: "jquery",
                jQuery: "jquery",
                "window.jQuery": "jquery"
            }
А если workflow concat, то есть вообще возможность import'ить/require'ить из node_modules?

**Comment by artem-malko** [comment]
А, понял.
providePlugin придется описывать в файле с конфигом вебпака)

**Comment by CcRaZyY** [comment]
![-2](https://user-images.githubusercontent.com/14764134/39161301-9f7a3154-47a2-11e8-90f8-7258dc15085a.jpg)
Если речь идёт об этой записи, то пробовал, результат не изменился

**Comment by artem-malko** [comment]
https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by artem-malko** [comment]
Помогло?

**Comment by artem-malko** [comment]
Видимо да) Закрываю пока что
