### ISSUE TITLE
Расширение .sass, вместо .scss?

### ISSUE THREAD

**Issue by TheUnchainedPug** [tars/tars#345]
Привет, Артем.
С недавнего времени стал знакомиться с тарс, но не нашел встроенной возможности, при инициализации, после выбора препроцессора выставить .sass, вместо .scss.
Вообще, возможно ли это?
Спасибо.

**Comment by artem-malko** [comment]
Привет.
При выборе scss в качестве препроцессора поддерживаются расширения как scss, так и sass. Встроенные файлы при ините имеют расширение scss, этого поменять нельзя (только если руками все переименовать).
