### ISSUE TITLE
Не подключается стили из node_modules

### ISSUE THREAD

**Issue by pashkes** [tars/tars#346]
Вообщем пытаюсь подключить тот же бутстрап как в этом примере https://github.com/tars/tars/blob/master/docs/ru/css-processing.md но в скомпилированном файле никаких стилей бутстрапа нету в итоге

**Comment by CcRaZyY** [comment]
`npm i bootstrap --save (или -D)`
так устанавливал?

**Comment by artem-malko** [comment]
Кажется лучше перенести это в gitter)
