### ISSUE TITLE
Add css critical path

### ISSUE THREAD

**Issue by alexHlebnikov** [tars/tars#35]
**Идея:** The critical path is the path to render a web page - what's needed before that can happen. CSS Stylesheets block rendering. Until the browser has requested, received, downloaded and parsed your stylesheets, the page will remain blank. By reducing the amount of CSS the browser has to go through, and by inlining it on the page (removing the HTTP request), we can get the page to render much, much faster.
**Вариант добавления:** прикрутить https://github.com/addyosmani/critical от Addy Osmani
**Полезные ссылки:**
Critical Path CSS Generator: http://jonassebastianohlsson.com/criticalpathcssgenerator/
critical-path-css-demo от Addy Osmani https://github.com/addyosmani/critical-path-css-demo
Презентация CSS and the critical path: https://speakerdeck.com/patrickhamann/css-and-the-critical-path

**Comment by artem-malko** [comment]
Думаю можно поместить в следующий релиз, если штука окажется реально полезной.

**Comment by alexHlebnikov** [comment]
Новая статья на тему с видео, где хорошо виден эффект использования техники: http://dbushell.com/2015/02/19/critical-css-and-performance/

**Comment by alexHlebnikov** [comment]
Статья на тему: http://www.smashingmagazine.com/2015/08/understanding-critical-css/
