### ISSUE TITLE
Как правильно добавлять библиотеки, плагины в tars?

### ISSUE THREAD

**Issue by Vladimir-Golub** [tars/tars#350]
При создании tars-cli конкотенацию js, css файлов выбрал автоматически.
Как в данном случае лучше добавлять библиотеки и плагины.
Скачал jquery, bootstrap. Раскидал в нужные папки все работает. Но как быть если выйдет новая версия. Если добавлять простым скачиванием, то возникают проблемы с обновлением.
Если использовать npm или bower, то с scss файламми еще понятно их import можно бросить в файл .scss плагинов или библиотек, а как подключить js ?

**Comment by artem-malko** [comment]
В данном случае — только руками.
Предлагаю заинитить проект снова, и уже не использовать конкатенацию.

**Comment by artem-malko** [comment]
Закрываю. Видимо вопрос решен
