### ISSUE TITLE
Некорректная сборка спрайта

### ISSUE THREAD

**Issue by pashkes** [tars/tars#353]
Некорректно собирает svg спрайт(separate-file-with-link) если в иконке применяются маски. После того как такую иконку закидываешь в папку, спрайт стает навалидный и никакие иконки вставленные до этого на странице не отображаются

**Comment by artem-malko** [comment]
@pashkes приведите пример такой иконки. Исходник)

**Comment by pashkes** [comment]
https://codepen.io/pashkes/pen/gjPYdx

**Comment by artem-malko** [comment]
@pashkes как быстрое решение — задать более уникальные id, вместо просто a и b.

**Comment by artem-malko** [comment]
@pashkes помогло?

**Comment by pashkes** [comment]
@artem-malko нет, svg с примера codepen обновил

**Comment by artem-malko** [comment]
@pashkes а есть пример уже готового спрайта с такой иконкой?

**Comment by pashkes** [comment]
@Hay-hey все эти иконки в виде черных квадратов отображаются там после того как загрузил
Почему так, что это значит?

**Comment by pashkes** [comment]
[https://drive.google.com/file/d/13ZyFkTecfKj07uhqh68Z0m_irRfhF6SZ/view?usp=sharing](url)
архив который сгенерировал icomoon там и исходники и спрайт

**Comment by Hay-hey** [comment]
@pashkes я конечно не увидел исходных svg, но например, если взять award.svg обработанный icomoon и удалить эту строку http://prntscr.com/kc87se , то все станет ок.
Возможно проблема в исходных svg :/

**Comment by pashkes** [comment]
@Hay-hey да, помогло, спасибо, проблема решена
