### ISSUE TITLE
Для чего нужны файлы ie9 и ie8?

### ISSUE THREAD

**Issue by DjSunrise** [tars/tars#354]
С тарсом работаю давно и в начале сразу из проекта выпилил все файлы для IE. Сейчас решил попробовать может реально что-то дельное. Но все же перепробовав разные вариации не понимаю для чего они нужны. 

Задумка такая, то что в этих стилях хранятся хаки для IE. Но ведь их можно сразу прописывать в main.css разве нет?

Я понимаю если бы эти хаки для ie не дублировали весь код main.css а в них были только именно "хаки" то это было бы круто. 

Объясните конкретно  как работать с файлами для поддержки ie8 и ie9 может я как-то не правильно понял их задумку?

Так же рассказать зачем нужны main_ie8.scss, _components-ie8.scss, _service-ie8.scss - потому что они тупо дублируют подключаемые файлы (может есть разница всего в одной подключаемом файле но все же это не повод всё дублировать и подключать)

**Comment by artem-malko** [comment]
Эти файлы нужны, чтобы собрать код для этих браузеров отдельно. Потому что в них много лишнего может быть, чего остальным браузерам нет нужды прокидывать.
