### ISSUE TITLE
Синтаксис html тегов внутри строк данных компонента

### ISSUE THREAD

**Issue by pashkes** [tars/tars#355]
Подскажите как мне вставлять теги внутрь строки данных компонента
если просто писать в таком виде: ` 'some text' + <br /> 'end title'`
то идет просто преобразование все в строку
`/n`
тоже не переносит

**Comment by artem-malko** [comment]
Необходимо использовать функции, которые выводят содержимое как html-сущности. Для handlerbars — {{{ строка или переменная со строкой с html }}}, для jade/pug — https://pugjs.org/language/interpolation.html
