### ISSUE TITLE
Tars build -m not worked 

### ISSUE THREAD

**Issue by aleksandr-guryanov** [tars/tars#356]
`🅃 🄰 🅁 🅂 : Build task has been started!

⠋🅃 🄰 🅁 🅂 : Build options (active are green):
⠋🅃 🄰 🅁 🅂 : Release mode "-r".
⠋🅃 🄰 🅁 🅂 : ✓ Minify mode.
⠋🅃 🄰 🅁 🅂 : IE8 maintenance "--ie8".
⠋🅃 🄰 🅁 🅂 : IE9 maintenance "--ie9".
⠋🅃 🄰 🅁 🅂 : IE8 and IE9 maintenance "--ie".
⠋🅃 🄰 🅁 🅂 : Custom flags. "--custom-flags" 'customFlags, with space separator'

⠋🅃 🄰 🅁 🅂 : Execute "tars build --help", to see all avaliable options.
⠋🅃 🄰 🅁 🅂 : You can use interactive mode via starting tars without any flags.
⠋🅃 🄰 🅁 🅂 : Please wait for a moment, while I'm preparing builder for working...

/usr/local/Cellar/node/10.8.0/bin/node: bad option: --min
[12:12:16] Node flags detected: --min
[12:12:16] Respawned to PID: 2494`

**Comment by artem-malko** [comment]
Will test in NodeJS 10.8.0

**Comment by aleksandr-guryanov** [comment]
> Will test in NodeJS 10.8.0

Как быть с данной проблемой - пока не планируете тест или точнее ориентировочно в ближайшее время ? Стоит откатиться лучше ?

**Comment by Hay-hey** [comment]
@artem-malko подтверждаю, на 10.10 крашится с флагом -m, во всех остальных случаях - ок.

**Comment by artem-malko** [comment]
@aleksandr-guryanov @Hay-hey  Будет апдейт) Пока лучше откатиться. Я пока в отпуске, через недельку постараюсь выпустить.
Кажется, проблема с npm cache clean

**Comment by donbot-inc** [comment]
I think, this is a gulp error on NodeJS versions >= 10
 
```
tars-cli git:(master) ✗ gulp --min
/Users/user/.nvm/versions/node/v10.11.0/bin/node: bad option: --min
[01:10:17] Node flags detected: --min
[01:10:17] Respawned to PID: 63654
```

Can anyone open issue for this problem? https://github.com/gulpjs/gulp/issues/new

**Comment by aleksandr-guryanov** [comment]
> @aleksandr-guryanov @Hay-hey Будет апдейт) Пока лучше откатиться. Я пока в отпуске, через недельку постараюсь выпустить.
> Кажется, проблема с npm cache clean

npm cache clean --force решает вопрос. А вот по поводу минификации проблема серьезная получается) Как отпуск ? ) Может решим этот баг, он довольно таки критический ((( чет сам разобраться не могу.

**Comment by artem-malko** [comment]
@aleksandr-guryanov уже в тестировании) Ожидайте в tars-cli 1.10.3 Фикс, конечно, несколько костыльный, но до выяснений обстоятельств подойдет. Сейчас идут тесты. Как новая версия будет в npm — напишу сюда.

**Comment by artem-malko** [comment]
Готово в tars-cli 1.10.3
