### ISSUE TITLE
Сборка стилей для IE при svg-symbols

### ISSUE THREAD

**Issue by CcRaZyY** [tars/tars#357]
Привет, столкнулся с проблемой компиляции стилей для ie при использовании `svg-symbols`.
**Проблема:** При задании стилей для ie8(9) они попадают в итоговый main.css и в main_ie8(9).css, заглянув в исходники нашёл строку: `if (tars.config.svg.active && tars.config.svg.workflow === 'sprite') {...}`, потом попробовал удалить условия по спрайтам и всё стало ок.
**Вопрос:** На сколько я правильно сделал и не поломает ли это что-то ещё? И почему было изначально такое условие?

**Comment by artem-malko** [comment]
Так, не совсем понял проблему. Какие именно стили попадают в оба файла? Приведи пример, пожалуйста.

**Comment by CcRaZyY** [comment]
Создаю папку `IE` в неё кидаю файлы `ie8(9)`, при настройки `svg-sprite` стили для **ie** попадают каждый в свой файл минуя при этом `main.css`. Но если я ставлю `svg-symbol`, то стили попадают во все файлы включая `main.css`. Поэтому полез в исходники и нашёл там строки которые говорят, что если включены `svg-sprite`, то при компиляции нужно делать исключение для папки `IE`. Ну или я все не так понял?)

**Comment by artem-malko** [comment]
@CcRaZyY так какие именно стили, покажи код) Я постараюсь объяснить, почему тот или иной кусок кода оказался там, где он оказался.

**Comment by artem-malko** [comment]
Погоди, тут ведь ничего нет про символы. Вообще, для ie9 и ie8 свои файлы стилей. Они подключают только их (в зависимости от версии). main — для других бразуеров

**Comment by CcRaZyY** [comment]
Просто я думал что любые стили описанные в этих файлах будут попадать в соответствующие итоговые файлы..

**Comment by artem-malko** [comment]
Погоди, так и есть) То что написал для IE9 только в его main файле и появится

**Comment by CcRaZyY** [comment]
Вот мы и подошли к сути😄. Я не вижу такого эффекта если включаю `svg-symbols` в `tars-config`. Поэтому я полез в конфиг и нашёл [вот](url) эти строки и как говорил выше, если [выношу ](https://ibb.co/jp9wN9) из под условия, то всё работает как надо, но в стандартном случае все что пишу в стилях для ie попадает и в общий `main.css` и в тот что для **ie**

**Comment by CcRaZyY** [comment]
Ответ все ещё приветствуется😉

**Comment by CcRaZyY** [comment]
Ну я попробовал, у меня целый проект на этом сидит, ошибок не видел пока

**Comment by artem-malko** [comment]
@CcRaZyY давай пулик, это легко будет просто новой версией (минорной)

**Comment by CcRaZyY** [comment]
Пока тестил нашёл ещё один прикол, стили для ie8 попадали и в ie9 и в ie8, и наоборот так же работало, заодно поправил это)

**Comment by artem-malko** [comment]
@CcRaZyY спасибо, вмержил) Думаю, этот тред можно закрыть
