### ISSUE TITLE
Компонент внутри компонента, ошибка при передачи данных

### ISSUE THREAD

**Issue by pashkes** [tars/tars#358]
Проблемы с передачей данных в дочерный компонент если дочерний компонент находится в папке родительского компонента. В доке написано что чтоб дочерний компонент получил глобальный объект данных, нужно в родительский компонент ничего не передавать, я так и сделал, но при компиляции эти данные компонент не видит
node v8.11.2

**Comment by artem-malko** [comment]
Привет.
Проиллюстрируй кодом, пожалуйста. И скинь ссылку на доку, про которую говоришь.

**Comment by artem-malko** [comment]
@pashkes код все еще нужен, чтобы понять, в чем проблема)

**Comment by pashkes** [comment]
@artem-malko на днях постараюсь залить тестовую репу где это будет показано. На самом деле приятно что идет поддержка до сих пор)

**Comment by CcRaZyY** [comment]
А ты пробовал запустить сборку и посмотреть в moskData именование дочернего компонента? На сколько помню у него имя становится вида `parent_children`

**Comment by pashkes** [comment]
все работает через parent_children, разобрался, спасибо)
