### ISSUE TITLE
Будет ли обновление Webpack

### ISSUE THREAD

**Issue by Solunsky** [tars/tars#359]
Здравствуйте! Начну с самого важного, сборка - самая лучшая)
Встал вопрос, в планах ли обновление Webpack до 4 версии? 

На данный момент webpack можно обновить до 2.1.0-beta.22 ибо уже далее начинаются проблемы.

**Comment by artem-malko** [comment]
Планы были. Попробую в ближайший месяц сделать.

**Comment by artem-malko** [comment]
Issue — https://github.com/tars/tars/issues/360
