### ISSUE TITLE
Подумать в сторону Post CSS

### ISSUE THREAD

**Issue by alexHlebnikov** [tars/tars#36]
**Что такое:** https://github.com/postcss/postcss
PostCSS is a tool for transforming CSS with JS plugins. The growing ecosystem of PostCSS plugins can add vendor prefixes, support variables and mixins, transpile future CSS syntax, inline images, and more.
PostCSS can do the same work as preprocessors like Sass, Less, and Stylus. But PostCSS is modular, 4-40x faster, and much more powerful.
PostCSS itself is very small. It includes only a CSS parser, a CSS node tree API, a source map generator, and a node tree stringifier. All CSS transformations are encapsulated in modular plugins. And these plugins are themselves small plain JS functions, which receive a CSS node tree, apply transformations to it, and return a modified tree.
**Почитать о плюсах и минусах:**
Breaking up with Sass: it’s not you, it’s me: http://benfrain.com/breaking-up-with-sass-postcss
I'm Excited About PostCSS, But I'm Scared to Leave Sass: http://davidtheclark.com/excited-about-postcss

**Comment by artem-malko** [comment]
Если хочешь, могу рассказать, как реализовано хранение доп. тасков к TARS (less-tasks, jade-tasks и т.д.) и ты сам попробуешь прикрутить это? Будет опциональный выбор css-препроцессор или PastCss.

**Comment by alexHlebnikov** [comment]
Да, давай как-нибудь расскажешь :)

**Comment by alexHlebnikov** [comment]
Перевод статьи на русский: http://css-live.ru/articles/rasstavanie-s-sass-delo-ne-v-tebe-delo-vo-mne.html
