### ISSUE TITLE
Update webpack from 2 to 4

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#360]

**Comment by artem-malko** [comment]
@aleksandr-guryanov если webpack не юзался совсем — не должно. Если юзался, придется руками поправить свой конфиг. Старый конфиг (если он был изменен) не будет удален при обновлении.

**Comment by aleksandr-guryanov** [comment]
Странно, но попробовал установить в другую папку и конфиги сравнить, для этого попробовал обновиться и тут шляпа. "npm cache clean" где то запускается в tars-cli при попытки его обновить. Вообщем безуспешно на этой команде tars update вылетает. Пришлось удалить и заново установить. Но показывает версию 1.9.11 и конфиги вебпака не отличаются. Как быть ?

**Comment by artem-malko** [comment]
Погоди, а что обновлял, cli или сам сборщик?

**Comment by artem-malko** [comment]
Кажется, в 10 ноде что-то изменилось с npm cache clean, тут те же пробелмы https://github.com/tars/tars/issues/361

**Comment by artem-malko** [comment]
done!
