### ISSUE TITLE
При создании новый проект не видит main.js

### ISSUE THREAD

**Issue by Nikolasgrizli** [tars/tars#361]
Добрый день. При создании нового проекта с недавнего времени стала появляться ошибка.
Порядок действий:
новая папка
tars init
tars dev
Выскакивает в консоли две строки - 
index.html:60 GET http://localhost:3004/static/js/main.js 404 (Not Found)
Refused to execute script from 'http://localhost:3004/static/js/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

танцы с бубном не помогают как и явное присвоение типа для скрипта:
<script type="text/javascript"  src="%=static=%js/main%=hash=%%=min=%.js"></script>

**Comment by CcRaZyY** [comment]
А сам файл main.js успешно компилится папку?

И пусть вроде должен содержать `dev/build` если я правильно понимаю

**Comment by Nikolasgrizli** [comment]
нет, только две папки выходят в билде - http://prntscr.com/ktfne9

**Comment by Nikolasgrizli** [comment]
в папке dev тоже самое

**Comment by CcRaZyY** [comment]
тут скорее всего он не компилится просто из-за того что файл main.js пустой, создай какой-нибудь скрипт и смотри что получится, должна появиться папка js и в ней main.js

**Comment by Nikolasgrizli** [comment]
делал, да и пустой раньше собирался

**Comment by Nikolasgrizli** [comment]
нашёл проблему так-же с update, возможно это как-то связано:
http://prntscr.com/ktkn1g - tars update
npm cache clean  работает, но только с --force

**Comment by artem-malko** [comment]
Так, кажется это уже другая проблема.
По поводу main.js — при работе с js через webpack, если нет скриптов, файл не создается.
Вторая проблема уже интереснее, надо копать.

**Comment by Nikolasgrizli** [comment]
я создаю без вебпака, просто с конкатенацией - вот нулейвой проект http://prntscr.com/kut820
и сразу после запуска(tars dev) я вижу ту же картину http://prntscr.com/kut8mk

**Comment by Yanduz** [comment]
Тоже имеется такая проблема, неважно пустой файл main.js или нет, когда включен вотч (dev --lr) то когда меняешь, что нибудь, то в консоли вообще ничего не происходит, как будто просто не следит за этим фалом с самого начала

**Comment by Selnapenek** [comment]
Такая проблема почему-то из-за новой версии gulp'a.

**Comment by artem-malko** [comment]
done! Можно проверять в новой версии

**Comment by artem-malko** [comment]
Пустой файл не появляется — это норм. Для этого может чуть позже сделаем стаб. Сейчас же, как только появится первый js — файл появится и все будет ок.
