### ISSUE TITLE
Обновить Normalize.css до 8.0.0 

### ISSUE THREAD

**Issue by Yanduz** [tars/tars#362]
Начну с того, что TARS просто бомба, я только начинаю погружаться в веб разработку, но даже сейчас понимаю, что это супер облегчение работы. По делу, развернул проект, потыкал и заметил, что normalize еще 3.0.3 трех летней давности, такое себе, мозолит глаза :d Кстати тоже имею ошибку npm cache clean при tars update (MacOS Mojave, NodeJS 10.10.0)

**Comment by CcRaZyY** [comment]
Возможно есть смысл добавить вместо этого что-то другое? есть отличный пример с [хабра](https://habr.com/post/420539/)

**Comment by artem-malko** [comment]
@Yanduz предлагаю замутить pull request) Только не забудь увеличить версию tars в  package.json и tars.json

**Comment by CcRaZyY** [comment]
Если я правильно понимаю то pull request будет затруднён так же как и в #321

**Comment by artem-malko** [comment]
@CcRaZyY видимо да(

**Comment by pashkes** [comment]
было бы еще неплохо чтоб пофиксили подключение библиотек с node_modules, так как сейчас сборщик не видит эти подключения

**Comment by pashkes** [comment]
@artem-malko [ссылка на мой репозиторий](https://github.com/pashkes/tars)
Я пытаюсь передать данные в миксин которые находятся в папке вложенную в компонент

**Comment by artem-malko** [comment]
@pashkes подскажи, на что обратить внимание?)
