### ISSUE TITLE
tars build падает с ошибкой при изменении buildPath в конфиге

### ISSUE THREAD

**Issue by FoxMalder** [tars/tars#366]
Tars build падает с ошибкой при изменении buildPath в конфиге. Передо мной бекендер поставил задачу, чтобы готовый билд находился не в папке с проектом, а на уровень выше, т.е. есть проект под названием frontend, в нем есть папка builds и в нем находятся билды. Мне нужно, чтобы все сбилдженные файлы находились рядом с папкой frontend.
Я изменил в конфиге следующие строки:
"buildPath": "../builds",
"useBuildVersioning": false,
"useArchiver": false.

После запуска tars build вылетает ошибка:

 UnhandledPromiseRejectionWarning: Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (C:\Users\shagaev_d\AppData\Roaming\npm\node_modules\tars-cli\node_modules\del\index.js:19:9)
    at C:\Users\shagaev_d\AppData\Roaming\npm\node_modules\tars-cli\node_modules\del\index.js:35:5
    at Array.map (<anonymous>:null:null)
    at C:\Users\shagaev_d\AppData\Roaming\npm\node_modules\tars-cli\node_modules\del\index.js:33:28
    at <anonymous>:null:null

(node:12272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

При чем, если поменять путь на "buildPath": "./builds", то все становится нормально.
Помогите, пожалуйста

**Comment by FoxMalder** [comment]
Закрывающий слеш ставил, но все равно не помогает. При первом запуске команды tars build все хорошо, а вот при втором возникает ошибка. Если я переименую папку с названием билда, то при первом запуске все хорошо, а при втором снова падает с ошибкой. Наверное проблема в перезаписи файлов

**Comment by artem-malko** [comment]
Правкой кода самого сборщика(
