### ISSUE TITLE
Ошибка обработки, JavaScript has not been processed

### ISSUE THREAD

**Issue by rucomcode** [tars/tars#369]
После обновления до последней версии tars-cli при команде tars dev выдает ошибку "JavaScript has not been processed", ниже указывает на причину -  "Error: Cannot find module 'babel-preset-es2015' from '/Users/roman/Develop/gbuz'". 
Если поставить пакет 'babel-preset-es2015', тоже валится с "JavaScript has not been processed", но теперь причина уже другая - "Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/roman/Develop/gbuz/node_modules/babel-preset-es2015/lib/index.js"
Пробовал ставить babel-preset-env - результат не меняется. Как быть?
node 9.11.1
npm 5.6.0

**Comment by donbot-inc** [comment]
I haven't fixed the problem yet. Just write @babel/preset-env in "presets" section in .babelrc file. babel-preset-es2015 package no longer needed, it can be removed.

**Comment by artem-malko** [comment]
@donbot-inc do we need an issue for that?

**Comment by donbot-inc** [comment]
> @donbot-inc do we need an issue for that?

No, already in https://github.com/tars/tars-cli/issues/87 and already fixed in https://github.com/tars/tars-cli/pull/90

**Comment by artem-malko** [comment]
done in tars-cli 1.10.3
