### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

### ISSUE THREAD

**Issue by Schamil74** [tars/tars#370]
`tars dev -l` `tars add-component header -b -a -d` и вылетела ошибка
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/home/shamil/Documents/tars/node_modules/@babel/preset-env/lib/index.js")

**Comment by donbot-inc** [comment]
Tars version? Tars-cli version? And view package.json project

**Comment by Schamil74** [comment]
The problem was solved by updating the tars cli.

**Comment by artem-malko** [comment]
Cool) Thank you, @donbot-inc for advice)
