### ISSUE TITLE
Does not work tars add-component 

### ISSUE THREAD

**Issue by veremey** [tars/tars#372]
@artem-malko 
Не работает команда `tars add-component header`
Выдает такую ошибку 

![image](http://dl4.joxi.net/drive/2018/11/14/0015/3317/1027317/17/487dc62c81.jpg)

🅃 🄰 🅁 🅂 : TARS-CLI version: "1.9.8"
🅃 🄰 🅁 🅂 : TARS version in current project: "1.10.1"

**Comment by artem-malko** [comment]
Да, в 1.10.3 пофиксили https://github.com/tars/tars-cli/releases/tag/1.10.3
