### ISSUE TITLE
Долгая компиляция

### ISSUE THREAD

**Issue by pashkes** [tars/tars#373]
Первый запуск сборки около 6 минут происходит, хотя в это время процессор и диск почти не нагружены. Может подскажете в какую сторону копать
Использую pug в качестве шаблонизатора. Думал может из за большого количества компонентов(около 80) и страниц штук 40. Самое странное что билд очень быстро делается
![image](https://user-images.githubusercontent.com/16703984/48713810-eb405700-ec19-11e8-92fe-8c3f1ec68b0e.png)

**Comment by pashkes** [comment]
> @pashkes насколько быстры последующие пересборки?

смотря в каких файлах делать изменение, от 2 секунд, если этот миксин только в одном месте подключен или 35 секунд если этот миксин на многогих страницах используется

**Comment by artem-malko** [comment]
К сожалению, первая долгая сборка как раз и нужна, чтобы последующие были быстрее. Тут ничего не поделаешь.

**Comment by SkiperX** [comment]
Подниму тему
сделал проект из 15 блоков и столкнулся с долгой компиляцией pug и scss при изменениях.
6-20 секунд в среднем.

подумал что сам что то сломал, но нет. 
Заинитил чистый тарс, подключил scss бутстрап, взял 1000 строк pug со случайного сайта,
и вот:
http://joxi.ru/E2pB8eVi7Oz6Zr
галп же должен это за миллисекунды компилить

**Comment by pashkes** [comment]
и меня в итоге тот проект так увеличился что в какой то момент страницы которые не нужны были закидывал в папку архив, потому что первого запуска сборки можно было минут 40 ждать 🤣

**Comment by SkiperX** [comment]
Так это не проблема pug
Простой gulp task компилит 20 страниц за 1.66 ms

**Comment by CcRaZyY** [comment]
В моём случае помог SSD диск -_- но это не панацея скорее временное решение пока проект не раздуется)

**Comment by artem-malko** [comment]
@SkiperX первый билд в dev-сборке — это не только билд, а еще и построение сложного кеша, который перебилжевания ускоряет сильно. К сожалению, сейчас нет мейнтейнров, которые занимались бы тулзой, которая этот кеш создает. Приходится сидеть на старых пакетах(

**Comment by SkiperX** [comment]
@artem-malko gulp-newer не выход?

**Comment by artem-malko** [comment]
@SkiperX к сожалению нет. Этот пакет не умеет сам разрешать зависимости между файлами.

**Comment by vilka-vk** [comment]
У меня не только первый билд компилится долго, но и в процессе разработки html компилится порой дольше 5 минут, css 2-3 минуты. И это при том, что на проекте пока что всего лишь 7 страниц, все практически одинаковые. Я правда не знаю как количество страниц влияет на скорость загрузки одной в лайв-релоадере... 
Разрабатывать уже крайне сложно. Мой поток мыслей в миллиарды раз быстрее тарса, и я пока жду пока скомпилится изменение в 2 символа успеваю забыть что и зачем делаю. Может все таки можно что-то сделать чтобы лайв-релоадер работал быстрее? 
В 2016 году тарс был лучше.

**Comment by SkiperX** [comment]
Мне помогло отключение опции "safe write" в настройках PHPStorm. На горячую норм стало компилить.

Или вот, наткнулся на статью пару дней назад, но еще не пробовал
https://medium.com/@inomdzhon/%D1%83%D1%81%D1%82%D0%B0%D0%BB%D0%B8-%D0%B6%D0%B4%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE%D0%BA%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D0%BE%D0%B1%D0%B8%D1%80%D0%B5%D1%82%D1%81%D1%8F-jade-pug-%D0%BF%D1%80%D0%B8-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B5-front-end%D0%B0-%D0%B5%D1%81%D1%82%D1%8C-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-341aaf589a70

**Comment by vilka-vk** [comment]
Решилась проблема. Оказалось, что в файл с лого в src был вставлен большущий код base64, файл весил в итоге 213КБ. Удаляем этот код, все моментально работает, за 3 секунды компилится. Так что сама виновата.

**Comment by artem-malko** [comment]
@vilka-vk :+1:

**Comment by olegKusov** [comment]
У меня сборка происходит больше 10 минут... пипец.

**Comment by artem-malko** [comment]
@olegKusov нужна хоть какая-то инфа, какие настройки выбраны, какая IDE, какой размер проекта
