### ISSUE TITLE
Вопрос по user-tasks

### ISSUE THREAD

**Issue by CcRaZyY** [tars/tars#379]
Привет. Это больше вопрос чем проблема)
Вот захотел я поменять конфиг сборки стилей, повторяю в user-tasks файловую структуру до файла `concat-compile-css-task-template.js`, меню там название файлов и порядок сборки, пытаюсь запустить  сборку, но мой конфиг не применяется, я так понимаю простого объявления переменных (одноименных с оригинальным файлом) в user-tasks не достаточно? Нужно описывать весь порядок действий? Можно ли решить как-то "малой кровью"?)

**Comment by artem-malko** [comment]
По идее, для переопределения существующих тасков достаточно только оснвоной файл с таском назвать также. А есть пример такого проекта?

**Comment by CcRaZyY** [comment]
Вот [ссылка](https://Dave-Dev@bitbucket.org/Dave-Dev/test.git) на тестовый проект

**Comment by artem-malko** [comment]
@CcRaZyY мм?)

**Comment by CcRaZyY** [comment]
Всё равно не дошло немного) про работу с тасками я понял. Получается в модули я не могу заходить из юзер-тасков? А как тогда переопределить такие моменты?

**Comment by artem-malko** [comment]
@CcRaZyY не, я говорю про то, что ты хелпер положил свой в user-tasks, а в самой таске юзается встроенный же. https://bitbucket.org/Dave-Dev/test/src/c1b52da2879f23c58bddfccfabc4e7e2cfa266d7/tars/tasks/css/compile-css.js?at=master&fileviewer=file-view-default

Нужно не только хелперы свои добавлять, но и таск! Точнее даже так, в первую очередь таск.

**Comment by CcRaZyY** [comment]
А, всё, понял, я балбес! Не указал что я новый хелпер создал)) тогда вопрос закрыт) сейчас переопределю такс).

Тогда есть ещё один вопрос, почему при сборке стилей указывается что файл `vars` импортится во втором подходе, ещё и после файла шрифтов.
Я так понимаю что сначала нужно определить какие-то переменные в файле `vars`, а потом использовать их во всех других файлах, но тогда нужно файл в самом начале прокидывать..(или я не прав?)
А сейчас получается что я не могу в миксинах и шрифтах использовать какие-либо переменные, поэтому собственно я и хотел у себя переопределить этот файл.

Если это было сделано чтобы переопределить стили от библиотек, то непонятно, в библиотеках используют флаг `!default` и это даёт нам возможность переопределять стили даже если файл с нашими переменными находится перед файлом библиотеки

**Comment by artem-malko** [comment]
Уже не помню, почему так было сделано) Делай, как тебе удобно)
issue закрываю
