### ISSUE TITLE
tars 1.10.6 bug

### ISSUE THREAD

**Issue by veremey** [tars/tars#382]
### `tars dev` выдает ошибки. 
Просит обновиться - обновился 
![](http://joxi.ru/nAybXZ9fgg0Plr.jpg) 

### Но есть ошибки при сборке, предполагаю, что нужно было обновиться как-то иначе 
![](http://joxi.ru/brRQ8MYS77Px3A)

tars просит этот плагин в 'js:webpack-processing' , 'main:build-dev',   'js:processing' 
🅃 🄰 🅁 🅂 : TARS-CLI version: "1.10.4"
🅃 🄰 🅁 🅂 : Update available for TARS-CLI! New version is: "1.10.6"
🅃 🄰 🅁 🅂 : Run the command "tars update" to update TARS-CLI.
🅃 🄰 🅁 🅂 : TARS version in current project: "1.11.5"
npm -v: 4.2.0 
node -v: v8.9.1 
`tars update` и `tars update-project` не обновляет версию :( 
## Что я делаю не так?

**Comment by artem-malko** [comment]
Предлагаю сделать так:
``` 
npm un -g tars-cli &&  npm cache clean --force && npm i -g tars-cli
```

**Comment by veremey** [comment]
Да. Помогло. 
Спасибо!
