### ISSUE TITLE
Взаимодействие локальных пакетов и пакетов установленных глобально в tars-cli

### ISSUE THREAD

**Issue by pinkman-frontend-user** [tars/tars#390]
Хочу добавить в проект vue.js, для этого надо сделать два действия - настроить webpack.config.js и .eslintrc

1 - добавляю зависимости в package.json

**dependencies**

```
...
"vue": "^2.5.17",
...
```

**dev-dependencies**

```
    ...
    "pug": "^2.0.3",
    "pug-loader": "^2.4.0",
    "pug-plain-loader": "^1.0.0",
    "vue-loader": "^15.4.2",
    "vue-template-compiler": "^2.5.17",
    ...
```

Настраиваю webpack.config.js

![image](https://user-images.githubusercontent.com/44676144/51985479-00a1ef00-24af-11e9-9666-ab3fdf81e902.png)
![image](https://user-images.githubusercontent.com/44676144/51985359-b7ea3600-24ae-11e9-9d39-60c64a7ed030.png)
![image](https://user-images.githubusercontent.com/44676144/51985343-b02a9180-24ae-11e9-854c-0f78a77567d5.png)

получаю вот такое 

![image](https://user-images.githubusercontent.com/44676144/51985456-ee27b580-24ae-11e9-9308-08e0cb565692.png)

_костыльно решается установкой webpack локально, можно даже не менять tars.require на require в конфиге_

2 - добавляю плагин в .eslintrc

![image](https://user-images.githubusercontent.com/44676144/51985551-2dee9d00-24af-11e9-8907-a443d5b3189c.png)

и добавляю его в локальный package.json

**dev-dependencies**

```
    ...
   "eslint-plugin-vue": "^4.5.0",
    ...
```

получаю собственно уже другую ошибку

![image](https://user-images.githubusercontent.com/44676144/51985777-c71db380-24af-11e9-8074-8ae7b691f9cd.png)

_костыльно так же решается установкой локально  eslint и eslint-loader._

----

Судя по тому как я понимаю работу, пакет установленный "глобально" ищет вызываемые зависимости у себя в директории и про проект ничего не знает.  И наоборот, локально установленный пакет хочет использовать методы "глобального", и ищет его так же в своей директории.  При этом явно указать расположение стандартными конфигами возможности нет, лоадеры и плагины eslint ищутся по маске внутренними механизмами

Это все довольно грустная картинка. Локально добавлять те зависимости, наполовину ради которых был вообще заведен тарс, так себе идея. И форкать его тоже не хочется, потому что при всей однотипности проектов есть те, в которых vue не нужен, а нужно что-то другое или вообще ничего не нужно.

Может быть я упускаю какое-то очевидное решение? Или как вариант при установке tars-cli прикладывать какой нибудь package-custom.json, как мы делаем при tars-init с zipом шаблона

**Comment by artem-malko** [comment]
Прежде всего, для работы с vue я бы рекомендовал vue-cli) 

В tars можно попробовать поиграться с https://webpack.js.org/configuration/entry-context/#context
То есть , поставить доп/ пакеты локально и настроить context на cwd

**Comment by pinkman-frontend-user** [comment]
vue-cli классный, но он про SPA. В наших кейсах SPA почти не встречается, это классические MPA, с вкраплениями динамики (фильтры, поиски, галереи и всякие аякс попапы с корзинами). Поэтому ТАРС подходит очень хорошо. 

Про контекст пошел читать, вернусь с результатами

**Comment by artem-malko** [comment]
@pinkman-frontend-user Как результаты?)

**Comment by artem-malko** [comment]
Пока закрою, если будут результаты — открою)
