### ISSUE TITLE
При сборке gulp build --min проблема

### ISSUE THREAD

**Issue by denis3865** [tars/tars#391]
Добрый день, собираю проект, по ключу --min и получаю два файла main.js и main.min.js. Все свои плагины ставлю в папке c плагинами в min виде. (ex. owl.carousel.min.js) . Но в исходном формате main.js все плагины которые я ставил минифицированные - тарс унимифицирует и за чего у меня только плагины на 9к строк кода что очень не удобно дописывать в него позже

**Comment by artem-malko** [comment]
Добрый день.

Если используется простая склейка js-файлов (workflow: 'concat'), то что было положено в плагины, то и будет в main.js склеено. То есть, если в plugins лежит минифицированный плагин, он же и в main.js таким же попадет. Можно положить не минифицированную версию просто. Тогда в main.js будет обычная версия, а в main.min.js уже сжатая.

**Comment by denis3865** [comment]
В tars-config у меня есть для js workflow: 'concat',
Но тем не менее код в исходном main.min.js не минифицированный. Хотя я кладку в папку plugins только .min
Верстку потом интегрирую на WordPress. Мне требуется прописывать доп JS , даже для простых форм

**Comment by artem-malko** [comment]
Хм, это странно, так как нету механизма, чтобы код минифицирвоанный стал неминифицированным. А можете сделать простой пример где-нить на гитхабе?

**Comment by artem-malko** [comment]
@denis3865 up
