### ISSUE TITLE
Отключение добавление hash кода

### ISSUE THREAD

**Issue by pashkes** [tars/tars#394]
Можно каким то образом отключить добавление hash кода для всех подключаемых файлов? Это очень мешает особенно когда используешь svg спрайт как отдельный файл

**Comment by impcyber** [comment]
Генерацию хеша отключить или изменить на свою в файле tars/tars.json
```
// Build options
tars.options = {
...
    build: {
        hash: tars.flags.release ? Math.random().toString(36).substring(7) : '',
```

**Comment by pashkes** [comment]
@impcyber спасибо, работает
