### ISSUE TITLE
Webpack build не подключает static

### ISSUE THREAD

**Issue by impcyber** [tars/tars#395]
Добрый день.

После развертывания нового проекта с Webpack я заметил, что после команды build в папке с билдом отсутствует папка static/js, соответственно, не подключаются скрипты на страницах. Однако, она почему-то генерируется в корне папки /build. 

![image](https://user-images.githubusercontent.com/1425691/54880789-13ef8c00-4e5a-11e9-8bbc-092da70913bb.png)

Все заработало как надо после изменений в webpack.config.js

```
path: path.resolve(`${(tars.isDevMode) ? `${tars.config.devPath}` : `${tars.config.buildPath}`}/${staticFolderName}/js`),
```
на
```
path: path.resolve(`${(tars.isDevMode) ? `${tars.config.devPath}` : `${tars.options.build.path}`}/${staticFolderName}/js`),
```
Это некий баг или я что-то возможно упустил при настройке изначально?

> $ tars -v
> [ TARS ]: TARS-CLI version: "1.10.10"
> [ TARS ]: TARS version in current project: "1.12.1"
> 
> $ npm -v
> 6.7.0
> 
> $ node -v
> v11.12.0
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 9.8 (stretch)
> Release:	9.8
> Codename:	stretch

**Comment by artem-malko** [comment]
@impcyber  Добрый день. Да, у нас баг. Если откроете pull request — будем очень рады!)
