### ISSUE TITLE
Как подключать jquery плагины?

### ISSUE THREAD

**Issue by SkiperX** [tars/tars#398]
Выбрал js через вебпак
теперь проблема с не-es6 плагинами

import $ from 'jquery/dist/jquery.min.js'
import 'selectric/public/jquery.selectric.min.js'
window.$ = $;

$(...).selectric is not a function

есть способ их импортировать?
пока просто тяну с cdn

**Comment by CcRaZyY** [comment]
нужен `workflow: modular`.
Важно! тогда нужно будет каждый файл js из любой папки подключать в main.js через import

**Comment by SkiperX** [comment]
стоит workflow: modular

**Comment by pashkes** [comment]
Там где та написал путь нужно писать имя npm или bower пакета, и всё

**Comment by Solunsky** [comment]
в **common.js**
`import $ from 'jquery'`;

В **tars-config.js**
`providePlugin: {$: 'jquery', jQuery: 'jquery', 'window.jQuery': 'jquery'}`

@SkiperX

**Comment by artem-malko** [comment]
Кажется разобрались?) Кто-нить сделает пулик в доку, если что-то не очень еще очевидно?) @CcRaZyY @pashkes @Solunsky ?

**Comment by CcRaZyY** [comment]
А нужно ли оно? В нынешние времена jquery мало используется в проектах, ну у меня точно.. Может просто в readme указать ссылку на эту статью и те кому это действительно нужно будут просто подключать

**Comment by SkiperX** [comment]
jquery работает

.selectric is not a function
gulp конкат выходит использовать, тк это либа без es6?

**Comment by SkiperX** [comment]
@artem-malko 
глянь плиз еще, я в этой теме отписался  https://github.com/tars/tars/issues/373
скорость сборки жутко тормозит работу
а так тарс понравился

**Comment by CcRaZyY** [comment]
> .selectric is not a function
У меня всё сработало.
`npm i -D selectric`

в файле static/js/main.js сделал `import "selectric";`

и в любом месте проекта он используется спокойно

**Comment by artem-malko** [comment]
@CcRaZyY про ссылку — хорошая идея!

**Comment by artem-malko** [comment]
В итоге закрываю тикет?) Если кто-то против — пишите, открою снова
