### ISSUE TITLE
Не билдятся .html файлы

### ISSUE THREAD

**Issue by devmodeone** [tars/tars#399]
Доброго времени суток, вопрос неинтересного характера, но все же вот так вот получилось...
Пытаюсь билдить проект (tars build), пишет, что проект успешно забилдился, все круто и классно, но тем не менее, не появляется никаких .html файлов, что весьма странно.

![ошибос](https://user-images.githubusercontent.com/50143327/56964600-2bf6b180-6b64-11e9-96f9-8ffa3fd8c991.png)

![список файлов](https://user-images.githubusercontent.com/50143327/56964649-4c267080-6b64-11e9-9373-577c080974c8.png)

![успешный билд](https://user-images.githubusercontent.com/50143327/56964687-5c3e5000-6b64-11e9-8cb0-1af04cb16ca3.png)

**Comment by artem-malko** [comment]
Добрый день.

В проекте есть хотя бы одна страница?

**Comment by devmodeone** [comment]
Да, разумеется. Имеется больше 20 страниц и различных компонентов. 

Для информации:
Препроцессор CSS: Scss
Шаблонизатор: Jade

Папки:
img / static / components

Все ровно такое же, как и в сливаемой верстке с гита. Изначально ругался сборщик на версии ES (переменные были объявлены в скриптах, как var, а не let), но это исправлено. Билд успешный, но так или иначе - .html Файлы н билдятся вовсе.

**Comment by artem-malko** [comment]
А файлы страниц какое расширение имеют?

**Comment by devmodeone** [comment]
.pug

**Comment by artem-malko** [comment]
Так, а что выбрано на этой строчке в tars-config.js https://github.com/tars/tars/blob/master/tars-config.js#L239 ?

**Comment by devmodeone** [comment]
> Так, а что выбрано на этой строчке в tars-config.js https://github.com/tars/tars/blob/master/tars-config.js#L239 ?

![image](https://user-images.githubusercontent.com/50143327/57122434-03e69880-6d86-11e9-8091-f225da5a8f21.png)

**Comment by artem-malko** [comment]
Это, конечно, хорошо, что вы скинули, но что в файле tars-config.js?)

**Comment by devmodeone** [comment]
> Это, конечно, хорошо, что вы скинули, но что в файле tars-config.js?)

Прошу извинить, неправильно понял. К сожалению, за рабочим PC буду только лишь в среду, пока попробую дома забилдить. Если будет ошибка - обязательно напишу сюда. Не заливал проект с работы в реп :(

**Comment by artem-malko** [comment]
@devmodeone up)

**Comment by artem-malko** [comment]
Видимо все ок) Если что, переоткрою)
