### ISSUE TITLE
Как задать title для новой страницы?

### ISSUE THREAD

**Issue by denis3865** [tars/tars#400]
Добрый день, очень простой вопрос но не понимаю как задать разный Title для страницы

Вот сам код страницы

doctype html
html(class="no-js", lang="ru")

  include ../components/head/head
  include ../components/preloader/preloader
  include ../components/header/header
  include ../components/home/home
  include ../components/about/about
  include ../components/portfolio/portfolio
  include ../components/why/why
  include ../components/team/team
  include ../components/plans/plans
  include ../components/reviews/reviews
  include ../components/latest/latest
  include ../components/callback/callback
  include ../components/footer/footer
  head
    +head(head.defaults)
  body.page
    |%=symbols=%
    +preloader()
    #container
      +header()

      +home()

      +about()

      +portfolio()

      +why()

      +reviews()

      +plans()

      +callback()

      +footer()
    script(src='%=static=%js/separate-js/pageable.min.js')
    script(src='%=static=%js/separate-js/svg4everybody.min.js')
    script svg4everybody();
    //- Main scripts. You can replace it, but I recommend you to leave it here
    script(src='%=static=%js/main%=hash=%%=min=%.js')

**Comment by artem-malko** [comment]
Добрый день.

Каждый  компонент умеет принимать данные. Например, `title` находится в компоненте `head`. В приведенном коде компонент `head` принимает дефолтный шейп данных. В них лежит вот такой набор данных (исходник: https://github.com/tars/tars/blob/master/templates/pug/markup/components/head/data/data.js):
```
head: {
    defaults: {
        title: 'default title',
        useSocialMetaTags: true
    }
}
```

Предположим, на другой странице нам нужен другой тайтл. Для этого в даннхы для  `head` заводим еще один шейп:
```
head: {
    defaults: {
        title: 'default title',
        useSocialMetaTags: true
    },

    contacts: {
        title: 'Contacts page title',
        useSocialMetaTags: true,
    }
}
```
И на странице с контактами подключаем `head` с нужными данными:
```
head
        +head(head.contacts)
```
