### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by trixter5** [tars/tars#401]
Появилась ошибка, которая "бегает" теперь практически по всем pug миксинам.
Не могу понять причину.
Удаляю из шаблона миксин, в котором ошибка, она оказывается в другом.
[21:53:21] File: markup\components\breadcrumbs\breadcrumbs.pug Event: change
[21:53:21] Starting 'html:compile-templates'...
[21:53:49] gulp-notify: [TARS notification]
An error occurred while compiling to html.
Look in the console for details.

Error details:

D:\WORK\2019\may\SLDK\project\markup\components\breadcrumbs\breadcrumbs.pug:2
    1| mixin breadcrumbs(data)
  > 2|     nav(aria-label="Page breadcrumb")
    3|         ol.breadcrumb
    4|             each val in data
    5|                 if data.active === "true"

Invalid string length

Есть мысли?

**Comment by artem-malko** [comment]
Честно говоря — совсем нет( Если есть проект на «потыкать» — было бы проще.

**Comment by artem-malko** [comment]
@trixter5 все еще повторяется? Если нет, то как пофиксилось?

**Comment by artem-malko** [comment]
Закрываю, если проблема повториться — переоткроем.
