### ISSUE TITLE
Как поменять stylus на sass?

### ISSUE THREAD

**Issue by denibudeyko** [tars/tars#402]
Как поменять stylus на sass?

**Comment by artem-malko** [comment]
Если проект уже начат — никак( Получится только начать новый с нужными опциями и код перенести руками.

**Comment by denibudeyko** [comment]
Проект не начат , лишь tars скачал

**Comment by artem-malko** [comment]
@denibudeyko тогда точно все просто) Прям при запуске будет возможность выбрать

**Comment by denibudeyko** [comment]
Спасибо, нашел)
