### ISSUE TITLE
Relative static path is incorrect

### ISSUE THREAD

**Issue by Arti3DPlayer** [tars/tars#403]
I included main css with the following path:
```
<head>
<link rel="stylesheet" type="text/css" href="%=static=%/main.css">
</head>
```

While development it works fine, and generate path like `/static/main.css`

Then after build if I will open generated file, my styles will not load, because correct path should be without leading slash: `static/main.css` instead of `/static/main.css`

I tried to change: `generateStaticPath: false` but didn't get any affect:

**Comment by impcyber** [comment]
Try add this in `<head>`:
```<base href="/">```

**Comment by artem-malko** [comment]
@Arti3DPlayer as I understand, you're trying to open dev-build. Dev-build is used for development only, to work with server.
`tars build` will generate correct build, which works without server. So, just try to `tars build`. Will wait for feedback)

**Comment by Arti3DPlayer** [comment]
great, thanks :)

**Comment by artem-malko** [comment]
@Arti3DPlayer :+1:
