### ISSUE TITLE
When will support  .net core ？

### ISSUE THREAD

**Issue by chenbigit** [tars/tars#404]
Tars now supports C++/Java/Nodejs/Php，Will support  .net core ？

**Comment by artem-malko** [comment]
I don't understand your question, sorry(
Tars — it's a framework for frontend only)

**Comment by bukhalo** [comment]
@chenbigit maybe wrong repo? https://github.com/TarsCloud/Tars

**Comment by chenbigit** [comment]
sorry, I got a wrong repo。
