### ISSUE TITLE
В wsl 2 на видовс не регистрирует изменение файла

### ISSUE THREAD

**Issue by NabAlexey** [tars/tars#405]
Не регистрирует изменения и не перезапускает сборку

**Comment by artem-malko** [comment]
Потребует время, чтобы найти винду(

**Comment by NabAlexey** [comment]
@artem-malko 
Так соре, эта проблема решается если закинуть проект в файловую систему wsl. Но есть другой баг, иногда browser sync перезагружает страницу без изменений, т.е. там какой-то баг толи browsersync перезагружает слишком рано когда еще все изменения не попали в каталог dev/ толи как-то пересобирается не до конца. Происходит с регулярной переодичностью.
Еще баг в wsl 2 когда пре запущенном проекте система не выключается и не перезагружается и висит бесконечно спинер, видимо виндовс не может кильнуть процесс. Все это указывает что wsl 2 еще сырой и много проблем.
Вообще переходил на wsl 2 с целью избавится от бага когда я не мог переименовать не пустой каталог во время запущенной сборки, в wsl 2 он отсутствует. 
Ишью наверно следует закрыть.

**Comment by artem-malko** [comment]
Закроем. Но, конечно, обидно, что wsl так работает(

**Comment by NabAlexey** [comment]
wsl 2*
