### ISSUE TITLE
Возможно ли добавить в tars такую возможность

### ISSUE THREAD

**Issue by denibudeyko** [tars/tars#406]
Понравилась такая возможность у другого сборщика
https://dibsssolutions.github.io/school/
т.е окрывает верстку на гитхаб и имеется возможность просмотреть все страницы + менять размеры экраны что бы посмотреть под все разрешения. Возможно ли такое добавить в TARS?

**Comment by artem-malko** [comment]
@denibudeyko конечно можно. Но я бы не хотел этого добавлять, так как такая функциональность доступна нам в дев. консоли Хрома. Там примерно такой же контрол есть, который позволит верстку глянуть в разных размерах с разными юзер-агентами.

Если добавлять в TARS — значит это надо будет поддерживать, а тут итак фич уже очень много. На скрине есть пример, как такое же включить в консоли Хрома.
<img width="890" alt="Screenshot 2019-10-22 16 52 13" src="https://user-images.githubusercontent.com/1823689/67275121-1d260180-f4ec-11e9-831b-42ca07390852.png">

**Comment by TIIGRUS** [comment]
@artem-malko я согласен с тобой по поводу инструментов хрома, однако это больше подойдет для демонстрации результата заказчику в удобной для него форме.

**Comment by artem-malko** [comment]
@TIIGRUS предлагаю вам самим сделать такую фичу)
Но я все же за девтулзы, так как они не только размер окна меняют, но и имитируют тач-события и многое другое.
