### ISSUE TITLE
How to add npm packages

### ISSUE THREAD

**Issue by vetras** [tars/tars#407]
Hello,

We have and old web project that is using tars as the build system.
Currently our external dependencies are the copied min js files from NPM into a "libraries" folder (webpack bundles all those).

I would like to add dependencies on `package.json` and them `import` them on JS.
Doing this throws "require is not a function" at runtime, on dev tools.

I have searched all the TARS docs but i cannot find anything that explains how to use a npm package within a tars project.

Can you help? provide a sample project that uses `lodash` from npm, for example?

**Comment by artem-malko** [comment]
Hi)

First of all, you can install any packages you want locally) Just 
```
npm i lodash
```
In your directory with project. But it depends on your config. I mean tars-config, js —» workflow. If you use `concat` — you can not use npm packages. In `concat` workflow all js files just concatenated to each other. If you need to use npm-pacakges, you have to switch from `concat` workflow to `modular`. In that case, you will use webpack us bundler. But, you need to require all libs by yourself.

**Comment by vetras** [comment]
Thanks! solved.
f you use concat — you can not use npm packages. 

I end up creating a new hello world project to understand how this works. Got `modular` to work and now i'm migrating the code to use this approach.
Will be a big PR :D

thanks

**Comment by artem-malko** [comment]
Cool.

And you asked about docs: https://github.com/tars/tars/blob/master/docs/en/js-webpack-processing.md?
