### ISSUE TITLE
Не компилируется папка с js

### ISSUE THREAD

**Issue by lex-pvl** [tars/tars#408]
При создании дефолтного шаблона и последующей его компиляции, папка с js файлами игнорируется.

**Comment by artem-malko** [comment]
А что в конфиге (tars-config) указано в параметре `workflow` и как выглядит содержимое файла с js-ом?

**Comment by lex-pvl** [comment]
В конфиге в параметре workflow указан concat, в js ничего особенного, просто alert

**Comment by artem-malko** [comment]
подозреваю, что проблема именно в prod режиме? Предлагаю добавить осмысленный код туда, так как alert просто вырезается uglify-ем

**Comment by lex-pvl** [comment]
Осмысленный код добавил, но ничего не изменилось. В конфиге поменял workflow на modular и все заработало.

**Comment by artem-malko** [comment]
@lex-pvl осмысленный код тоже мог быть выпилен, если нигде не использовался) Какой именно код был? Было бы круто увидеть репу с примером проекта

**Comment by artem-malko** [comment]
Закрываю issue. Если проблема все еще актуально — можно открыть снова.

**Comment by sinneren** [comment]
> Закрываю issue. Если проблема все еще актуально — можно открыть снова.

мне тоже это решение помогло, но можно комментарий получить. Почему при workflow concat не собирает JS из markup/static/js, а при modular - всё собирает?

Правда, несмотря на то, что он всё собрал, так задача в консоли не завершилась. Последний шаг `Finished "default" after..." и на этом этапе висит, не вышел работы. Вроде мелочь, но выглядит как ошибка.

**Comment by from-test-work** [comment]
А вот теперь и у меня такая проблемка.
Компилирует скрипт только при команде tars dev -l
Репозиторий с примером [https://github.com/from-test-work/goSurf-landing](https://github.com/from-test-work/goSurf-landing) файл ../components/header/header.js или static/js/main.js
Что бы я туда не писал - вотчер не показывает статус изменения, ну и сам скрипт не компилиться

---------------
Конфиг системы

$ node -v
v14.15.3

$ npm -v
6.14.10

$ gulp -v
CLI version: 2.3.0
Local version: 4.0.2

$ tars -v
[ TARS ]: TARS-CLI version: "1.12.2"
[ TARS ]: TARS version in current project: "1.14.2"
