### ISSUE TITLE
Почему нельзя использовать сборщик с node v12?

### ISSUE THREAD

**Issue by denibudeyko** [tars/tars#409]
Добрый день, после переустановки системы установил последнюю стабильную node v12 и получил ошибку. Вычитал на форуме что надо установить gulp v4, обновил package json и установил но там вылезла другая проблема. Решил проблему установкой node v11 который работает с gulp 3.9.1 
Вопрос, будет ли поддержка gulp 4, ибо node v12 конфликтует с gulp v3

**Comment by impcyber** [comment]
@denibudeyko Согласно ишью https://github.com/gulpjs/gulp/issues/2324
gulp3 больше не поддерживается

**Comment by artem-malko** [comment]
@denibudeyko будет) Вот ближайшие дни постараюсь запилить уже

**Comment by denibudeyko** [comment]
@artem-malko Спасибо большое

**Comment by artem-malko** [comment]
@denibudeyko @impcyber все сделано) Можно обновляться
