### ISSUE TITLE
Как быть когда много компонентов?

### ISSUE THREAD

**Issue by denibudeyko** [tars/tars#410]
Добрый день ,есть верстка большого проекта на более 30 страниц, и первый запуск длиться достаточно долго, и самих компонентов достаточно много
_Finished 'main:build-dev' after 1.42 min_

Скажите можно как то улучшить скорость инициализации проекта?

**Comment by bukhalo** [comment]
> Добрый день ,есть верстка большого проекта на более 30 страниц, и первый запуск длиться достаточно долго, и самих компонентов достаточно много
> _Finished 'main:build-dev' after 1.42 min_
> 
> Скажите можно как то улучшить скорость инициализации проекта?

Программно – скорее всего никак. Есть некоторые советы по оптимизации скорости сборки, но существенного результата они обычно не дают. Ну зависит от того, как вы собираете проект. Шаблонизатор? Webpack?

**Comment by denibudeyko** [comment]
Некоторые доп методы уже использую
Отключил индексацию файлов
Добавил в исключение брэдмаура

Так же эта проблема случается если редактирую кусок файла что на всех страницах 
К примеру у меня 30 страниц jade, при изменение хэдара, компилируется все страницы аж 13 секунд. Может какие то методы есть сократить время, да и сократить значительно, ибо если к примеру надо менять весь header, это будет очень долго

**Comment by artem-malko** [comment]
@denibudeyko если кусок много где используется — то приходится все места использования перекомпилить) К сожалению, тут никуда не денешься.

**Comment by bukhalo** [comment]
@denibudeyko кстати если у вас действительно Jade (не Pug) хочу отметить, что он весьма медленный, рекомендую перейти на Pug хотя бы.

**Comment by denibudeyko** [comment]
@bukhalo Разве Это не одно и то же?)
https://gist.github.com/neretin-trike/53aff5afb76153f050c958b82abd9228

**Comment by bukhalo** [comment]
> @bukhalo Разве Это не одно и то же?)
> https://gist.github.com/neretin-trike/53aff5afb76153f050c958b82abd9228

В целом – одно и то же. Но после того, как Jade стал Pug-ом в нём добавили много улучшений, в том числе касающихся производительности.

**Comment by bukhalo** [comment]
@artem-malko наверное можно закрывать?
