### ISSUE TITLE
Сборка зависает в конце

### ISSUE THREAD

**Issue by pinkman-frontend-user** [tars/tars#417]
В процессе сборки "tars build -m" сборка "повисает" на последнем шаге, причём в консоле вот такая ситуация:
[скрин](https://imgur.com/a/ccuAU7x)
mac os 10.15.3
node v13.8.0

Есть идеи с чем может быть связано?

**Comment by artem-malko** [comment]
@pinkman-frontend-user привет)

А сборка при этом происходит? В папке build все как надо?

**Comment by pinkman-frontend-user** [comment]
@artem-malko да, сборка собирается и всё ок. Что подозрительно

**Comment by artem-malko** [comment]
@pinkman-frontend-user так значит это только в docker? А если прям в родной ОС запустить?

**Comment by pinkman-frontend-user** [comment]
В родной ОС-и такое же поведение. Я скриншот оттуда приложил в первом сообщении

**Comment by pinkman-frontend-user** [comment]
Развернул нулевой проект и с ним такая же ситуация, но только если в настройках TARS-a стоит 
"js": {
  "workflow": "modular"
}
Продолжаю копать дальше

**Comment by pinkman-frontend-user** [comment]
Изолировал проблему. Проблему в том, что в режиме "tars build -m" в webpack.config.js
в поле watch всегда прилетает true.

**Comment by artem-malko** [comment]
@pinkman-frontend-user спс за расследование) Займусь фиксом!

**Comment by marselbairam** [comment]
Столкнулся с аналогичной проблемой, но заметил еще несколько особенностей:
1) Теперь все пути в HTML-файлах указывается не правильно (на уровень выше ../)
2) Если запустить `tars build --min` несколько раз, то css файлы дублируются в папке, т.е после трех циклов получаем следующий результат:
```
- main.css
- main.css.map
- main.min.css
- main.min.min.css
- main.min.min.min.css
```

**Comment by artem-malko** [comment]
@marselbairam не могу воспроизвести( Есть тестовый проект? И какая версия tars и tars-cli используются. Можно узнать, если запустить в папке с проектом
```
tars -v 
```

**Comment by artem-malko** [comment]
@pinkman-frontend-user фикс на бою) В версии 1.14.2

**Comment by marselbairam** [comment]
@artem-malko 
tars-cli 1.12.2
tars 1.14.1

[start-template.zip](https://github.com/tars/tars/files/5085505/start-template.zip)
