### ISSUE TITLE
Что произошло со сборщиком?? 

### ISSUE THREAD

**Issue by from-test-work** [tars/tars#421]
Была стабильная рабочая версия 1.12. Решил обновиться до последней версии 1.14 17.09.20 числа  и все перестало адекватно работать. Проект стартует быстро, запускается и виснет. 
После изменения в файлах разработки вотчер не обновляет статут и не реагирует на изменения (что логично).
В диспетчере задач Node просто вешается
На ноутбуке вообще не работает даже выше перечисленное, а вот стационарник - с трудом, но вытягивает, и то через некоторое время после старта, т.к тоже висит.
У всех есть такая проблема, или это только у меня??

**Comment by artem-malko** [comment]
Только что завел пустой проект на tars 1.14.2 Подскажите, какой конфиг в tars.json?

**Comment by from-test-work** [comment]
**svg**: {
        active: true,
        // symbols, sprite
        **workflow**: '**symbols**',
}

**css**: {
        // concat, manual
        **workflow**: '**concat**'
}

 **js**: {
        // concat, modular
        **workflow**: '**modular**',
}


/**
 * Templater
 * Available 'pug', 'jade' and 'handlebars'
 * @type {String}
 */
    **templater**: '**pug**',

 /**
 * Css-preprocessor
 * Available 'scss', 'less' or 'stylus'
 * .sass extension is supported if cssPreprocessor is 'scss'
 * @type {String}
 */
    **cssPreprocessor**: '**scss**',


Остальное не трогал

**Comment by artem-malko** [comment]
@from-test-work прям со старта тормозит? Даже вот пустой проект?

**Comment by from-test-work** [comment]
По идее после обновления что то пошло не так с компонентами. 
Развернул голый сборщик, работает мгновенно
Все таки это локальная проблема.
