### ISSUE TITLE
Как передать из компонента имя partials?

### ISSUE THREAD

**Issue by wizzzart** [tars/tars#424]
Привет. Использую handlebars и его partials. Partial определяется следующим образом:
```
{{#> partial-name}}
  Тут контент
{{/partial-name}}
```

Для вызова partial используется следующий синтаксис: 
`{{> partial-name }}`

Мне нужно имя частицы partial передать через компонент. Можно это как-то сделать?
Пример:
```
{{#each navTabs}}
    <div class="tab-pane fade {{#if tbsActive}} active{{/if}}">{{> сюда нужно передать имя partial }}</div>
{{/each}}
```

Проблема в том, что конструкция типа 
`{{> {{partialName}} }}` естественно не работает.

**Comment by artem-malko** [comment]
Привет, придется курить доки https://handlebarsjs.com/ ) Сам TARS handlerbars никак не ограничивает)

**Comment by wizzzart** [comment]
Не сообразил, то это функционал handlebars, а не тарса.
Ташение такое, если кому-то вдруг понадобится:
`{{> (lookup . 'partialName') }}`
Спасибо

**Comment by artem-malko** [comment]
Супер, что решение нашлось)
