### ISSUE TITLE
Ideas for 2.0.0 version

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#59]
- [ ] Disable IE8 support.
- [ ] Add ES6 with webpack/browserify/systemjs.
- [ ] Add templaters.
- [ ] Another workflow for SVG. Use sprite of symbols instead usual svg-sprite.

**Comment by artem-malko** [comment]
English only in this discussion.

**Comment by alexHlebnikov** [comment]
Add post-processors.
Add Angular/Ember/Backbone support.

**Comment by artem-malko** [comment]
@alexHlebnikov what does Angular/Ember/Backbone support mean? Boilerplate for that frameworks?

**Comment by artem-malko** [comment]
@alexHlebnikov post-processors have to be implemented before 2.0 version.

**Comment by TrySound** [comment]
@artem-malko @alexHlebnikov I think this issue for bower. TARS is a builder, not a framework.

**Comment by artem-malko** [comment]
@alexHlebnikov @TrySound of course not for bower. These frameworks need special file structure for theirs special entities. So, we could download source code for that libs from bower, but TARS need to have ready FS for them.
@alexHlebnikov I've understood you correctly?

**Comment by alexHlebnikov** [comment]
@artem-malko yes, I'm talking about file structure.

**Comment by TrySound** [comment]
@artem-malko Okay. For this will be helpful file structure with .gitignore files. So no need to have create-fs task. The other way is using yo-gen.

**Comment by TrySound** [comment]
@artem-malko But the lib must be loaded by bower.

**Comment by artem-malko** [comment]
@TrySound :+1: 
I'm not sure about yo-gen in that place, i think, that there could be some problems with it.

**Comment by TrySound** [comment]
@artem-malko Tasks not for this.

**Comment by artem-malko** [comment]
@TrySound why not? It can create fs too.
If there will not be any problems with yo, so it'll be yo.

**Comment by Hazantip** [comment]
Add support sass @imports

**Comment by vova-white** [comment]
Is it possible add a partition sprites into groups?
## Example

### Static
```
static/
    └── img/
        └── sprite/
            └── 96dpi/
                └── ui/
                    └── ui_1.png
                    ...
                    └── ui_&infin;.png
                └── social/
                    └── social_1.png
                    ...
                    └── social_&infin;.png
```
### Ready build
```
dev/
    └── static/
        └── img/
            └── png-sprite/
                └── sprite_ui.png
                └── sprite_social.png

```

**Comment by artem-malko** [comment]
@vova-white it is quite specific issue, so you have to implement it by yourself by using user-tasks
