### ISSUE TITLE
Add filtering style-files with underscore prefix

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#63]
If style-file has less/styl/scss extension and underscore prefix, user needs to import this file to compile it.
If style-file has css extension and underscore prefix, TARS just makes a copy of this file. User have to include this file to html by himself.
In all other cases, all files will be concatinated into one file.

**Comment by TrySound** [comment]
I use [^_] for exclude file from concatenating files.

**Comment by artem-malko** [comment]
Connected #42

**Comment by artem-malko** [comment]
@import 'markup/modules/footer/_partial'; для импортов

**Comment by artem-malko** [comment]
ready in version-1-4-0
