### ISSUE TITLE
Add formatting for CSS and HTML in build

### ISSUE THREAD

**Issue by d6233** [tars/tars#69]
В чате обсуждали по поводу того что jade компилятор на выходе делает не отформатированный html, есть плагин gulp-prettify который решает эту проблему, если возможно сделать такую опцию при build, ну и тоже самое css через gulp-csscomb.

We've discussed some days ago, that jade makes not-formatting HTML. Sometimes it's usefull to have beauty HTML in build. And it would be nice to have something like that for CSS. I'd recommend gulp-prettify for HTML and gulp-csscomb for CSS.

**Comment by artem-malko** [comment]
@d6233 what about csscomb and prettify config? We need to add it  to the root of builder? What kind of options have to be by default?

**Comment by d6233** [comment]
HTML
	indent_size: 1,
	indent_inner_html: true,
	indent_char: '\t',
	preserve_newlines: true,
	max_preserve_newlines: 0,
	unformatted: true,
	end_with_newline: false
CSS
"always-semicolon": true,
    "block-indent": "\t",
    "color-case": "lower",
    "color-shorthand": true,
    "element-case": "lower",
    "eof-newline": false,
    "leading-zero": false,
    "quotes": "single",
    "remove-empty-rulesets": true,
    "space-after-colon": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": " ",
    "space-before-closing-brace": "\n",
    "space-before-colon": "",
    "space-before-combinator": " ",
    "space-before-opening-brace": " ",
    "space-before-selector-delimiter": "",
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": true

**Comment by artem-malko** [comment]
I've got some question:
1) indent_char: '\t', – why tabs? May be it would be more comfortable to use spaces?
2) unformatted: true, – what does it mean?
3) "block-indent": "\t", – the same question as the first)
4) "quotes": "single", – i think, this could break the following code:
```html
<script>
<div class="qwe"></div>
```

**Comment by artem-malko** [comment]
@d6233 up!

**Comment by artem-malko** [comment]
@d6233 up! Could you ask my questions from Apr11?

**Comment by d6233** [comment]
Я тебе писал, или в чате, или в вк
К табам просто привык, с ними мне проще.
А вообще я просто потыкал настройки туда сюда, меня устроило как оно форматирует, сильно не вникал...Сейчас использую pretiffy для handlebars, и настройки в scss форматирования, в csscomb же можно разные правила разделить, типа позиционирование, цвета, шрифт, и т.д.

**Comment by artem-malko** [comment]
Add only prettify for HTML.
Ready in version-1-4-0.
