### ISSUE TITLE
Possibility to copy all static files into the root of build

### ISSUE THREAD

**Issue by d6233** [tars/tars#70]
Иногда нужно, что бы файлы со статикой в build версии лежали в корне, а не в папке static, если можно реализуй пожалуйста.

Sometimes it's quite usefull to move keep all static files in root directory directly, not in static folder. Could you implement it, if it possible?

**Comment by artem-malko** [comment]
Interesting task. I'll marked it as enhancement. But it'll be implemented in next version, cause there a lot of features already. Sorry)

**Comment by artem-malko** [comment]
@d6233 что-то получается слишком круто иметь опцию или флаг для такого поведения сборщика. Если проблема все еще актуальна, я могу помочь написать user-task, который это будет делать. Пока не могу придумать, чтобы впилить это без использования конфигов или флагов.

**Comment by d6233** [comment]
Причём тут опции или флаги?Я всего лишь хотел что бы работало так http://prntscr.com/8jiti8
Сейчас допустим обязательно должна быть папка static или другое название, а хотелось бы что  можно было просто без неё в корне все файлы лежали

**Comment by artem-malko** [comment]
@d6233 Данная опция не для этого создана. Она нужна только для создания файловой структуры. Но я подумаю, как можно именно это место поэксплуатировать.
