### ISSUE TITLE
Padding in spritesmith

### ISSUE THREAD

**Issue by sPaTRoL** [tars/tars#74]
When zooming in the browser appears edge of another image. It would be nice to make padding 1px in spritesmith.
P.S. Normalize.css updated to version v3.0.2.
P.S.S. В русской документации в разделе "Работа с изображениями" абзацы слились: "SVG изображения склеиваются в один SVG-спрайтSVG-изображения в release-версии минифицируются".

**Comment by artem-malko** [comment]
Will be implemented in 1.3.0

**Comment by artem-malko** [comment]
ready in 1.3.0
