### ISSUE TITLE
Add font generator

### ISSUE THREAD

**Issue by artem-malko** [tars/tars#8]
Добавить возможность генерации css для шрифтов в проекте.
Add font generator (from ttf or otf to svg, woff, woff2) and css generator for this font.

**Comment by artem-malko** [comment]
Также найти (или написать свой) генератор различный расширений файла шрифта.

**Comment by artem-malko** [comment]
Приглашается народ, для решения проблемы)
You are welcome to solve this problem)

**Comment by Grawl** [comment]
Я использую [webfonts](https://www.npmjs.com/package/webfonts) для этого

**Comment by artem-malko** [comment]
@Grawl он генерирует шрифты очень большого размера(

**Comment by Grawl** [comment]
Да, но зато он работает “из коробки” – не надо ставить кучу всего.

**Comment by artem-malko** [comment]
@Grawl этого мало. В шрифтах размер файла имеет критическое значение.

**Comment by TrySound** [comment]
[Fontie](https://fontie.flowyapps.com/) - отличная штука, но они не дают никакого API или инструментария.

**Comment by Grawl** [comment]
@TrySound ну так они настроили свой сервак и управляют им самостоятельно, API такого сервиса по-любому был бы платным, так как однозначно увеличил бы число запросов. При этом поставить их систему себе не дают не потому что жадные, а потому что у них нет времени всё это оформлять как отдельный пакет.

**Comment by artem-malko** [comment]
https://github.com/ecomfe/fontmin

**Comment by artem-malko** [comment]
Ждем fontmin. Очень многообещающий проект.

**Comment by artem-malko** [comment]
Нет смысла. ТАкие генераторы все равно будут делать достаточно большие шрифты.
