### ISSUE TITLE
Вложенность модулей

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [tars/tars#80]
Здравствуйте,
Иногда возникает необходимость использовать модуль в модуле.
{{> navigation/navigation navigation}} при вызове этой конструкции в другом модуле достается сама верстка без заполнения данными из /navigation/data/data.js.

**Comment by artem-malko** [comment]
data модуля:
```javascript
module: {
    main: {
        title: 'module title'
    },
    secondary: {
        title: 'module title'
    },
    view2Data: {
        title: 'view2Data title'
    }
}
```
Подключение модуля на странице:
```handlebars
{{> module/moduleView1 module}}
```
Мы передаем весь объект с данными в шаблон.
Затем внутри moduleView1:
```handlebars
{{main.title}} или {{secondary.title}}
{{> module/moduleView2 view2Data}}
```
Чтобы получить title, нам нужно указать, от какого типа даных title берем, так как изначально мы в шаблон весь объект с данными передали.
А при подключении module/moduleView2 мы передаем объект view2Data.

При таком подходе есть проблема, в основном шаблоне moduleView1 нужно напрямую указывать, какого типа title нужно использовать. Нам же хочется в page передать не только объект с данными, но и тип данных. То есть вот так:

```handlebars
{{> module/moduleView1 module.main}}
```
Тогда внутри moduleView1:
```handlebars
просто {{title}}
```
Осталось решить проблему с передачей данных в подключаемый партиал moduleView2. Для решения этой проблемы предлагаю немного изменить данные для модуля:
```javascript
module: {
    main: {
        title: 'module title',
        view2Data: {
            title: 'main view2Data title'
        }
    },
    secondary: {
        title: 'module title',
        view2Data: {
            title: 'secondary view2Data title'
        }
    }
}
```
В этом случае мы можем подключать партиал следующим образом:
```handlebars
{{main}}
{{> module/moduleView2 view2Data}}
```

Надеюсь вопрос решен?)

**Comment by artem-malko** [comment]
@AlexanderBukhtaty пожалуй внесу данный пример в доку.

**Comment by AlexanderBukhtaty** [comment]
Извините просто это мое 1-ое issue и 2-ой день с node.js goulp и tars.
попытаюсь описать
сейчас вы расширяете объект module вручную в родительском модуле.
хотелось бы что бы автоматом брал и расширял module новым объектом(атрибутом) module2 из подключаемого модуля.
например module2/data/data.js содержит большой объем информации, дабы не переписывать каждый раз портянку нужно сделать расширение объекта module автоматом с возможностью переопределения атрибута module2(подключаемых модулей).

Маленький листинг
## Module1
markup/modules/module1/data/data.js
```javascript
module1: {
	title : "title", 
	description : "description", 
}
```
markup/modules/module1/module1.html
```
<div>
 <h2>{{title}}</h2>
 <p>{{description}}</p>
 {{> module/module2 module2}}
</div>
```
## Module2
markup/modules/module2/data/data.js
```javascript
module2: {
	items : [ 
		{href : "#", text : "text"},
		{href : "#", text : "text"},
		{href : "#", text : "text"},
	],
...
}
```
markup/modules/module1/module1.html
```
<ul>
	{{#each items}}
		<li><a href="{{href}}">{{text}}</li>
	{{/each}}
</ul>
```

## Результат 
### расширенный объект module1 в module1/data/data.js
```javascript
module1: {
	title : "title", 
	description : "description",
	module2: {
		items : [ 
			{href : "#", text : "text"},
			{href : "#", text : "text"},
			{href : "#", text : "text"},
		],
	...
	} 
}
```
### вывод результата работы шаблонизатора (module1/module1.html)
```
<div>
	<h2>title</h2>
	<p>description</p>
	<ul>
		<li><a href="#">text</li>
		<li><a href="#">text</li>
		<li><a href="#">text</li>
	</ul>
</div>
```
как то так. 
предполагаю что надо в gulp-compile-handlebars лезть?.

**Comment by artem-malko** [comment]
Расширять точно не вариант. А вот прокинуть объект с данными в конкретный модуль — вот это стоит подумать.

**Comment by artem-malko** [comment]
@AlexanderBukhtaty обновил доки на эту тему. Можно посмотреть в ветке version-1-4-0 https://github.com/tars/tars/blob/version-1-4-0/docs/ru/html-processing.md#Работа-с-модулями-и-данными-в-handlebars
