### ISSUE TITLE
increase compile time

### ISSUE THREAD

**Issue by dumperize** [tars/tars#81]
Why growing compile time?
I start project: 
- - - - - 
[ 12:01:49 ] File: markup\modules\header\header.scss Event: change
[ 12:01:49 ] Starting 'css:compile-css'...
. . .
[ 12:01:49 ] Finished 'css:compile-css' after 451 ms
- - - - -  

20 minutes later: 

- - - - - 
[12:24:00] Starting 'css:compile-css'...
....
[12:24:14] Finished 'css:compile-css' after 14 s
- - - - - 

i am reboot gulp 
and start again: 

- - - - - 
[12:34:42] Starting 'css:compile-css'...
....
[12:34:43] Finished 'css:compile-css' after 591 ms
- - - - - 

again everything works quickly
Every 20 minuts i must reboot gulp... very uncomfortable.

it may be possible something to do this?

**Comment by artem-malko** [comment]
@dumperize could you send me your markup directory?

**Comment by dumperize** [comment]
This is bug occurs in module \tars\markup\modules\header
because i have 6 *.scss files in it. Maybe tars dont support this?

I have one .scss file in another modules. If i change it project compiles fast. 

This is my markup directory: 
https://www.dropbox.com/s/o8fy71ueilgkc21/markup.zip?dl=0

**Comment by dumperize** [comment]
And also (for the experiment) i change tars\tars\tasks\css\compile-css.js 
add subfolder for css
- - - - 
scssFilesToConcatinate.push(
...
    './markup/modules/**/*.scss'
);
- - - -

**Comment by dumperize** [comment]
and also i hook up gulp-beml

**Comment by artem-malko** [comment]
@dumperize is there any problems with 1.2.7?

**Comment by artem-malko** [comment]
@dumperize it seems, taht it was a problem of old node-sass. So, node-sass has been updated. This issue will be reopened in case this problem is returned.
