### ISSUE TITLE
Remove jsPathsToConcat*ModulesJs files from js:move-separate

### ISSUE THREAD

**Issue by owanturist** [tars/tars#94]
Опции `jsPathsToConcatBeforeModulesJs` и `jsPathsToConcatAfterModulesJs` позволяют конкатенировать js файлы по шаблону в начало и конец  `main.js` соответственно.

Вполне резонно, исключать перечисленные шаблоны/файлы из бандла задачи `js:move-separate`.

**Comment by artem-malko** [comment]
Так они и так туда не включены)
```javascript
    gulp.src('./markup/' + tarsConfig.fs.staticFolderName + '/js/separate-js/**/*.js')
```

**Comment by owanturist** [comment]
Я могу в `/js/separate-js` закинуть файл и указать к ему путь в одной из `jsPathsToConcat*`.
В итоге файл будет и в общем бандле, сконкатенированный с остальными js, и в `separate` бандле.

**Comment by artem-malko** [comment]
@owanturist типа защита от дурака?

**Comment by owanturist** [comment]
@artem-malko называй как хочешь =)

**Comment by artem-malko** [comment]
@owanturist Ладно, делай)
